VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <fields>
        <fullName>CCPM_dynamicECODE__c</fullName>
        <label>Dynamic ECODE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_smsTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SMS Template</label>
        <referenceTo>CCPM_smsTemplate__c</referenceTo>
        <relationshipLabel>SMS Messages</relationshipLabel>
        <relationshipName>CCPM_smsMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_smsTemplate__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>CCPM_smsTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_followupMessage__c</fullName>
        <label>Followup Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_initialMessage__c</fullName>
        <label>Initial Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>SMSTEMP-{000000}</displayFormat>
        <label>SMS Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_ActualSMSScheduleDateTime__c</fullName>
        <label>Actual SMS Schedule Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_CampingFollowUpMessageTemplate__c</fullName>
        <label>Camping FollowUp Message Template</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_DismissedLead__c</fullName>
        <description>This field is created to reference in Apex for checking dismissed Leads.</description>
        <formula>AND(CCPM_IsCartDismissed__c, 
CCPM_DismissedChannel__c == &apos;Digital&apos;, 
OR(RecordType.Name == &apos;Customer Cart&apos;,RecordType.Name == &apos;Prospect Cart&apos;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DismissedLead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeEcode__c</fullName>
        <formula>(Store__r.CCPM_storeEcode__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Ecode</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_CampaignMemberTriggerHandlerHelper.cls
/**
*@name          CCPM_CampaignMemberTriggerHandlerHelper 
*@author        Sriraman Sridharan (Deloitte)
*@date          10/05/2017
*@description   This is a helpper class for CCPM_CampaignMemberTriggerHandler
*@Class         CCPM_CampaignMemberTriggerHandler
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Sriraman Sridharan                 10/05/2017   Initial Implementation.
Bharath Ammanamanchi               02/15/207    Code cleanup. 

*/
public class CCPM_CampaignMemberTriggerHandlerHelper {
    public static Map<String, BusinessHours> mapBusinessHoursNameRec = CCPM_utility.mapGetBusinessHours();
    
    
     /**
@author        Bharath Ammanamanchi(Deloitte)
@description   Method to update the Lead on Campaign Member update
@param         Lead, Map<String, Account>
@return        CCPM_SMSMessage__c
*/
    public static void updateLeadFromCampaignMemeber(Lead objLead, Campaign objCampaignIn){
        if(objLead != null && objCampaignIn != null && CCPM_Collection.isNotNullEmpty(objCampaignIn.CCPM_smsTemplates__r)){
            CCPM_leadTriggerHandlerHelper.calculateActualSMSScheduleDateTime(objLead);
            objLead.CCPM_CampingFollowUpMessageTemplate__c = objCampaignIn.CCPM_smsTemplates__r[0].CCPM_followupMessage__c;
        }
    }
     /**
@author        Bharath Ammanamanchi(Deloitte)
@description   Method to create sms message custom object to send initial messages for Campaigns
@param         Lead, Map<String, Account>
@return        CCPM_SMSMessage__c
*/
    public static CCPM_SMSMessage__c createSMSForCampaignMember(Lead objLead, Campaign objCampaignIn){
        CCPM_SMSMessage__c objSMSMsg = null;
        if(objLead != null && objCampaignIn != null && CCPM_Collection.isNotNullEmpty(objCampaignIn.CCPM_smsTemplates__r) && !objLead.CCPM_DismissedLead__c){ 
            CCPM_smsTemplate__c objSMSTemp = objCampaignIn.CCPM_smsTemplates__r[0];
            String strMessage = objSMSTemp.CCPM_initialMessage__c;
            objSMSMsg = CCPM_utility.createRecordsForSmsMessageObject(objLead,strMessage,objLead.CCPM_mobileNumber__c,Label.CCPM_leadTypeCampaignInitialSMSPart1,Label.CCPM_taskCommunicationOutbound,objLead.CCPM_ActualSMSScheduleDateTime__c,Label.CCPM_liveTextPhoneNumber);
            if(objSMSMsg != null){
                objSMSMsg.CCPM_smsTemplate__c = objSMSTemp.id;
                objSMSMsg.CCPM_dynamicECODE__c = objLead.CCPM_storeEcode__c;
            }
        }
        return objSMSMsg;
    }
}