VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <encrypted>true</encrypted>
        <label>Account Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_logLevelSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to set the default logging</description>
    <fields>
        <fullName>CCPM_IsDebugLogged__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If True, log debug-level message in the Org</inlineHelpText>
        <label>Log Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isErrorLogged__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If True, log error-level messages in this Org</inlineHelpText>
        <label>Log Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isInfoLogged__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If True, log info-level messages in this Org</inlineHelpText>
        <label>Log Info</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isWarnLogged__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If True, log warning-level messages in this Org</inlineHelpText>
        <label>Log Warning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_purgeLogAfter__c</fullName>
        <inlineHelpText>Number of days that log are keep in this Org. Logs are automatically deleted if the
Apex Batch is setup</inlineHelpText>
        <label>Purge Log After</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Log Level Settings</label>
</CustomObject>

VZDEV/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <label>Account Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/LOG_LogMessage__c.object
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <fields>
        <fullName>CCPM_age__c</fullName>
        <description>Age in Days</description>
        <formula>TODAY() - DATEVALUE(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Age in Days</inlineHelpText>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_debugLevel__c</fullName>
        <description>Debug Level</description>
        <label>Debug Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_integrationPayload__c</fullName>
        <description>If log is integration related show xml payload</description>
        <inlineHelpText>If log is integration related show xml payload</inlineHelpText>
        <label>Integration Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_logCode__c</fullName>
        <description>The exception error code of custom org code for record</description>
        <inlineHelpText>The exception error code of custom org code for record</inlineHelpText>
        <label>Log Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_message__c</fullName>
        <description>Message to log</description>
        <inlineHelpText>Message to log</inlineHelpText>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_referenceId__c</fullName>
        <description>The related record Id</description>
        <inlineHelpText>The related record Id</inlineHelpText>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_referenceInfo__c</fullName>
        <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
        <inlineHelpText>The related record info (e.g. Apex Batch Job Id, Contact etc)</inlineHelpText>
        <label>Reference Info</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_sourceFunction__c</fullName>
        <description>The originating function in the class/component</description>
        <inlineHelpText>The originating function in the class/component</inlineHelpText>
        <label>Source Function</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_source__c</fullName>
        <description>The originating class/component of log message</description>
        <inlineHelpText>The originating component of log message</inlineHelpText>
        <label>Source</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_stackTrace__c</fullName>
        <description>Raw exception stack trace for unhandled errors</description>
        <inlineHelpText>Raw exception stack trace for unhandled errors</inlineHelpText>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_timer__c</fullName>
        <description>The time in milliseconds for the transaction (e.g. For integration/batch apex messages it might be the time taken to process)</description>
        <inlineHelpText>The time in milliseconds for the transaction (e.g. For integration/batch apex messages it might be the time taken to process)</inlineHelpText>
        <label>ExecutionTime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_testDataUtility.cls
/********************************************************************************************************
* @author       Deloitte
* @description  This test class is the framework used to generate test data to be used by the other test classes
* @date         2015-06-29
* @group        Message Logs - Test Classes
*********************************************************************************************************/
@isTest
public class CCPM_testDataUtility {
   
    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method generates a Log Message Custom setting with the parameters provided as input
    * @param        error (Boolean): indicates if the error logs must be logged
    * @param        warning (Boolean): indicates if the warning logs must be logged
    * @param        info (Boolean): indicates if the info logs must be logged
    * @param        debug (Boolean): indicates if the debug logs must be logged
    * @param        logPurge (Boolean): the number of day before the log messages must be deleted
    * @return       void
    *********************************************************************************************************/
    public static CCPM_logLevelSetting__c generateErrorMgtCustomSetting(Boolean error, Boolean warning , Boolean info, Boolean debug, Integer logPurge)    
    {
       //insert custom setting
       CCPM_logLevelSetting__c setg = new CCPM_logLevelSetting__c();
       setg.Name = 'Default';
       setg.CCPM_IsDebugLogged__c = debug;
       setg.CCPM_isErrorLogged__c = error;
       setg.CCPM_isInfoLogged__c = info;
       setg.CCPM_isWarnLogged__c = warning;
       setg.CCPM_purgeLogAfter__c = logPurge;
       insert setg;
        
       return setg;
    }
 
    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method generates a list of test accounts
    * @param        nrOfAccounts (integer): the number of accounts to be created
    * @param        nameRoot (String): the rootname of the accounts being generated
    * @param        executeInsert (Boolean): True of the DML insert must be executed or not, False otherwise
    * @return       List<Account>: the list of generated accounts
    *********************************************************************************************************/
    public static List<Account> generateAccounts(integer nrOfAccounts, String nameRoot, Boolean executeInsert)
    {
        List<Account> accList = new List<Account>();
        for (integer i=1; i<= nrOfAccounts; i++)
        {
            Account acc = new Account();
            acc.Name = nameRoot + ' - ' + String.valueOf(i);
            acc.CCPM_accountNumber__c=''+i;
            accList.add(acc);
        }
        if (executeInsert)
            insert accList;
        
        return accList;
    }

    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method generates a list of test contacts
    * @param        nrOfContacts (integer): the number of contacts to be created
    * @param        nameRoot (String): the rootname of the contacts being generated
    * @param        linkToAccount (Account): the account to which the contact must be linked to
    * @param        executeInsert (Boolean): True of the DML insert must be executed or not, False otherwise
    * @return       List<Contact>: the list of generated contacts
    *********************************************************************************************************/
    public static List<Contact> generateContacts(integer nrOfContacts, String nameRoot, Account linkToAccount, Boolean executeInsert)
    {
        List<Contact> ctcList = new List<Contact>();
        
            Contact ctc = new Contact();
            ctc.AccountId = linkToAccount.Id;
            ctc.LastName = nameRoot;
            Contact ctc2 = new Contact();
            ctc2.AccountId = linkToAccount.Id;
            ctc2.LastName = nameRoot + 'b';
            
            ctcList.add(ctc);
         	ctcList.add(ctc2);
 
        
        if (executeInsert)
            insert ctcList;
        
        return ctcList;
    }

    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method retireves the logMessage specified by the provided SFDC Id
    * @param        logId (Id): the SFDC Id of the Log message to be retrieved
    * @return       LOG_LogMessage__c: the Queried Log Message
    *********************************************************************************************************/ 
    public static LOG_LogMessage__c getInsertedLog(Id logId){
       LOG_LogMessage__c insertedMsg = [SELECT  CCPM_age__c,CCPM_debugLevel__c, Id, CCPM_logCode__c, CCPM_message__c, Name, CCPM_referenceId__c, CCPM_referenceInfo__c, CCPM_source__c, CCPM_sourceFunction__c, CCPM_stackTrace__c, CCPM_timer__c, CreatedDate, CCPM_integrationPayload__c   
                                        FROM LOG_LogMessage__c
                                        WHERE Id = :logId
                                       LIMIT 1];
        return insertedMsg;
    }
     
}