VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This individual has indicated they do not want to receive SMS communications from Verizon.</description>
        <inlineHelpText>This individual has indicated they do not want to receive SMS communications from Verizon.</inlineHelpText>
        <label>Do Not SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <encrypted>true</encrypted>
        <label>Account Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the individual&apos;s address, this is their geographically closest Verizon store.</description>
        <inlineHelpText>Nearest store to the account owner</inlineHelpText>
        <label>Nearest Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag  to indicate if store is active or not</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if employee is active for that store</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_StoreID__c</fullName>
        <formula>CCPM_Store__r.CCPM_storeID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_Store__c</fullName>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Store Employees</relationshipLabel>
        <relationshipName>Store_Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCPM_employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>CCPM Sales Rep,CCPM Retail Sales Rep,CCPM Retail Store Management,CCPM Retail District Management,CCPM Telesales Rep,CCPM Telesales Supervisor,CCPM Telesales Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Store Manager</fullName>
                </value>
                <value>
                    <fullName>Assistant Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSResponseBodyForProspect__c</fullName>
        <description>Holds the response which needs to go out if any response of received on initial or follow-up sms</description>
        <formula>&quot;I just received your text, if your text requires a response, I will get back to you shortly. Thanks.&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SMS Response Body for Prospects</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSResponseBody__c</fullName>
        <description>Holds the response which needs to go out if any response of received on initial or follow-up sms</description>
        <formula>&quot;I just received your text, if your text requires a response, I will get back to you shortly. Thanks.(FreeVzMsg)&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SMS Response Body</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <description>Account Number is the customer&apos;s account which could have multiple lines and multiple carts</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account number for this mobile number</inlineHelpText>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartlastHandledBy__c</fullName>
        <description>ID of the rep who last handled the cart</description>
        <label>Cart Last Handled By</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_followupMessageBody__c</fullName>
        <description>This formula field builds up the follow up message for a customer.</description>
        <formula>&quot;Hi, this is &quot;+ Owner:User.FirstName +&quot; from Verizon. I&apos;m just following up on my earlier message. If you are interested in visiting a store please let me know! (FreeVzMsg)&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Follow-Up Message Body</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_initialMessageBodyPartII__c</fullName>
        <description>2nd part of initial message body so that customer does not receive single message cut-off message</description>
        <formula>&apos;Would you like me to book an appt &apos;+Store__r.CCPM_recommendedVisitingHours__c+&apos; to visit my store? If not, what time/day works for you? Reply &quot;X&quot; to stop msgs (FreeVzMsg).&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initial Message Body Part II</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_initialMessageBodyPartI__c</fullName>
        <description>Body of the initial SMS which needs to sent to customer 4 hours after cart has been created</description>
        <formula>&quot;Hi, &quot;+Owner:User.FirstName + &quot; here from Verizon. Come visit us at the &quot;+Store__r.Name + &quot; store to chat about the great items saved in your cart (FreeVzMsg)&quot;</formula>
        <label>Initial Message Body Part I</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_isLeadOwnerActive__c</fullName>
        <formula>Owner:User.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Owner Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isManualLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if Prospect is Embedded Account</description>
        <inlineHelpText>if check Prospect is Embedded Account</inlineHelpText>
        <label>Manual Lead?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isSMSResponseReceived__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the individual responded to any of the Verizon communications?</description>
        <inlineHelpText>Has the individual responded to any of the Verizon communications?</inlineHelpText>
        <label>SMS Response Received?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_prospectSMSBodyPartII__c</fullName>
        <formula>&apos;Would you like to book an appt &apos; + Store__r.CCPM_recommendedVisitingHours__c + &apos;. What time/day works for you? Or visit us online: http://vzw.com Reply &quot;X&quot; to stop msgs. (FreeVzMsg)&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prospect 1st SMS Body Part II</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_prospectSMSBodyPartI__c</fullName>
        <description>SMS body part 1 of Prospect 1st SMS.</description>
        <formula>&quot;Hi, &quot;+Owner:User.FirstName + &quot; here from Verizon. Come visit us at the &quot;+Store__r.Name + &quot; store to chat about the items you inquired about (FreeVzMsg).&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prospect 1st SMS Body Part I</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_sendMessageUsingApexTest.cls
/**
*@name          CCPM_sendMessageUsingApexTest
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          08/22/2017
@description    Test class for CCPM_sendMessageUsingApex
@testClass      CCPM_sendMessageUsingApexTest
Modification    Log:
------------------------------------------------------------------------------------
Developer                               Date                        Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)       08/22/2017          Original Version
*/
@istest public class CCPM_sendMessageUsingApexTest 
{
    public static lead objLead;
    public static lead newLead;
    public static string StrMessageType;
    public static datetime dttScheduledate;
    public static list<string> lstAccountUniqueID=new list<string>();
    public static list<string> lstLastName=new list<string>();
    public static list<string> lstcartUniqueId=new list<string>();
    public static list<string> lststoreID=new list<string>();
    public static list<string> lstcartLastHandledBy=new list<string>();
    Public static list<id> lstLeadId= new list<id>();
    Public static list<Lead> lstLead=new list<Lead>();
    Public static list<CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex> lstVRA=new list<CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex>();
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to create Data required for the test class.
*/     
    Public static void CreateData()
    {
        //Create Custom setting
        CCPM_testDataFactory.createCustomSetting();
        CCPM_testDataFactory.createCustomer(1, 'abc');
        CCPM_testDataFactory.createStore(1);
        list<CCPM_Store__c > lststore=[select id,CCPM_storeID__c from CCPM_Store__c limit 1];
        if(lstStore!= null && lstStore.size()>0 && lstStore.isEmpty()==false){
            lststoreID.add(lstStore[0].CCPM_storeID__c);
        }
        list<Account > lstCustomer=[select CCPM_accountUniqueID__c from Account limit 1];
        if(lstCustomer!= null && lstCustomer.size()>0 &&lstCustomer.isEmpty()==false ){
            lstAccountUniqueID.add(lstCustomer[0].CCPM_accountUniqueID__c);
        }
        lstLastName.add('TestLastName');
        lstcartUniqueId.add('TestCartUniqueId');
        lstcartLastHandledBy.add('LHB'); 
        CCPM_testDataFactory.createCartdefaultRecordType(1, lstAccountUniqueID, lstLastName, lstcartUniqueId, lststoreID, lstcartLastHandledBy);
        lstLead=[Select Id,CCPM_mobileNumber__c,RecordTypeId,ownerid,Store__c,CCPM_followupMessageBody__c,CCPM_initialMessageBodyPartII__c,CCPM_initialMessageBodyPartI__c from lead limit 1];
        if(lstLead!= null && lstLead.size()>0 && lstLead.isEmpty()==false)
        {
            lstLeadId.add(lstLead[0].id);
        }
        CCPM_testDataFactory.createStoreEmployee('Man','RN', 'IDC','AM', lstStore[0].id);
        
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test Follow-Up SMS.
*/  
    
    Static testmethod void sendFollowUpSMSTest()
    {
        test.startTest();
        //Create Custom setting
        //CCPM_testDataFactory.createCustomSetting();
        CreateData();
        CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
        VRA.StrMessageType=CCPM_staticConstants.strMessageTypeFollowUpSMS;
        
        if(lstLead!= null && lstLead.size()>0 &&lstLead.isEmpty()==false ){
            VRA.Leads=lstLead[0];
            lstVRA.add(VRA);
            VRA.dttScheduledate=System.now();
       //     CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
        }  
        test.stopTest();
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test Initial SMS Part 1.
*/  
    
    Static testmethod void sendInitialSMS1Test()
    {
        test.startTest();
        CreateData();
        CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
        VRA.StrMessageType=CCPM_staticConstants.strMessageTypeInitialSMSPart1;
        
        if(lstLead!= null && lstLead.size()>0 && lstLead.isEmpty()==false){
            VRA.Leads=lstLead[0];
            VRA.dttScheduledate=System.now();
            lstVRA.add(VRA);
          //  CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
        }
        test.stopTest();
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test Initial SMS Part 2.
*/ 
    Static testmethod void sendInitialSMS2Test()
    {
        test.startTest();
        CreateData();
        CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
        VRA.StrMessageType=CCPM_staticConstants.strMessageTypeInitialSMSPart2;
        
        if(lstLead!= null && lstLead.size()>0 && lstLead.isEmpty()==false ){
            VRA.Leads=lstLead[0];
            VRA.dttScheduledate=System.now();
            lstVRA.add(VRA);
         //   CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
        }
        test.stopTest();
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test Initial SMS Part 2.
*/ 
    
   @istest Static void sendProcessCustomerResponseTest()
    {
        test.startTest();
        CCPM_testDataFactory.createCustomSetting();
       // User sysadminUser =CCPM_testDataFactory.CreateUser('System Administrator','sysadmin');
        CCPM_testDataFactory.createCustomer(1, 'abc');
        CCPM_testDataFactory.createStore(1);
        list<CCPM_Store__c > lststore=[select id,CCPM_storeID__c from CCPM_Store__c limit 1];
        if(lstStore!= null && lstStore.size()>0 &&lstStore.isEmpty()==false ){
            lststoreID.add(lstStore[0].CCPM_storeID__c);
        }
        CCPM_testDataFactory.createStoreEmployee('Man','RN', 'IDC','AM', lstStore[0].id);
        list<CCPM_StoreEmployee__c> lstStoreEmployee = [select id,CCPM_employee__c,CCPM_IsActive__c from CCPM_storeEmployee__c where CCPM_role__c ='Store Manager' ];
        list<Account > lstCustomer=[select CCPM_accountUniqueID__c from Account limit 1];
        if(lstCustomer!= null && lstCustomer.size()>0 && lstCustomer.isEmpty()==false){
            lstAccountUniqueID.add(lstCustomer[0].CCPM_accountUniqueID__c);
        }
        lstLastName.add('TestLastName');
        lstcartUniqueId.add('TestCartUniqueId');
        lstcartLastHandledBy.add('LHB'); 
        Lead objCart=new Lead();
        objCart.LastName=lstLastName[0];
        objCart.Status='New';
        objCart.Company='1';           
        // objCart.CCPM_accountNumber__c = lstAccountUniqueID[0];
        objCart.CCPM_accountUniqueID__c = lstCustomer[0].CCPM_accountUniqueID__c;
        objCart.CCPM_storeID__c = lststoreID[0];
        // objCart.CCPM_cartlastHandledBy__c = cartLastHandledBy[i];
        objCart.CCPM_mobileNumber__c = '3213187287';
        objCart.CCPM_SMSLegalOptIn__c = ccpm_staticConstants.boolSMSSent;
        objCart.CCPM_LeadType__c = 'Customer Abandoned Cart Digital';
        if(objcart!=null )
            insert objCart;
        // CCPM_testDataFactory.createCart(1, lstAccountUniqueID, lstLastName, lstcartUniqueId, lststoreID, lstcartLastHandledBy);
        lstLead=[Select Id,CCPM_isLeadOwnerActive__c,CCPM_isManualLead__c,RecordTypeId,CCPM_isSMSResponseReceived__c,CCPM_mobileNumber__c,ownerid,Store__c,CCPM_SMSResponseBodyForProspect__c,CCPM_followupMessageBody__c,CCPM_initialMessageBodyPartII__c,CCPM_initialMessageBodyPartI__c,CCPM_SMSOptOut__c from lead limit 1];
        if(lstLead!= null && lstLead.size()>0 &&lstLead.isEmpty()==false )
        {
            
                lstLead[0].ownerId=lstStoreEmployee[0].CCPM_employee__c;
                update lstLead;
            
            lstLeadId.add(lstLead[0].id);
        }
       // CCPM_testDataFactory.createStoreEmployee('Man','RN', 'IDC','AM', lstStore[0].id);
        
        lstLead=[select id,RecordTypeId,CCPM_isLeadOwnerActive__c,store__c,CCPM_isManualLead__c,CCPM_isSMSResponseReceived__c,CCPM_SMSResponseBody__c,CCPM_SMSResponseBodyForProspect__c,OwnerId,LastName,CCPM_SMSOptOut__c from lead limit 1];
        
        //list<LiveText__LiveText_Number__c> LiveTextNumber= [select id from LiveText__LiveText_Number__c limit 1];
        /*
         createITRRecords();
        
        list<LiveText__ITR_Message__c> lstITR=[select id,LiveText__Originating_Number__c,LiveText__Message__c,LiveText__Lead__c from LiveText__ITR_Message__c limit 1];
        CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
        VRA.StrMessageType=CCPM_staticConstants.strMessageTypeProcessCustomerResponse;
        lstLead[0].store__c =lstStore[0].id;
        update lstLead;
        if(lstLead!= null && lstLead.size()>0 && lstLead.isEmpty()==false){
            VRA.Leads=lstLead[0];
            VRA.ITRRecord=lstITR[0];
            lstVRA.add(VRA);
            CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
        }
        list<task> lstTasks=[select id,whoid,status,subject from task where subject like'SMS for Review%' limit 1];
        CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA1 = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
        CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA2 = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
        list<CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex> lstVRA1=new list<CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex>();
        if(lstTasks!=null && lstTasks.size()>0 &&lstTasks.isEmpty()==false )
        {   
            System.assert(lstTasks[0].status==CCPM_staticConstants.strTaskNotStarted);
            VRA1.Tasks=lstTasks[0];
            VRA1.StrMessageType=CCPM_staticConstants.strMessageTypeTaskOwnerSMS;
            lstVRA1.add(VRA1);
            CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA1);
        }
        ccpm_sendMessageUsingApex.CustomerResponseForDoubleOptOut(lstITR[0],lstLead[0]);
        lstITR[0].LiveText__Message__c =CCPM_staticConstants.strFirstCustomerResponseForOptOutQuote;
        Update lstITR[0];
        VRA.Leads=lstLead[0];
        VRA.ITRRecord=lstITR[0];
        lstVRA.add(VRA);
        ccpm_sendMessageUsingApex.CustomerResponseForDoubleOptOut(lstITR[0],lstLead[0]);
        CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
        
        
        lstLead[0].RecordTypeId = ccpm_staticConstants.strLeadCustomerAbandonedCartRecordTypeID;
        VRA2.Leads=lstLead[0];
        VRA2.ITRRecord=lstITR[0];
        lstVRA.add(VRA2);
        CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
        */
        test.stopTest();
    }  
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test Prospect Action Required SMS.
*/ 
    
    @istest Static void ProspectActionRequiredSMS()
    {
        test.startTest();
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        System.runAs(u)
        {
            
            CreateData();
            createITRRecords();
            list<LiveText__ITR_Message__c> lstITR=[select id,LiveText__Originating_Number__c,LiveText__Message__c,LiveText__Lead__c from LiveText__ITR_Message__c limit 1];
            CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
            VRA.StrMessageType=CCPM_staticConstants.strMessageTypeProspectActionRequired;
            if(lstLead!= null && lstLead.size()>0 && lstLead.isEmpty()==false){
                VRA.Leads=lstLead[0];
                
                lstVRA.add(VRA);
             //   CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
            }
            
            
        }
        test.stopTest();
        
    } 
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test Prospect Action Required SMS.
*/ 
    
    @istest Static void newProspectSMS()
    {
        test.startTest();
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        System.runAs(u)
        {
            
            CreateData();
            lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
            createITRRecords();
            
            CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA1 = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
            VRA1.StrMessageType=CCPM_staticConstants.strMessageTypeProspectFirstSMSPart1;
            if(lstLead!= null && lstLead.size()>0){
                VRA1.Leads=lstLead[0];
                VRA1.dttScheduledate=system.now();
                
                lstVRA.add(VRA1);
            }
            
            CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
            VRA.StrMessageType=CCPM_staticConstants.strMessageTypeProspectFirstSMSPart2;
            if(lstLead!= null && lstLead.size()>0 && lstLead.isEmpty()==false){
                VRA.Leads=lstLead[0];
                VRA.dttScheduledate=system.now();
                lstVRA.add(VRA);
              //  CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
            }
            
            
        }
        test.stopTest();
        
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test SMS to task owners.
*/  
    
    Static testmethod void createTasksToSendSMSTest()
    {	
        test.startTest();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        list<task> lstTask = new list<Task>();
        CreateData();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        CCPM_testDataFactory.createTask(lstLead[0].id,'outbound');
        lstTask = [select id,whoid,Status,ownerid from task limit 1];
        lstStoreEmployee = [select id,CCPM_employee__c from CCPM_storeEmployee__c where CCPM_role__c='Sales Rep'];
        lstTask[0].ownerid= lstStoreEmployee[0].CCPM_employee__c;
        update lstTask;
        CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex VRA = new CCPM_sendMessageUsingApex.setVariablesRequiredtoSendSMSforApex();
        VRA.StrMessageType=CCPM_staticConstants.strMessageTypeTaskOwnerSMS;
        
        if(lstTask!= null && lstTask.size()>0){
            VRA.tasks=lstTask[0];
            lstVRA.add(VRA);
            //VRA.dttScheduledate=System.now();
        //    CCPM_sendMessageUsingApex.SendMessageViaApex(lstVRA);
        }  
        test.stopTest();
    }    
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test method send SMS to managers
*/  
    
    Static testmethod void createTasksToSendSMSManagersTest()
    {	
        test.startTest();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        CreateData();
        createITRRecords();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        
        list<LiveText__ITR_Message__c> lstITR=[select id,LiveText__Originating_Number__c,LiveText__Message__c,LiveText__Lead__c from LiveText__ITR_Message__c limit 1];
        lstStoreEmployee = [select id,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstStoreEmployee.clear();
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstLead[0].ownerid = lstStoreEmployee[0].CCPM_employee__c;
        map<id,User> mapOwnerFirstname = new map<id,User>([select id,firstname,lastname from user where id = :lstStoreEmployee[0].CCPM_employee__c limit 1]);
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        
        System.runAs(u)
        {
            mapOwnerFirstname.get(lstStoreEmployee[0].CCPM_employee__c).firstname=null;
            update mapOwnerFirstname.values();
        }
     //   CCPM_sendMessageUsingApex.SendSMSToManagers(lstITR[0],lstLead[0],lstStoreEmployee[0],mapOwnerFirstname,System.now());
        
        //CCPM_sendMessageUsingApex.SendSMSToManagers(lstITR[0],lstLead[0],lstStoreEmployee[0],null,System.now());
        test.stopTest();
    }
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test method send SMS to managers
*/  
    
    Static testmethod void createTasksToSendSMSManagersTest2()
    {	
        test.startTest();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        CreateData();
        createITRRecords();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        
        list<LiveText__ITR_Message__c> lstITR=[select id,LiveText__Originating_Number__c,LiveText__Message__c,LiveText__Lead__c from LiveText__ITR_Message__c limit 1];
        lstStoreEmployee = [select id,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstStoreEmployee.clear();
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstLead[0].ownerid = lstStoreEmployee[0].CCPM_employee__c;
        
        
     //   CCPM_sendMessageUsingApex.SendSMSToManagers(lstITR[0],lstLead[0],lstStoreEmployee[0],null,System.now());
        test.stopTest();
    }    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test all the returning null functionality
*/  
    
    Static testmethod void ReturnNullTest1()
    {	
        test.startTest();
        CreateData();
        createITRRecords();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstLead[0].ownerid = lstStoreEmployee[0].CCPM_employee__c;
        //update lstLead;
        list<User> lstUser = [select id,firstname,lastname from user where id = :lstStoreEmployee[0].CCPM_employee__c limit 1];
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        
        System.runAs(u)
        {
            lstUser[0].isactive=false;
            lstUser[0].mobilephone=null;
            update lstUser;
        }
        
     //   CCPM_sendMessageUsingApex.createToDoTaskforCustomerResponse(lstLead[0],null);
        
        test.stopTest();
    }
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test all the returning null functionality
*/  
    
    Static testmethod void ReturnNullTest2()
    {	
        test.startTest();
        CreateData();
        createITRRecords();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstLead[0].ownerid = lstStoreEmployee[0].CCPM_employee__c;
        lstLead[0].CCPM_mobileNumber__c=null;
        //update lstLead;
        list<User> lstUser = [select id,firstname,lastname from user where id = :lstStoreEmployee[0].CCPM_employee__c limit 1];
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        
        System.runAs(u)
        {
            lstUser[0].isactive=false;
            lstUser[0].mobilephone=null;
            update lstUser;
        }
        
      //  CCPM_sendMessageUsingApex.InitialSMS(lstLead[0],null,null);
        
        test.stopTest();
    } 
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test all the returning null functionality
*/  
    
    Static testmethod void ReturnNullTest3()
    {	
        test.startTest();
        CreateData();
        createITRRecords();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstLead[0].ownerid = lstStoreEmployee[0].CCPM_employee__c;
        lstLead[0].CCPM_mobileNumber__c=null;
        //update lstLead;
        list<User> lstUser = [select id,firstname,lastname from user where id = :lstStoreEmployee[0].CCPM_employee__c limit 1];
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        
        System.runAs(u)
        {
            lstUser[0].isactive=false;
            lstUser[0].mobilephone=null;
            update lstUser;
        }
       // CCPM_sendMessageUsingApex.FollowUpSMS(lstLead[0],null);
        test.stopTest();
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test all the returning null functionality
*/  
    
    Static testmethod void ReturnNullTest4()
    {	
        test.startTest();
        CreateData();
        createITRRecords();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstLead[0].ownerid = lstStoreEmployee[0].CCPM_employee__c;
        lstLead[0].CCPM_mobileNumber__c=null;
        //update lstLead;
        list<User> lstUser = [select id,firstname,lastname from user where id = :lstStoreEmployee[0].CCPM_employee__c limit 1];
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        
        System.runAs(u)
        {
            lstUser[0].isactive=false;
            lstUser[0].mobilephone=null;
            update lstUser;
        }
      //  CCPM_sendMessageUsingApex.newProspectSMS(lstLead[0],null,null);
        test.stopTest();
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test all the returning null functionality
*/  
    
    Static testmethod void ReturnNullTest5()
    {	
        test.startTest();
        CreateData();
        createITRRecords();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstLead[0].ownerid = lstStoreEmployee[0].CCPM_employee__c;
        lstLead[0].CCPM_mobileNumber__c=null;
        //update lstLead;
        list<User> lstUser = [select id,firstname,lastname from user where id = :lstStoreEmployee[0].CCPM_employee__c limit 1];
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        
        System.runAs(u)
        {
            lstUser[0].isactive=false;
            lstUser[0].mobilephone=null;
            update lstUser;
        }
        lstStoreEmployee.clear();
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
     //   CCPM_sendMessageUsingApex.sendLeadOrProspectActionRequiredSMS(null,null,lstStoreEmployee[0],null);
        test.stopTest();
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test all the returning null functionality
*/  
    
    Static testmethod void ReturnNullTest6()
    {	
        test.startTest();
        CreateData();
        createITRRecords();
        list<CCPM_StoreEmployee__c> lstStoreEmployee = new list<CCPM_StoreEmployee__c>();
        lstLead.clear();
        lstLead=[select id,CCPM_prospectSMSBodyPartII__c,CCPM_prospectSMSBodyPartI__c,CCPM_mobileNumber__c,store__c,CCPM_SMSResponseBody__c,OwnerId,LastName from lead limit 1];
        lstStoreEmployee = [select id,CCPM_storeEmployee__c.CCPM_role__c,CCPM_employee__r.firstname,CCPM_employee__r.lastname,CCPM_employee__r.MobilePhone from CCPM_storeEmployee__c where CCPM_role__c = :CCPM_staticConstants.strStoreAssistantManager];
        lstLead[0].ownerid = lstStoreEmployee[0].CCPM_employee__c;
        lstLead[0].CCPM_mobileNumber__c=null;
        lstLead[0].CCPM_LeadType__c = 'Customer Abandoned Cart Digital';
        update lstLead;
        list<User> lstUser = [select id,firstname,lastname from user where id = :lstStoreEmployee[0].CCPM_employee__c limit 1];
        User u=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'IU');
        
        System.runAs(u)
        {
            lstUser[0].isactive=false;
            lstUser[0].mobilephone=null;
            update lstUser;
        }
        list<LiveText__ITR_Message__c> lstITR=[select id,LiveText__Originating_Number__c,LiveText__Message__c,LiveText__Lead__c from LiveText__ITR_Message__c limit 1];
      //  CCPM_sendMessageUsingApex.CustomerResponseForDoubleOptOut(lstITR[0],lstLead[0]);
        test.stopTest();
    }
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to create ITR records for testing purpose
*/  
    public static void createITRRecords()
    {
        
        LiveText__LiveText_Number__c LiveTextNumber1=new LiveText__LiveText_Number__c();
        LiveTextNumber1.Name='test';
        LiveTextNumber1.LiveText__Validated__c=ccpm_staticConstants.boolSMSSent;
        LiveTextNumber1.LiveText__Number__c='13214249106';
        if(LiveTextNumber1!=null)
            insert LiveTextNumber1;
        
        LiveText__ITR_Message__c ITR=new LiveText__ITR_Message__c();
        ITR.LiveText__LiveText_Number__c=LiveTextNumber1.Id;
        ITR.Name='Test';
        ITR.LiveText__Originating_Number__c='+13213187287';
        ITR.LiveText__Message__c='Okay';
        ITR.LiveText__Lead__c=lstLead[0].id;
        insert ITR;
    }        
}