VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the individual&apos;s address, this is their geographically closest Verizon store.</description>
        <inlineHelpText>Nearest store to the account owner</inlineHelpText>
        <label>Nearest Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_ESNCodes__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>ESN Codes</label>
    <nameField>
        <label>ESN Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ESN Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_journey__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Journey</relationshipLabel>
        <relationshipName>Journey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <label>MTN</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Journey</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag  to indicate if store is active or not</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Existing customer for whom abandoned cart has been created</description>
        <label>Account Holder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartTypeProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cart Type Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_closedLeadSource__c</fullName>
        <description>The system from which the lead has closed</description>
        <inlineHelpText>This represents the close source system of the lead or prospect</inlineHelpText>
        <label>Closed Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ATG-ECOM-DESK</fullName>
                </value>
                <value>
                    <fullName>ATG-ECOM-GGDESK</fullName>
                </value>
                <value>
                    <fullName>ATG-ECOM-GGMOB</fullName>
                </value>
                <value>
                    <fullName>ATG-ECOM-GGTAB</fullName>
                </value>
                <value>
                    <fullName>ATG-ECOM-MAPP</fullName>
                </value>
                <value>
                    <fullName>ATG-ECOM-MDOT</fullName>
                </value>
                <value>
                    <fullName>ATG-ECOM-MIPP</fullName>
                </value>
                <value>
                    <fullName>ATG-ECOM-TDOT</fullName>
                </value>
                <value>
                    <fullName>NETACE</fullName>
                </value>
                <value>
                    <fullName>ONEPOS</fullName>
                </value>
                <value>
                    <fullName>ACSS</fullName>
                </value>
                <value>
                    <fullName>EROES</fullName>
                </value>
                <value>
                    <fullName>NR-APPL</fullName>
                </value>
                <value>
                    <fullName>NR-BEST</fullName>
                </value>
                <value>
                    <fullName>NR-TARG</fullName>
                </value>
                <value>
                    <fullName>NR-BBDT</fullName>
                </value>
                <value>
                    <fullName>MFRAPP</fullName>
                </value>
                <value>
                    <fullName>DOTCOM</fullName>
                </value>
                <value>
                    <fullName>NR-APDT</fullName>
                </value>
                <value>
                    <fullName>QUOTE-TELESALES</fullName>
                </value>
                <value>
                    <fullName>QUOTE-RETAIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_convertedCartType__c</fullName>
        <label>Converted Cart Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_lastInteraction__c</fullName>
        <description>Date/Time being recorded for last interaction between the customer and Heywire process in salesforce</description>
        <label>Last Interaction Date/TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_sendLeadsRequiringActionSMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to trigger the SMS to Store Managers and Assistant Managers to Trigger SMS for Leads or Prospects Requiring Action</description>
        <label>Send Leads Requiring Action SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_journeyTriggerHandlerTest.cls
/**
*@name          CCPM_journeyTriggerHandlerTest
*@author        Aneesha Ragireddy (Deloitte)
*@date          04/17/2018
@description    This is a test class for CCPM_journeyHandler
@testClass:     CCPM_journeyTriggerHandlerTest
Modification    Log:
---------------------------------------------------------------------------------------
Developer                              Date                                Description
---------------------------------------------------------------------------------------
Aneesha Ragireddy(Deloitte)     	 04/17/2018                          Original Version
*/
@isTest
public class CCPM_journeyTriggerHandlerTest {
    @isTest
    public static void beforeUpdateTest(){
        //List<Account> lstAcc = CCPM_testDataFactory.createCustomer(1, 'abc');
        CCPM_journey__c objNewJourney = new CCPM_journey__c();
        objNewJourney.CCPM_mobileNumber__c = '1234567890';
        //objNewJourney.CCPM_account__c = lstAcc[0].id;
        insert objNewJourney;
        CCPM_journeyTriggerHandler objJourney = new CCPM_journeyTriggerHandler();
        objJourney.IsDisabled();
        objJourney.BeforeUpdate(null, null);
        objJourney.BeforeDelete(null);
        objJourney.AfterInsert(null);
        objJourney.AfterDelete(null);
        objJourney.AfterUpdate(null, null);
        objJourney.AfterUndelete(null);
    }
     /**
*@author        Aneesha Ragireddy (Deloitte)
*@description   This method is targeted to test the Batch Class for processConvertedCartTypes
*@param :       None
*/
    @istest(SeeAllData=False) public static void testLeadCreation()
    {   
        List<lead> lstLead = new List<lead>();
        Lead l1 = new Lead();
        
        test.startTest();
        CCPM_testDataFactory.createCustomSetting();
        
        Id customerCartRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Customer Cart').getRecordTypeId();
        list<CCPM_Store__c> lstObjStore = CCPM_testDataFactory.createStore(CCPM_staticConstants.NoOfRecords);
        CCPM_testDataFactory.createCustomer(1, 'abc');
        
        l1.LastName = 'ABCActionRequiredOne';
        l1.FirstName = 'TestingOne';
        l1.Status = 'Converted';
        l1.CCPM_SMSLegalOptIn__c = true;
        l1.CCPM_convertedCartType__c = 'AAL,AAL,NEW,EUP-A1,Gibberish';
        l1.CCPM_accountUniqueID__c = 'abc0';
        l1.CCPM_cartTypeProcessed__c = false;
        l1.CCPM_lastInteraction__c = system.now().addHours(-800);
        l1.CCPM_mobileNumber__c = '9999999999';
        l1.Company = '1';
        l1.CCPM_closedLeadSource__c = 'ATG-ECOM-TDOT';
        l1.CCPM_sendLeadsRequiringActionSMS__c = false;
        l1.CCPM_storeID__c = lstObjStore[0].CCPM_storeid__c;
        l1.CCPM_LeadType__c = 'Customer Abandoned Cart Digital';
        
        lstLead.add(l1);
        insert lstLead;
        CCPM_ESNCodes__c ESN = new CCPM_ESNCodes__c();
        ESN.CCPM_isActive__c=true;
        ESN.Name='A1';
        insert ESN;
         Profile p = [SELECT Id FROM Profile WHERE Name='CCPM Sales Rep'];
        User u = new User(Alias = 'manager', Email='standardtestuser2UAT@testorgUAT.com',firstname='a', 
                          EmailEncodingKey='UTF-8', LastName='manager', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, isActive = true,
                          TimeZoneSidKey='America/Los_Angeles', UserName='manager'+'UAT@testorgUAT.com',mobilephone='3214249106');
        insert u;
        CCPM_testDataFactory.createStoreRep(u,lstObjStore[0]);
        System.debug('userid->'+u.id);
        lstLead[0].ownerid=u.id;
        update lstLead[0];
        System.debug('lstLead[0]->'+lstLead[0].ownerid);
        CCPM_processCommissionableCartType ProcessCommisionableBatch = new CCPM_processCommissionableCartType();
        
        
        Database.executeBatch(ProcessCommisionableBatch,200);
        test.stopTest();


}
}