VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This individual has indicated they do not want to receive SMS communications from Verizon.</description>
        <inlineHelpText>This individual has indicated they do not want to receive SMS communications from Verizon.</inlineHelpText>
        <label>Do Not SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the individual&apos;s address, this is their geographically closest Verizon store.</description>
        <inlineHelpText>Nearest store to the account owner</inlineHelpText>
        <label>Nearest Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_globalSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Settings for verizon lead &amp; prospect management</description>
    <fields>
        <fullName>CCPM_followUpSMSInterval__c</fullName>
        <inlineHelpText>Interval in minutes from date/time lead is created to send the follow-up SMS</inlineHelpText>
        <label>Follow Up SMS Interval (In Min)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_initialSMSInterval__c</fullName>
        <inlineHelpText>Interval in minutes to send the initial sms from date/time lead (cart) was created in salesforce</inlineHelpText>
        <label>Initial SMS Interval (In Min)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_StoreID__c</fullName>
        <formula>CCPM_Store__r.CCPM_storeID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_Store__c</fullName>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Store Employees</relationshipLabel>
        <relationshipName>Store_Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCPM_employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>CCPM Sales Rep,CCPM Retail Sales Rep,CCPM Retail Store Management,CCPM Retail District Management,CCPM Telesales Rep,CCPM Telesales Supervisor,CCPM Telesales Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CCPM_commissionableRepID__c</fullName>
        <description>ID of reps which will be populated in REPID column in cart. This field is mapped to &quot;Cart Handled By&quot; in lead object</description>
        <label>Commissionable Rep ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_SMSInteractionHistoryControllerTest.cls
/**
*@name          CCPM_SMSInteractionHistoryControllerTest
*@author        Paras Shah (Deloitte)
*@date          02/06/2016
@description    To Test the class CCPM_SMSInteractionHistoryController


@testClass:     CCPM_SMSInteractionHistoryControllerTest
Modification    Log:
------------------------------------------------------------------------------------
Developer               Date                                Description
------------------------------------------------------------------------------------
Paras Shah(Deloitte)    02/06/2016                          Original Version
*/

@istest(SeeAllData=False)
public class CCPM_SMSInteractionHistoryControllerTest {    
    /**
*@author        Paras Shah (Deloitte)
*@description   This method is targeted to test the CCPM_SMSInteractionHistoryController class
*@param :       None
*/
    @istest(SeeAllData=False) public static void testLeadCreation()
    {   
        test.startTest();
        CCPM_testDataFactory.createCustomSetting();
        User integrationUser=CCPM_testDataFactory.CreateUser('CCPM Integration User','integrationUser');
        //User objStoreEmployeeWithoutStore = CCPM_testDataFactory.CreateUser('CCPM Sales Rep');
        System.runAs(integrationUser){ 
            //Creating Store,Customer and Cart test data and it also triggers the before Insert Condition on CCPM_leadHandler
            list<CCPM_Store__c> lstObjStore = CCPM_testDataFactory.createStore(CCPM_staticConstants.NoOfRecords);
            //Parameters to createStoreEmployee -> (String managerName, String repName, String CommisionableRepID, String assistantManager, ID StoreID)
            //Returns a list of store employees.
            List<String> accountUniqueID = new List<String>();
            List<String> storeID = new List<String>();
            for(CCPM_Store__c store: lstObjStore){
                String managerName = 'M'+store.Name;
                String repName = 'S'+store.Name; 
                String CommisionableRepID = 'repID' + repName; 
                String assistantManager = 'A'+store.Name;
                CCPM_testDataFactory.createStoreEmployee(managerName,repName,CommisionableRepID,assistantManager,store.Id);
            }
            //Create Customer and assign one nearest store per customer.(Number of customers and stores are same for now)
            list<Account> lstCustomer=CCPM_testDataFactory.createCustomer(CCPM_staticConstants.NoOfRecords,'A1');
            try{
                system.debug('disp#1lstcustomer'+lstCustomer);
                list<CCPM_Store__c> stores=[Select id,CCPM_storeID__c from CCPM_store__c limit :(lstCustomer.size())];
                for(integer i=0;i<(lstCustomer.size());i++)
                {
                    if(stores.size()>0 && stores!=null){
                        lstCustomer[i].CCPM_Store__c=stores[i].id;
                        lstCustomer[i].CCPM_storeID__c=stores[i].CCPM_storeID__c;
                        accountUniqueID.add(lstCustomer[i].CCPM_accountUniqueID__c);
                        storeID.add(stores[i].CCPM_storeID__c);
                    }
                }
            }
            Catch(DMLException e)
            {
                CCPM_LogMessageUtility.logMessage(e,'CCPM_leadTest','testLeadCreation','Exception thrown while querying for store records',true);
            }
            //Individual Customer without a nearest store
            List<Account> lstCustomerWithoutNearestStore = CCPM_testDataFactory.createCustomer(1,'B');
            //Create Carts and assert test
            try{
        system.debug('disp#2'+lstCustomerWithoutNearestStore);
                //CreateCarts
                //Parameters to create a Cart -> (String accountUniqueID, String LastName, String cartUniqueId, String storeID, string cartLastHandledBy)
                List<String> cartUniqueId = new List<String>();
                List<String> cartLastName = new List<String>(); 
                List<CCPM_storeEmployee__c> storeEmployee = [Select id, CCPM_employee__r.CCPM_commissionableRepID__c from CCPM_storeEmployee__c where CCPM_employee__r.CCPM_commissionableRepID__c!=null limit :CCPM_staticConstants.NoOfRecords];
                List<String> cartLastHandledBy = new List<String>();
                for(integer i=0;i<(CCPM_staticConstants.NoOfRecords /2);i++){
                    string strCartLastName = 'Cart'+i;
                    string strCartUniqueId = 'cartUniqueId'+strCartLastName;
                    cartLastName.add(strCartLastName);
                    cartUniqueId.add(strCartUniqueId);
                    cartLastHandledBy.add('asd');
                }
                for(integer i=(CCPM_staticConstants.NoOfRecords /2);i<CCPM_staticConstants.NoOfRecords;i++){
                    string strCartLastName = 'Cart'+i;
                    string strCartUniqueId = 'cartUniqueId'+strCartLastName;
                    cartLastName.add(strCartLastName);
                    cartUniqueId.add(strCartUniqueId);
                    cartLastHandledBy.add(''+i);
                }
                system.debug('disp#3'+cartLastName);
                system.debug('disp#4'+cartUniqueId);
                
                //insert new CCPM_globalSetting__c(CCPM_initialSMSInterval__c = '180',CCPM_followUpSMSInterval__c = '3600'); 
                
                List<lead> lstCarts = CCPM_testDataFactory.createCart(CCPM_staticConstants.NoOfRecords,accountUniqueID,cartLastName,cartUniqueId, storeID, cartLastHandledBy);
                
                list<Lead> lstLeadCart =[select id,store__c,CCPM_SMSOptOut__c from lead];
                upsert lstLeadCart;
                
                system.debug('disp#5'+lstCarts);
                
                CCPM_testDataFactory.createTask(lstLeadCart[0].id,'Inbound');
                CCPM_testDataFactory.createTask(lstLeadCart[0].id,'Outbound');
                
                //Method calls with valid Id
                String strLeadPhone = CCPM_SMSInteractionHistoryController.getLeadPhone(lstLeadCart[0].id);
                CCPM_SMSInteractionHistoryController.getSMSMessageList(lstLeadCart[0].id);
                
                List<lead> lstQueryleadPhone = [select CCPM_mobileNumber__c from Lead where id = :lstLeadCart[0].id limit 1];
                system.assertEquals(strLeadPhone,lstQueryleadPhone[0].CCPM_mobileNumber__c);
                
                //Method calls with null id
                String strLeadPhoneNull = CCPM_SMSInteractionHistoryController.getLeadPhone(null);
                CCPM_SMSInteractionHistoryController.getSMSMessageList(null); 
                
                system.assertEquals(strLeadPhoneNull,null );
            }
            Catch(DMLException e)
            {
                System.debug('Exception occured while updating lead Cart/Class:CCPM_leadTest ' + e.getMessage());
            }
            
            
        }
        test.stopTest();
    }
}