VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This individual has indicated they do not want to receive SMS communications from Verizon.</description>
        <inlineHelpText>This individual has indicated they do not want to receive SMS communications from Verizon.</inlineHelpText>
        <label>Do Not SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <encrypted>true</encrypted>
        <label>Account Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <encrypted>true</encrypted>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the individual&apos;s address, this is their geographically closest Verizon store.</description>
        <inlineHelpText>Nearest store to the account owner</inlineHelpText>
        <label>Nearest Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaignJourneyMessage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SMS Journey Message Lookup</description>
        <inlineHelpText>SMS Journey Message Lookup</inlineHelpText>
        <label>Campaign Journey Message</label>
        <referenceTo>CCPM_journeyMessage__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

VZDEV/src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>CCPM_cartUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Cart Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

VZDEV/src/objects/CCPM_DynamicCampaignSMS__mdt.object
<CustomObject>
    <description>Contains Dynamic values to be encoded into the SMS for Campaigns</description>
    <fields>
        <fullName>CCPM_CampaignName__c</fullName>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_campaignSMSDate__c</fullName>
        <description>This field stores the date value to be populated in the SMS</description>
        <label>Campaign SMS Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_dynamicURL__c</fullName>
        <description>Stores the Dynamic URL values for a campaign</description>
        <label>Dynamic URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dynamic Values for Campaign SMS</label>
    <pluralLabel>Dynamic Values for Campaign SMS</pluralLabel>
</CustomObject>

VZDEV/src/objects/CCPM_journeyMessage__c.object
<CustomObject>
    <description>Object for Campaigns</description>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_messageFollowUpSMS__c</fullName>
        <label>MessageFollowupSMS</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_messageInitialSMS__c</fullName>
        <label>MessageInitialSMS</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Journey Message</label>
    <nameField>
        <displayFormat>JM-{000000}</displayFormat>
        <label>Journey Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag  to indicate if store is active or not</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <description>Account Number is the customer&apos;s account which could have multiple lines and multiple carts</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account number for this mobile number</inlineHelpText>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartID__c</fullName>
        <description>Unique reference id of the cart</description>
        <externalId>true</externalId>
        <label>Cart ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique Identified to create/update carts(leads). The format will be &apos;A:&apos;+Account Number&apos; +&apos;-M:&apos; + Mobile Number + &apos;-S:&apos; + Lead Status. This field will be used to upset leads in Salesforce for carts (leads) for existing customers.</description>
        <externalId>true</externalId>
        <label>Cart Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <description>Email address specified by the customer when creating the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Email of the lead / prospect. Required to save a Prospect if the MTN is unavailable.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_isInitialSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</description>
        <inlineHelpText>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Initial SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_CampaignMemberHandlerTest.cls
/**
*@name          CCPM_CampaignMemberTest
*@author        Sriraman Sridharan (Deloitte)
*@date          09/21/2017
@description    The Test Class is meant to unit test the Campaign Member trigger and its handler class
Modification    Log:
------------------------------------------------------------------------------------
Developer                               Date                   Description
------------------------------------------------------------------------------------
Sriraman Sridharan(Deloitte)          09/27/2017              Original Version
*/
@isTest
public class CCPM_CampaignMemberHandlerTest {

    /**
@author        Sriraman Sridharan(Deloitte)
@description   This method is targeted to create Data required for the test class.
*/     
    public static List<lead> createCart(Integer NoOfRecords, List<Account> accountUniqueID,string strmobilenumber, string unique)
    {   
        //To create test user and assign as OwnerId
        List<lead> lstObjCart = new List<lead>();
        for(integer i=0;i<NoOfRecords;i++){
            Lead objCart=new Lead();
            objCart.LastName= 'LeadCampaign';
            objCart.FirstName='Count';
            objCart.Status='New';
            objCart.Company = '1';           
            objCart.CCPM_accountUniqueID__c = accountUniqueID[i].CCPM_accountUniqueID__c;
            objCart.CCPM_mobileNumber__c = '3213187287';
            datetime date1=Datetime.now();
            objCart.CCPM_cartUniqueID__c = accountUniqueID[i].CCPM_accountUniqueID__c + i + unique;
            objCart.CCPM_cartID__c = accountUniqueID[i].CCPM_accountUniqueID__c + i + unique;
            objCart.RecordTypeId = CCPM_staticConstants.strLeadCustomerAbandonedCartRecordTypeID;
            objCart.LeadSource = 'CRM';
            objCart.CCPM_LeadType__c = 'Customer Campaign';
            lstObjCart.add(objCart);
        }
        
        try{
            if(lstObjCart!= null){
                System.debug('@@@@ lstObjCart : ' + lstObjCart);
                insert lstObjCart;
            }
            return lstObjCart;
        }
        Catch(DmlException e)
        {
            System.debug('The following exception has occurred while creating cart/ClassName:CCPM_CampaignMemberHandlerTest: ' + e.getMessage());
            return null;
        }
    }
public static List<lead> createClosedCart(Integer NoOfRecords, List<Account> accountUniqueID,string strmobilenumber, string unique)
    {   
        //To create test user and assign as OwnerId
        List<lead> lstObjCart = new List<lead>();
        for(integer i=0;i<NoOfRecords;i++){
            Lead objCart=new Lead();
            objCart.LastName= 'LeadCampaign';
            objCart.FirstName='Count';
            objCart.Status='Expired';
            objCart.Company = '1';           
            objCart.CCPM_accountUniqueID__c = accountUniqueID[i].CCPM_accountUniqueID__c;
            objCart.CCPM_mobileNumber__c = '3213187287';
            datetime date1=Datetime.now();
            objCart.CCPM_cartUniqueID__c = accountUniqueID[i].CCPM_accountUniqueID__c + i +unique;
            objCart.CCPM_cartID__c = accountUniqueID[i].CCPM_accountUniqueID__c + i +unique;
            objCart.RecordTypeId = CCPM_staticConstants.strLeadCustomerAbandonedCartRecordTypeID;
            objCart.LeadSource = 'CRM';
            objCart.CCPM_LeadType__c = 'Customer Campaign';            
            lstObjCart.add(objCart);
        }
        
        try{
            if(lstObjCart!= null){
                System.debug('@@@@ lstObjCart : ' + lstObjCart);
                insert lstObjCart;
            }
            return lstObjCart;
        }
        Catch(DmlException e)
        {
            System.debug('The following exception has occurred while creating cart/ClassName:CCPM_CampaignMemberHandlerTest: ' + e.getMessage());
            return null;
        }
    }    
    /**
@author        Sriraman Sridharan(Deloitte)
@description   This method is targeted to create Account with nearest store and store employee.
*/      
    public static List<Account> CreateAccountsWithNearestStore(integer NoOfRecords, String appendUnique){
        CCPM_testDataFactory.createStore(1);
        CCPM_store__c lstStore = [select id, CCPM_storeID__c from CCPM_store__c Limit 1];
        CCPM_testDataFactory.createStoreEmployee('Man','RN', 'IDC','AM', lstStore.id);
        list<Account> lstObjCustomer=new list<Account>();
        id customerRecordtype=[select id from recordtype where name='Customer Account'].id;
        for(integer i=0;i<NoOfRecords;i++)
        {
            Account objCustomer=new Account();
            objCustomer.Name='testuatCustomer'+appendUnique+i;
            objCustomer.RecordTypeId=customerRecordtype;
            objCustomer.CCPM_accountNumber__c=''+appendUnique+i;
            objCustomer.CCPM_accountUniqueID__c=''+appendUnique+i;
            objCustomer.Phone='1243658790';
            objCustomer.CCPM_email__c='test@salesforce.com';
            objCustomer.BillingStreet='testStreet';
            objCustomer.BillingCity='testStreet';
            objCustomer.BillingState='Alaska';
            objCustomer.BillingPostalCode='32745';
            ObjCustomer.CCPM_SMSOptOut__c=false;
            ObjCustomer.CCPM_storeID__c = lstStore.CCPM_storeID__c;
            lstObjCustomer.add(objCustomer);
        }
        try{
            insert lstObjCustomer;
            return lstObjCustomer;
        }
        Catch(DmlException e)
        {
            System.debug('The following exception has occurred while creating customer/ClassName:CCPM_CampaignMemberHandlerTest: ' + e.getMessage());
            return null;
        }
    }
    /**
@author        Sriraman Sridharan(Deloitte)
@description   This method is targeted to create cart data.
*/   
    public static void CreateData(){
        CCPM_testDataFactory.createCustomSetting();
        list<Account> lstObjCustomer= new List<Account>();
        lstObjCustomer =  CreateAccountsWithNearestStore(1, 'AccountOne');
        if(lstObjCustomer != null && lstObjCustomer.size()>0){
            List<lead> lstObjCart = createCart(1, lstObjCustomer,'3214249105','Unique');
            List<lead> lstObjCartConverted = createClosedCart(1, lstObjCustomer,'3214249105','Uni');
            System.debug('@@@lstObjCart: ' + lstObjCart);
        }
        else{
            System.debug('@@@lstObjCustomer: ' + lstObjCustomer);
        }
        //Create Journey message
        
        User SysAdmin = CCPM_testDataFactory.CreateUser('System Administrator' ,'SysAdmin');
        System.runAs(SysAdmin){ 
            CCPM_journeyMessage__c objCampaignJourneyMessage = new CCPM_journeyMessage__c();
            objCampaignJourneyMessage.CCPM_isActive__c = true;
            objCampaignJourneyMessage.CCPM_messageFollowUpSMS__c = 'FollowUpMessage';
            objCampaignJourneyMessage.CCPM_messageInitialSMS__c = 'InitialMessage';
            try{
                insert objCampaignJourneyMessage;
            }
            catch(Exception e){
                system.debug('@@@Exception :' + e);
            } 
        }
        
        //Create Campaign
        CCPM_journeyMessage__c objCampaignJourneyMessage = [Select id,CCPM_messageFollowUpSMS__c,CCPM_messageInitialSMS__c from CCPM_journeyMessage__c];
        if(objCampaignJourneyMessage != null){
            Campaign objCampaign = new Campaign();
            objCampaign.Name = 'Black Friday Campaign';
            objCampaign.IsActive = true;
            objCampaign.CCPM_campaignJourneyMessage__c = objCampaignJourneyMessage.id;
            try{
                insert objCampaign; 
            }
            Catch(Exception e){
                System.debug('@@@Exception' + e);
            }
        }
        else{
            System.debug('@@@objCampaignJourneyMessage Is Null');
        }
        
    }    

    /**
@author        Sriraman Sridharan(Deloitte)
@description   This method is targeted to test the handler class.
*/       
  static testmethod void CampaignMemberInsertTest()
  {
      CreateData();
      lead ObjCart = [Select id, name from Lead Limit 1];
      System.debug('@@@ObjCart: ' + ObjCart);
      test.startTest();
      Campaign objCampaign = [Select id, name from Campaign Limit 1];
      System.debug('@@@objCampaign: ' + objCampaign);
      //Create campaign member
      CampaignMember objCampaignMember = new CampaignMember();
      objCampaignMember.LeadID = ObjCart.Id;
      objCampaignMember.CampaignId = objCampaign.Id;
      try{
         insert objCampaignMember; 
      }
      catch(Exception e){
          system.debug('@@@objCampaignMember ' + objCampaignMember);
      }
      try{
          CampaignMember ObjFinalCampaignMember = [Select id, name, LeadId, CampaignId from CampaignMember];
            System.debug('@@@ObjFinalCampaignMember: ' + ObjFinalCampaignMember);
      }
      Catch(Exception e){
          System.debug('@@@ObjFinalCampaignMember error');
      }
      
      
      CampaignMember objCampaignMemberUpdate = [Select id, name ,CCPM_cartUniqueID__c from CampaignMember Limit 1];
      objCampaignMemberUpdate.CCPM_cartUniqueID__c = '3214249105Test';
      update objCampaignMemberUpdate;
      //delete objCampaignMemberUpdate;
      Map<Id, SObject> mapOldItems = null;
      CCPM_CampaignMemberTriggerHandler objcampaignclass = new CCPM_CampaignMemberTriggerHandler();
      objcampaignclass.AfterUndelete(mapOldItems);
      
      Map<string, CCPM_DynamicCampaignSMS__mdt> mapdynamicCampaignSMS = new map<string, CCPM_DynamicCampaignSMS__mdt>();
        List<CCPM_DynamicCampaignSMS__mdt> lstdynamicCampaignSMS = [Select MasterLabel,CCPM_CampaignName__c,CCPM_campaignSMSDate__c ,CCPM_dynamicURL__c
                                                                   From CCPM_DynamicCampaignSMS__mdt Where CCPM_isActive__c = true];
      //CreateData();
      string strexpired ='Expired';
      
      lead ObjCartOne = [Select id, name from Lead where status =: strexpired Limit 1];
      try{
          ObjCartOne.CCPM_isInitialSMSSent__c = true;
          ObjCartOne.Status = CCPM_staticConstants.strLeadStatusConverted;
          update ObjCartOne;
      }
      catch(Exception e){
          system.debug('@@@ObjCartOne ' + ObjCartOne);
      }
      CampaignMember objCampaignMemberOne = new CampaignMember();
      objCampaignMemberOne.LeadID = ObjCartOne.Id;
      objCampaignMemberOne.CampaignId = objCampaign.Id;
      
      try{
         insert objCampaignMemberOne; 
      }
      catch(Exception e){
          system.debug('@@@objCampaignMemberOne ' + objCampaignMemberOne);
      }
      test.stopTest();
  }  
}