VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This individual has indicated they do not want to receive SMS communications from Verizon.</description>
        <inlineHelpText>This individual has indicated they do not want to receive SMS communications from Verizon.</inlineHelpText>
        <label>Do Not SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_OrganizationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CCPM_DisableTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization Setting</label>
</CustomObject>

VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_smsTemplate__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>CCPM_smsTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_endDate__c</fullName>
        <inlineHelpText>This field is the text value of the field SMS Follow up End Date</inlineHelpText>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_followupMessage__c</fullName>
        <label>Followup Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_initialMessage__c</fullName>
        <label>Initial Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_startDate__c</fullName>
        <inlineHelpText>This field is the text value of the field SMS Follow up Start Date</inlineHelpText>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>SMSTEMP-{000000}</displayFormat>
        <label>SMS Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag  to indicate if store is active or not</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_district__c</fullName>
        <description>The district store belongs to</description>
        <label>District</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_market__c</fullName>
        <description>The market store belongs to</description>
        <label>Market</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeEcode__c</fullName>
        <label>Store Ecode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_territory__c</fullName>
        <description>The territory store belongs to</description>
        <label>Territory</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Existing customer for whom abandoned cart has been created</description>
        <label>Account Holder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_CampingFollowUpMessageTemplate__c</fullName>
        <label>Camping FollowUp Message Template</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_StoreTimeZone__c</fullName>
        <label>Store Time Zone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_Type__c</fullName>
        <description>Type</description>
        <formula>IF(OR(AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = true),ISPICKVAL(CCPM_leadType__c,&apos;Customer SFDC Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales SFDC Manual&apos;)),&apos;Manual Lead&apos;, 
IF(OR(CONTAINS(TEXT(LeadSource), &quot;CRM&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Campaign&apos;)),&apos;Campaign Lead&apos;, 
IF(OR(CONTAINS(TEXT(CCPM_leadType__c),&quot;Customer Abandoned Cart&quot;), AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = false)),&apos;Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Abandoned Visit&apos;),&apos;Abandoned Visit Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Quotes&apos;),&apos;Quote Lead&apos;, 
IF(OR(ISPICKVAL(CCPM_leadType__c,&apos;Prospect SFDC Manual&apos;),CONTAINS(TEXT(CCPM_leadType__c),&quot;Prospect Abandoned Cart&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Prospect Telesales SFDC Manual&apos;), RecordType.Name = &apos;Prospect Cart&apos;, RecordType.Name = &apos;Prospect&apos;),&apos;Prospect&apos;, 
&apos;&apos; ))))))</formula>
        <inlineHelpText>Type of lead or prospect based on how it entered Salesforce</inlineHelpText>
        <label>Current Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartID__c</fullName>
        <description>Unique reference id of the cart</description>
        <externalId>true</externalId>
        <label>Cart ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_isManualLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if Prospect is Embedded Account</description>
        <inlineHelpText>if check Prospect is Embedded Account</inlineHelpText>
        <label>Manual Lead?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_ownerFirstName__c</fullName>
        <formula>Owner:User.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeDistrict__c</fullName>
        <formula>Store__r.CCPM_district__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store District</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeEcode__c</fullName>
        <formula>(Store__r.CCPM_storeEcode__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Ecode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeMarket__c</fullName>
        <formula>Store__r.CCPM_market__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeName__c</fullName>
        <formula>Store__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeRecommendedHours__c</fullName>
        <description>Formula field to store Recommended Visiting Hours</description>
        <formula>Store__r.CCPM_recommendedVisitingHours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula field to store Recommended Visiting Hours</inlineHelpText>
        <label>Store Recommended Hours</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeTerritory__c</fullName>
        <formula>Store__r.CCPM_territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Territory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_triggerInitialSMSDateTime__c</fullName>
        <description>Holds the date/time to trigger initial sms based on business hours and creation date/time of cart + 3 hours. Adds 3 hours to standard createdDate and then calculates the new date based on business hours</description>
        <label>Trigger Initial SMS Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_CampaignMemberTriggerHandler.cls
/**
*@name          CCPM_CampaignMemberTriggerHandler 
*@author        Sriraman Sridharan (Deloitte)
*@date          10/05/2017
*@description   This is a controller or class
*@Class         CCPM_CampaignMemberTriggerHandler
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Sriraman Sridharan,
Bharath Ammanamanchi (Deloitte)    10/05/2017   Initial Implementation.
Brigadesh Chandrasekar(Deloitte)   10/15/2017   Modified Version to account for Dynamic URL,Dynamic Store Ecode and Dynamic DATE on SMS body
*/
public class CCPM_CampaignMemberTriggerHandler implements CCPM_ITriggerHandler{
    
    
    // Allows unit tests (or other code) to disable this trigger for the transaction
    public static Boolean TriggerDisabled = false;
    public static Map<String, BusinessHours> mapBusinessHoursNameRec = CCPM_utility.mapBusinessHoursNameRec;
    public static String strLeadCustomerCartRT = Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.CCPM_leadCustomerCartRT).getRecordTypeId();
    public static DateTime dtmSysNow = System.now();
    /**
	@author       Bharath Ammanamanchi (Deloitte)
				  Brigadesh Chandrasekar (Deloitte)
	@description  Checks to see if the trigger has been disabled either by custom setting or by running code
	@param        N/A
	@return       Boolean
	*/ 
    public Boolean IsDisabled()
    {
        system.debug('!!! CCPM_CampaignMemberTriggerHandler !!!');
        CCPM_OrganizationSetting__c settings = CCPM_OrganizationSetting__c.getInstance(UserInfo.getUserId());
        if(settings != null && settings.CCPM_DisableTrigger__c == true){
            return true;
        }
        else
            return TriggerDisabled;
    }
    
    public void BeforeInsert(List<SObject> newItems) {

        
        /**************Method Declarations Start*/
        List<CampaignMember> lstNew = (List<CampaignMember>)newItems;
        
        List<CCPM_SMSMessage__c> lstSmsMessage = new List<CCPM_SMSMessage__c>();
        Map<id, Lead> mapLeadsToBeUpdated = new map<id, Lead>();
        Map<id, Campaign> mapCampaign = new map<id, Campaign>();
        Map<id, Lead> mapLead = new map<id, Lead>();
        
        /**************Method Declarations end*/
        
        /**************Methods calling functionalities in other classes start. */
        
        /**************Methods calling functionalities in other classes end.*/
        
        /**************First Loop for before Update Start*/
        
        if(lstNew!=null && lstNew.size()>0){
            for(CampaignMember objCampaignMember: lstNew){
                //Get the set of leads and campaigns
                if(objCampaignMember.LeadId != null){
                    //add Lead field to the list from all the leads
                    mapLead.put(objCampaignMember.LeadId, new Lead());
                }
                if(objCampaignMember.CampaignId != null){
                    //add Campaign field to the list from all the Campaigns
                    mapCampaign.put(objCampaignMember.CampaignId, new Campaign());
                }
            }
        }
        
        /**************First loop for Before Update End*/
        
        //Fetch the related open leads
        try{
            mapLead = new Map<id, Lead>([SELECT id,name,RecordTypeId,CCPM_isManualLead__c,CCPM_Account__c,CCPM_Account__r.CCPM_SMSOptOut__c,CCPM_StoreTimeZone__c,
            							CCPM_cartID__c,CCPM_mobileNumber__c,CCPM_storeEcode__c, Store__c,CCPM_storeName__c,CCPM_Type__c,CCPM_ownerFirstName__c,
            							CCPM_storeRecommendedHours__c,OwnerId,CCPM_SMSOptOut__c,CCPM_triggerInitialSMSDateTime__c,CCPM_CampingFollowUpMessageTemplate__c,
            							Store__r.CCPM_market__c,Store__r.CCPM_territory__c,Store__r.CCPM_district__c,CCPM_storeDistrict__c,CCPM_storeTerritory__c,CCPM_storeMarket__c 
            							From Lead 
										Where Id IN :mapLead.keySet() AND Status IN :CCPM_Utility.setOpenLeadStatus]);
        }
        catch(Exception e){
            CCPM_LogMessageUtility.logMessage(e,'scheduleMessages','scheduleMessages','Exception thrown while querying for leads',true); 
        }
        //Fetch the campaigns
        try{
            mapCampaign = new Map<id, Campaign>([SELECT id,name,                                      
            									(Select Id, CCPM_followupMessage__c, CCPM_initialMessage__c 
            										From CCPM_smsTemplates__r 
            										Where CCPM_isActive__c = true AND CCPM_startDate__c <=: dtmSysNow AND CCPM_endDate__c >= :dtmSysNow Order by CreatedDate Desc Limit 1)
            									From Campaign 
            									Where Id IN :mapCampaign.keySet()]);        
           
        }
        catch(Exception e){
            CCPM_LogMessageUtility.logMessage(e,'scheduleMessages','scheduleMessages','Exception thrown while querying for leads',true); 
        }
        
        /**************Second Loop Start*/
        for(CampaignMember objCampMem: lstNew){
        	Lead objLead;
            Campaign objCampaign;
            
            if(objCampMem.LeadId != null && mapLead.containsKey(objCampMem.LeadId)){
                objLead = mapLead.get(objCampMem.LeadId);  
            }
            
            if(objCampMem.CampaignId != null && mapCampaign.containsKey(objCampMem.CampaignId)){
                objCampaign = mapCampaign.get(objCampMem.CampaignId);
            }
            if(objLead == null){
            	objCampMem.addError('The assigned Lead does not qualify as a campaign member');
            }
            if(objCampaign == null){
            	objCampMem.addError('The assigned Campaign does not qualify as a campaign member');
            }

            if(objLead != null && objCampaign != null && CCPM_Collection.isNotNullEmpty(objCampaign.CCPM_smsTemplates__r) 
            	&& objLead.RecordTypeId == strLeadCustomerCartRT && objLead.CCPM_Type__c == Label.CCPM_leadTypeCampaignLead
            	&& !objLead.CCPM_Account__r.CCPM_SMSOptOut__c){
            		CCPM_CampaignMemberTriggerHandlerHelper.updateLeadFromCampaignMemeber(objLead, objCampaign);
            		mapLeadsToBeUpdated.put(objLead.Id, objLead);
            		
            		CCPM_SMSMessage__c objSmsMessage = CCPM_CampaignMemberTriggerHandlerHelper.createSMSForCampaignMember(objLead, objCampaign);
            		if(objSmsMessage != null){
            			lstSmsMessage.add(objSmsMessage);
            		}
            	}
        }
        /**************Second Loop End*/
        
        if(CCPM_Collection.isNotNullEmpty(lstSmsMessage)){
            try{
                insert lstSmsMessage;
            }
            catch(Exception e){
                CCPM_LogMessageUtility.logMessage(e,'CCPM_CampaignMemberHandler','BeforeInsert','Exception thrown while inserting SMSMessages for the Lead owner',true);
            }
        }
        
        if(CCPM_Collection.isNotNullEmpty(mapLeadsToBeUpdated)){ 
            try{
                update mapLeadsToBeUpdated.values(); 
            }
            catch(Exception e){
                CCPM_LogMessageUtility.logMessage(e,'CCPM_CampaignMemberHandler','BeforeInsert','Exception thrown while Updating leads',true);
            }
        }
    }
    
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the before update trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void BeforeUpdate(Map<Id, SObject> mapNewItems, Map<Id, SObject> mapOldItems){
        /**************Method Declarations Start*/
        Map<id, CampaignMember> mapNew = (Map<id, CampaignMember>)mapNewItems;
        Map<id, CampaignMember> mapOld = (Map<id, CampaignMember>)mapOldItems;
        /**************Method Declarations end*/
        
        /**************Methods calling functionalities in other classes start. */
        
        /**************Methods calling functionalities in other classes end.*/
        
        /**************First Loop Start*/
        
        /**************First loop End*/
    }
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the before delete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void BeforeDelete(Map<Id, SObject> mapOldItems){
        /**************Method Declarations Start*/
        Map<id, CampaignMember> mapOld = (Map<id, CampaignMember>)mapOldItems;
        /**************Method Declarations end*/
        
        /**************Methods calling functionalities in other classes start. */
        
        /**************Methods calling functionalities in other classes end.*/
        
        /**************First Loop Start*/
        
        /**************First loop End*/
    }
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after insert trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterInsert(Map<Id, SObject> mapNewItems){
        /**************Method Declarations Start*/
        Map<id, CampaignMember> mapNew = (Map<id, CampaignMember>)mapNewItems;
        /**************Method Declarations end*/
        
        /**************Methods calling functionalities in other classes start. */
        
        /**************Methods calling functionalities in other classes end.*/
        
        /**************First Loop Start*/
        
        /**************First loop End*/
    }
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after update trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterUpdate(Map<Id, SObject> mapNewItems, Map<Id, SObject> mapOldItems){
        /**************Method Declarations Start*/
        Map<id, CampaignMember> mapNew = (Map<id, CampaignMember>)mapNewItems;
        Map<id, CampaignMember> mapOld = (Map<id, CampaignMember>)mapOldItems;
        /**************Method Declarations end*/
        
        /**************Methods calling functionalities in other classes start. */
        
        /**************Methods calling functionalities in other classes end.*/
        
        /**************First Loop Start*/
        
        /**************First loop End*/
    }
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after delete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterDelete(Map<Id, SObject> mapOldItems){
        /**************Method Declarations Start*/
        
        Map<id, CampaignMember> mapOld = (Map<id, CampaignMember>)mapOldItems;
        /**************Method Declarations end*/
        
        /**************Methods calling functionalities in other classes start. */
        
        /**************Methods calling functionalities in other classes end.*/
        
        /**************First Loop Start*/
        
        /**************First loop End*/
    }
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the After undelete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterUndelete(Map<Id, SObject> mapOldItems){
        /**************Method Declarations Start*/
        Map<id, CampaignMember> mapOld = (Map<id, CampaignMember>)mapOldItems;
        /**************Method Declarations end*/
        
        /**************Methods calling functionalities in other classes start. */
        
        /**************Methods calling functionalities in other classes end.*/
        
        /**************First Loop Start*/
        
        /**************First loop End*/
    }
}