VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_NPSCategory__c</fullName>
        <inlineHelpText>Based on the NPS score; Promoter, Passive, Detractor</inlineHelpText>
        <label>Category</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_NPSComments__c</fullName>
        <inlineHelpText>Comments from the customer that filled out the NPS survey</inlineHelpText>
        <label>NPS Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_NPSDateSurveyCompleted__c</fullName>
        <label>Date Survey Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_NPSScore__c</fullName>
        <inlineHelpText>Net Promoter Score last entered from the account</inlineHelpText>
        <label>NPS Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_NPSmobileNumber__c</fullName>
        <inlineHelpText>MTN of the line that completed the survey for the account</inlineHelpText>
        <label>Survey MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_NPS__c.object
<CustomObject>
    <description>This Object is to store Customer Survey&apos;s</description>
    <fields>
        <fullName>CCPM_AccountHolderName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Holder Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NPS</relationshipLabel>
        <relationshipName>NPS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_Category__c</fullName>
        <formula>IF(CCPM_NPSScore__c&gt;8,&quot;Promoter&quot;,
IF(CCPM_NPSScore__c&gt;6,&quot;Passive&quot;, &quot;Detractor&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_NPSComments__c</fullName>
        <label>NPS Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_NPSScore__c</fullName>
        <label>NPS Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_dateSurveyCompleted__c</fullName>
        <label>Date Survey Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_surveyMobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <label>Survey MTN</label>
        <type>Phone</type>
    </fields>
    <label>NPS</label>
    <nameField>
        <label>Survey ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_NPSTriggerHandlerHelper.cls
/**
*@name          CCPM_NPSTriggerHandlerHelper
*@author        Anupreeta Chakraborty (Deloitte)
*@date          02/11/2018
*@description   This is a helpper class for CCPM_NPSTriggerHandler
*@Class         CCPM_NPSTriggerHandlerHelper
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Anupreeta Chakraborty (Deloitte)    02/11/2018   US -2359 Initial Implementation.

*/
public with sharing class CCPM_NPSTriggerHandlerHelper  {
    
    /**
@author        Anupreeta Chakraborty(Deloitte)
@description   Method updates NPS fields of related Account from the values of recent NPS record.
@param         sObject
@return        Account

*/
    public static Account populateNPSAccountfields(CCPM_NPS__c objNPS) {
        Account objAccnt;
        objAccnt = new Account(id = objNPS.CCPM_AccountHolderName__c);
        //Update Account fields with NPS data.
        objAccnt.CCPM_NPSCategory__c = objNPS.CCPM_Category__c;
        objAccnt.CCPM_NPSComments__c = objNPS.CCPM_NPSComments__c;
        objAccnt.CCPM_NPSScore__c = objNPS.CCPM_NPSScore__c;
        objAccnt.CCPM_NPSmobileNumber__c = objNPS.CCPM_surveyMobileNumber__c;
        objAccnt.CCPM_NPSDateSurveyCompleted__c = objNPS.CCPM_dateSurveyCompleted__c;
        return objAccnt;
        
    }    
   
}