VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <encrypted>true</encrypted>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_processingQueue__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_InsertedDateTime__c</fullName>
        <label>Inserted Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SObjectType__c</fullName>
        <label>SObject Type</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Processing Queue</label>
    <nameField>
        <label>Processing Queue Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processing Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <fields>
        <fullName>CCPM_leadRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the associated lead.</description>
        <inlineHelpText>Refers to the associated lead.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>SMS Messages</relationshipLabel>
        <relationshipName>SMS_Message_Sent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_SMSSchedulesToBeRemoved__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_InsertedDateTime__c</fullName>
        <description>Time during which the record was inserted</description>
        <label>Inserted DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SObjectType__c</fullName>
        <description>Indicated the type of object from which the record was inserted</description>
        <label>SObject Type</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>SMS Schedules To Be Removed</label>
    <nameField>
        <displayFormat>SMS2R-{00}</displayFormat>
        <label>SMS Schedules To Be Removed</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Schedules To Be Removed</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <description>Email address specified by the customer when creating the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Email of the lead / prospect. Required to save a Prospect if the MTN is unavailable.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_processQueueBatchTest.cls
/**
*@name          CCPM_processQueueBatchTest
*@author        Paras Shah (Deloitte)
*@date          09/29/2017
@description    To Test the Batch class CCPM_processQueueBatchTest


@testClass:     CCPM_processQueueBatchTest
Modification    Log:
------------------------------------------------------------------------------------
Developer               Date                                Description
------------------------------------------------------------------------------------
Paras Shah(Deloitte)    09/29/2017                          Original Version
CCPM_processQueue__c
*/

@isTest
public class CCPM_processQueueBatchTest {
    
    public static void createData(){
        //test.startTest();
        CCPM_testDataFactory.createCustomSetting();
        List<CCPM_processingQueue__c> lstSMSSchedules = new List<CCPM_processingQueue__c>();
        List<String> stUniqueID = new List<String>();
        List<lead> lstlead = new List<lead>();
        //Create Account Unique ID's
        /*
        for(Integer i=0; i< CCPM_staticConstants.NoOfRecords; i++){
            stUniqueID.add(CCPM_testDataFactory.generateRandomString(10));
            //stUniqueID.add('Unique'+i);
        }*/
        CCPM_testDataFactory.createCustomer(CCPM_staticConstants.NoOfRecords, 'RSH');
        list<Account> lstAccounts = [Select id, CCPM_accountUniqueID__c from Account where CCPM_accountUniqueID__c != NULL limit :CCPM_staticConstants.NoOfRecords ];
        //Create leads for every account
        for(Integer j=0; j< CCPM_staticConstants.NoOfRecords; j++){
            lead objCart = new lead();
                objCart.LastName=CCPM_testDataFactory.generateRandomString(10);
                objCart.Status='New';
                objCart.CCPM_accountUniqueID__c = lstAccounts[j].CCPM_accountUniqueID__c;
                objCart.CCPM_mobileNumber__c = '3213187287';
                objCart.CCPM_email__c ='test@gmail.com';
                objCart.Company ='Deloitte';
                objCart.RecordTypeId = CCPM_staticConstants.strLeadCustomerAbandonedCartRecordTypeID;
                lstlead.add(objCart);
        }
        system.debug('@@@lstlead' + lstlead);
        
        try{
            insert lstlead;
        }catch(Exception e){
            CCPM_LogMessageUtility.logMessage(e,'RemoveSmsScheduleBatchHandlerTest','Test Method','Exception thrown while updating list of sms message schedules',ccpm_staticConstants.boolSMSSent);
        }
        List<lead> lstAlllead = [Select id,Status,CCPM_mobileNumber__c,RecordTypeId,CCPM_accountUniqueID__c from lead];
        system.debug('@@@lstAlllead' + lstAlllead);
        List<CCPM_SMSMessage__c> insSMSMessageObj= new List<CCPM_SMSMessage__c>();
        //Create SMS Message Records
        for(Integer i=0; i< lstAlllead.size(); i++){
            /*system.debug('@@@lstAlllead[i].id ' +lstAlllead[i].id);
            system.debug('@@@lstAlllead[i].CCPM_accountUniqueID__c ' +lstAlllead[i].CCPM_accountUniqueID__c);*/
            CCPM_SMSMessage__c insSMSMessageObjRecord= CCPM_testDataFactory.insertSMSRecord(CCPM_staticConstants.NoOfRecords,'Test',CCPM_staticConstants.strMessageTypeInitialSMSPart1,lstAlllead[i].id);
            insSMSMessageObj.add(insSMSMessageObjRecord);
        }
        try{
            system.debug('@@@insSMSMessageObj' + insSMSMessageObj);
            insert insSMSMessageObj;
        }catch(Exception e){
            CCPM_LogMessageUtility.logMessage(e,'RemoveSmsScheduleBatchHandlerTest','Test Method','Exception thrown while updating list of sms message schedules',ccpm_staticConstants.boolSMSSent);
        }
        List<CCPM_SMSMessage__c> lstSmsMessage = [Select id, name,CCPM_leadRecord__c,CCPM_leadRecord__r.CCPM_accountUniqueID__c from CCPM_SMSMessage__c];
        system.debug('@@@lstSmsMessage' + lstSmsMessage);
        //Create revords in the Queue for sms schedules to be removed
        for(Integer i=0; i< lstAccounts.size(); i++){
            lstSMSSchedules.add(new CCPM_processingQueue__c(
                CCPM_accountUniqueID__c = lstAccounts[i].CCPM_accountUniqueID__c,
                CCPM_storeID__c = CCPM_testDataFactory.generateRandomString(10),
                CCPM_InsertedDateTime__c = system.now(),
                CCPM_Status__c = CCPM_staticConstants.StatusNew,
                CCPM_SObjectType__c = CCPM_staticConstants.SObjectTypeAccount
            ));
        }
        try{
            insert lstSMSSchedules;
        }catch(Exception e){
            CCPM_LogMessageUtility.logMessage(e,'RemoveSmsScheduleBatchHandlerTest','Test Method','Exception thrown while updating list of sms message schedules',ccpm_staticConstants.boolSMSSent);
        }
        List<CCPM_processingQueue__c> lstSmsMessageToRemove = [Select id, name,CCPM_accountUniqueID__c from CCPM_processingQueue__c];
        system.debug('@@@lstSmsMessageToRemove' + lstSmsMessageToRemove);
        
        system.debug('@@@stUniqueID' + stUniqueID);
        List<lead> lstLeadsForRemovingScedules = [Select id,Status,CCPM_mobileNumber__c,RecordTypeId,CCPM_accountUniqueID__c from lead];
        //where CCPM_accountUniqueID__c IN :stUniqueID

       /* For(Integer i=0;i<stUniqueID.size();i++){
            //String test =stUniqueID.get(i);
            String strQuery;
            List<lead> lstLeadsForRemovingScedules = [Select id,Status,CCPM_mobileNumber__c,RecordTypeId,CCPM_accountUniqueID__c from lead where CCPM_accountUniqueID__c =:stUniqueID[i]];
            //this.strQuery = 'select id, name, CCPM_accountUniqueID__c, CCPM_storeID__c, CCPM_Status__c, CCPM_InsertedDateTime__c from CCPM_SMSSchedulesToBeRemoved__c where CCPM_Status__c ='+ '\'' + status + '\'' +' limit '+CCPM_staticConstants.strRemoveSmsScheduleBatchLimit;
            system.debug('@@@lstLeadsForRemovingScedulesInTest' + lstLeadsForRemovingScedules);
        } */
        system.debug('@@@lstLeadsForRemovingScedulesInTest2' + lstLeadsForRemovingScedules);
    }
    
    
    public static testMethod void RemoveScheduleTest(){
        
        createData();
        /*
        List<lead> lstLeadsForRemovingScedulestest = [Select id,Status,CCPM_mobileNumber__c,RecordTypeId,CCPM_accountUniqueID__c from lead];
        system.debug('@@@lstLeadsForRemovingScedulestest3' + lstLeadsForRemovingScedulestest);
        */
        
        String CRON_EXP = '0 0 * * * ?'; 
        CCPM_processQueueJob scheduledJob = new CCPM_processQueueJob(); 
        system.schedule('CCPM_processQueueJob', CRON_EXP, scheduledJob);
        
        CCPM_processQueueBatch RemoveSms =new CCPM_processQueueBatch();
        database.executebatch(RemoveSms,integer.valueof(CCPM_staticConstants.strBatchChunk));

        //test.stopTest();        
    }
    
}