VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <encrypted>true</encrypted>
        <label>Account Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <encrypted>true</encrypted>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the individual&apos;s address, this is their geographically closest Verizon store.</description>
        <inlineHelpText>Nearest store to the account owner</inlineHelpText>
        <label>Nearest Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_StoreID__c</fullName>
        <formula>CCPM_Store__r.CCPM_storeID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_Store__c</fullName>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Store Employees</relationshipLabel>
        <relationshipName>Store_Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCPM_employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>CCPM Sales Rep,CCPM Retail Sales Rep,CCPM Retail Store Management,CCPM Retail District Management,CCPM Telesales Rep,CCPM Telesales Supervisor,CCPM Telesales Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Store Manager</fullName>
                </value>
                <value>
                    <fullName>Assistant Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSFollowUpDate__c</fullName>
        <inlineHelpText>The date &amp; time for the SMS to be scheduled to be sent</inlineHelpText>
        <label>SMS Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <description>Account Number is the customer&apos;s account which could have multiple lines and multiple carts</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account number for this mobile number</inlineHelpText>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartID__c</fullName>
        <description>Unique reference id of the cart</description>
        <externalId>true</externalId>
        <label>Cart ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique Identified to create/update carts(leads). The format will be &apos;A:&apos;+Account Number&apos; +&apos;-M:&apos; + Mobile Number + &apos;-S:&apos; + Lead Status. This field will be used to upset leads in Salesforce for carts (leads) for existing customers.</description>
        <externalId>true</externalId>
        <label>Cart Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_cartlastHandledBy__c</fullName>
        <description>ID of the rep who last handled the cart</description>
        <label>Cart Last Handled By</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_confirmEmail__c</fullName>
        <description>Confirm Email address specified by the customer when creating the cart</description>
        <label>Confirm Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_confirmMTN__c</fullName>
        <description>Confirm Mobile number which has been used to create the cart</description>
        <label>Confirm MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_createdChannel__c</fullName>
        <description>The field shows the created channel on the prospect</description>
        <inlineHelpText>This represents the initial channel of the lead or prospect upon creation</inlineHelpText>
        <label>Created Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_createdDate__c</fullName>
        <label>Cart Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <description>Email address specified by the customer when creating the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Email of the lead / prospect. Required to save a Prospect if the MTN is unavailable.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_eventType__c</fullName>
        <inlineHelpText>The Conversation Topic that requires an SMS follow up to be sent.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samsung GS9 BOGO</fullName>
                </value>
                <value>
                    <fullName>TMP OE - Q2 2018</fullName>
                </value>
                <value>
                    <fullName>Add a Line</fullName>
                </value>
                <value>
                    <fullName>Confirming with Family First</fullName>
                </value>
                <value>
                    <fullName>Connected Device</fullName>
                </value>
                <value>
                    <fullName>Contract Terminating Soon</fullName>
                </value>
                <value>
                    <fullName>Feature Add</fullName>
                </value>
                <value>
                    <fullName>Gift for Upcoming Occasion</fullName>
                </value>
                <value>
                    <fullName>iPhone X</fullName>
                </value>
                <value>
                    <fullName>iPhone X send message</fullName>
                </value>
                <value>
                    <fullName>New Service</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>Special Event</fullName>
                </value>
                <value>
                    <fullName>Tablets</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_followupMessageBody__c</fullName>
        <description>This formula field builds up the follow up message for a customer.</description>
        <formula>&quot;Hi, this is &quot;+ Owner:User.FirstName +&quot; from Verizon. I&apos;m just following up on my earlier message. If you are interested in visiting a store please let me know! (FreeVzMsg)&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Follow-Up Message Body</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_isInitialSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</description>
        <inlineHelpText>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Initial SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isStoreEmployeeUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Store Employee Updated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_storeEmployeeHandlerTest.cls
/**
*@name          CCPM_storeEmployeeHandler
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          08/28/2017
@description    Test class for 
@testClass      CCPM_storeEmployeeHandlerTest
Modification    Log:
------------------------------------------------------------------------------------
Developer                               Date                        Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)       08/28/2017          	Original Version
Sriraman Sridharan(Deloitte)		   09/15/2017			Modified Version
*/
@isTest
public class CCPM_storeEmployeeHandlerTest {
    
    public static lead objLead;
    public static lead newLead;
    public static string StrMessageType;
    public static datetime dttScheduledate;
    public static list<string> lstAccountUniqueID=new list<string>();
    public static list<string> lstLastName=new list<string>();
    public static list<string> lstcartUniqueId=new list<string>();
    public static list<string> lststoreID=new list<string>();
    public static list<string> lstcartLastHandledBy=new list<string>();
    Public static list<id> lstLeadId= new list<id>();
    Public static list<Lead> lstLead=new list<Lead>();    
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to create Data required for the test class.
*/     
    public static List<lead> createCart(Integer NoOfRecords, List<String> accountUniqueID, List<String> LastName, List<String> cartUniqueId, List<String> storeID, List<String> cartLastHandledBy,string strmobilenumber,string strRecordtypeID,boolean boolAccountUniqueIDFlag,string EventType)
    {   
        //To create test user and assign as OwnerId
        List<lead> lstObjCart = new List<lead>();
        for(integer i=0;i<NoOfRecords;i++){
            Lead objCart=new Lead();
            objCart.LastName=LastName[i];
            objCart.FirstName=LastName[i];
            objCart.Status='New';
            objCart.Company = '1';           
            objCart.CCPM_accountNumber__c = accountUniqueID[i];
            if(boolAccountUniqueIDFlag)
            {
                objCart.CCPM_accountUniqueID__c = accountUniqueID[i];  
            }
            if(EventType!=null)
            {
                objCart.CCPM_eventType__c = EventType;
                
            }
                            objcart.CCPM_SMSFollowUpDate__c = system.now().addHours(5);
            objCart.CCPM_storeID__c = storeID[i];
            objCart.CCPM_cartlastHandledBy__c = cartLastHandledBy[i];
            objCart.CCPM_mobileNumber__c = '3213187287';
            objCart.CCPM_email__c ='test@gmail.com';
            objCart.CCPM_confirmEmail__c='test@gmail.com';
            datetime date1=Datetime.now();
            objCart.CCPM_createdDate__c=date1.addHours(-5);
            objCart.CCPM_cartUniqueID__c = cartUniqueId[i];
            objCart.CCPM_SMSLegalOptIn__c =true;
            objCart.CCPM_confirmMTN__c= strMobilenumber;
            if(i/2 == 0){
                objCart.CCPM_isStoreEmployeeUpdated__c = false;
            }
            else{
                objCart.CCPM_isStoreEmployeeUpdated__c = true;
            }
            objCart.RecordTypeId = strRecordtypeID;
            objCart.CCPM_cartID__c=cartUniqueId[i];
            objCart.CCPM_createdChannel__c ='Telesales';
            objCart.ccpm_leadtype__c = 'Prospect Telesales SFDC Manual';
            lstObjCart.add(objCart);
            
        }
        
        try{
            if(lstObjCart!= null){
                System.debug('@@@@ lstObjCart : ' + lstObjCart);
                insert lstObjCart;
            }
            return lstObjCart;
        }
        Catch(DmlException e)
        {
            System.debug('The following exception has occurred while creating cart/ClassName:CCPM_testDataFactory: ' + e.getMessage());
            return null;
        }
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to create Data required for the test class.
*/     
    Public static void CreateData(string strmobilenumber,string strRecordtypeID,string strrole,boolean boolAccountUniqueIDFlag,string EventType)
    {
        CCPM_testDataFactory.createCustomer(1, 'abc');
        CCPM_testDataFactory.createStore(2);
        list<CCPM_Store__c > lststore=[select id,CCPM_storeID__c from CCPM_Store__c limit 1];
        if(lstStore!= null && lstStore.size()>0 && lstStore.isEmpty()==false){
            lststoreID.add(lstStore[0].CCPM_storeID__c);
        }
        list<Account > lstCustomer=[select CCPM_accountUniqueID__c from Account limit 1];
        if(lstCustomer!= null && lstCustomer.size()>0 &&lstCustomer.isEmpty()==false ){
            lstAccountUniqueID.add(lstCustomer[0].CCPM_accountUniqueID__c);
        }
        lstLastName.add('TestLastName');
        lstcartUniqueId.add('TestCartUniqueId');
        lstcartLastHandledBy.add('LHB'); 
        CCPM_testDataFactory.createStoreEmployee('Man','RN', 'IDC','AM', lstStore[0].id);
        if(strrole==null && EventType==null)
        {
            createCart(1, lstAccountUniqueID, lstLastName, lstcartUniqueId, lststoreID, lstcartLastHandledBy,strmobilenumber,strRecordtypeID,true,null);
        }
        else{
            list<CCPM_StoreEmployee__c> lstStoreEmployee = [select id,CCPM_employee__c,CCPM_employee__r.IsActive from CCPM_storeEmployee__c where CCPM_role__c=:strrole];
            System.debug('@Test_lstStoreEmployee->'+lstStoreEmployee);
            list<User> lstUser = [select id,firstname,lastname from user where id = :lstStoreEmployee[0].CCPM_employee__c limit 1];
            System.debug('@Test_lstUser->'+lstUser);
            System.runas(lstUser[0])
            {
                createCart(1, lstAccountUniqueID, lstLastName, lstcartUniqueId, lststoreID, lstcartLastHandledBy,strmobilenumber,strRecordtypeID,boolAccountUniqueIDFlag,EventType);
            }
        }
    }    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to test insertLeadShareSettings.
*/  
    
    static testmethod void StoreEmployeeInsertTest()
    {	
        list<Lead> lstLead = new list<Lead>();
        CCPM_testDataFactory.createCustomSetting();
        CreateData('3213187287',CCPM_staticConstants.strLeadCustomerAbandonedCartRecordTypeID,null,true,null);
        lstLead=[Select Id,CCPM_isStoreEmployeeUpdated__c,CCPM_mobileNumber__c,RecordTypeId,OwnerId,Store__c,CCPM_isInitialSMSSent__c,CCPM_followupMessageBody__c,CCPM_initialMessageBodyPartII__c,CCPM_initialMessageBodyPartI__c from lead limit 1];
        list<CCPM_store__c> lstStore = new list<CCPM_store__c>();
        lstStore = [select id from CCPM_store__c where id != :lstLead[0].Store__c ];
        list<CCPM_storeEmployee__c> lstStoreEmployee = [select id,CCPM_Store__c, ccpm_employee__c,CCPM_employee__r.id,CCPM_employee__r.IsActive from CCPM_storeEmployee__c where CCPM_role__c=:CCPM_staticConstants.strStoreAssistantManager limit 1];
        lstLead[0].Store__c=lstStoreEmployee[0].CCPM_Store__c;
        update lstLead;
        task objtask = new task();
                objtask.WhoId =lstLead[0].id;
        objtask.RecordTypeId= Schema.SObjectType.task.getRecordTypeInfosByName().get(Label.CCPM_taskToDoRT).getRecordTypeId() ;
        objtask.status='Not Started';
        insert objtask;
        
        system.debug('@@@lstStoreEmployee.CCPM_employee__r.IsActive ' + lstStoreEmployee[0].CCPM_employee__r.IsActive);
        list<User> lstUsr = [Select id,isactive from User where id=:lstStoreEmployee[0].CCPM_employee__r.id];
        system.debug('@@@lstUsr '+ lstUsr);
        lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreSalesRep;
        update lstStoreEmployee;
        lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreAssistantManager;
        update lstStoreEmployee;
        lstStoreEmployee[0].CCPM_IsActive__c = false;
        update lstStoreEmployee;
        lstStoreEmployee[0].CCPM_IsActive__c = true;
        update lstStoreEmployee;
        lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreManager;
        update lstStoreEmployee;
                lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreAssistantManager;
        lstStoreEmployee[0].CCPM_IsActive__c = false;
         lstStoreEmployee[0].CCPM_previousactive__c=true;
        update lstStoreEmployee;
        
        
        Test.startTest();
        //Update Owner
        list<CCPM_storeEmployee__c> lstStoreEmployeOwner = [select id,CCPM_Store__c, ccpm_employee__c,CCPM_employee__r.id from CCPM_storeEmployee__c where CCPM_employee__r.id =: lstLead[0].OwnerId limit 1];
        if(lstStoreEmployeOwner!= null && lstStoreEmployeOwner.size()>0){
            system.debug('@@@lstStoreEmployeOwner Not Empty');
            lstStoreEmployeOwner[0].CCPM_IsActive__c = true;
            update lstStoreEmployeOwner;
            lstStoreEmployeOwner[0].CCPM_IsActive__c = false;
            update lstStoreEmployeOwner;
        }
        /*
        lstLead[0].Store__c = null;
        //lstLead[0].CCPM_storeID__c = null;
        Update lstLead[0];
        */
        list<CCPM_storeEmployee__c> lstStoreEmployeOwnerForEmptyStore = [select id,CCPM_Store__c, ccpm_employee__c,CCPM_employee__r.id from CCPM_storeEmployee__c where CCPM_employee__r.id =: lstLead[0].OwnerId limit 1];
        if(lstStoreEmployeOwnerForEmptyStore!= null && lstStoreEmployeOwnerForEmptyStore.size()>0){
            system.debug('@@@lstStoreEmployeOwnerForEmptyStore Not Empty');
            lstStoreEmployeOwnerForEmptyStore[0].CCPM_IsActive__c = true;
            update lstStoreEmployeOwnerForEmptyStore;
            lstStoreEmployeOwnerForEmptyStore[0].CCPM_IsActive__c = false;
            update lstStoreEmployeOwnerForEmptyStore;
            CCPM_storeEmployeeBatch storeEmployeeBatch =  new CCPM_storeEmployeeBatch();
             DataBase.executeBatch(storeEmployeeBatch);
        }
        Map<Id, CCPM_storeEmployee__c> mapstrEmp = new Map<id, CCPM_storeEmployee__c>(lstStoreEmployeOwner);
        CCPM_storeEmployeeTriggerHandler strEmpHdlr = new CCPM_storeEmployeeTriggerHandler();
        strEmpHdlr.BeforeInsert(mapstrEmp.values());
        strEmpHdlr.BeforeDelete(mapstrEmp);
        strEmpHdlr.AfterUpdate(mapstrEmp, mapstrEmp );
        strEmpHdlr.AfterDelete(mapstrEmp);
        strEmpHdlr.AfterUndelete(mapstrEmp);
        Test.stopTest();
    }
    
    static testmethod void StoreEmployeeBatchTest()
    {	
        list<Lead> lstLead = new list<Lead>();
        CCPM_testDataFactory.createCustomSetting();
        CreateData('3213187287',CCPM_staticConstants.strLeadCustomerAbandonedCartRecordTypeID,null,true,null);
        lstLead=[Select Id,CCPM_isStoreEmployeeUpdated__c,CCPM_mobileNumber__c,RecordTypeId,OwnerId,Store__c,CCPM_isInitialSMSSent__c,CCPM_followupMessageBody__c,CCPM_initialMessageBodyPartII__c,CCPM_initialMessageBodyPartI__c from lead limit 1];
        list<CCPM_store__c> lstStore = new list<CCPM_store__c>();
        lstStore = [select id from CCPM_store__c where id != :lstLead[0].Store__c ];
        list<CCPM_storeEmployee__c> lstStoreEmployee = [select id,CCPM_Store__c, ccpm_employee__c,CCPM_employee__r.id,CCPM_employee__r.IsActive from CCPM_storeEmployee__c where CCPM_role__c=:CCPM_staticConstants.strStoreAssistantManager limit 1];
        lstLead[0].Store__c=lstStoreEmployee[0].CCPM_Store__c;
                    lstLead[0].CCPM_createdChannel__c ='Telesales';
        update lstLead;
        task objtask = new task();
                objtask.WhoId =lstLead[0].id;
        objtask.RecordTypeId= Schema.SObjectType.task.getRecordTypeInfosByName().get(Label.CCPM_taskToDoRT).getRecordTypeId() ;
        objtask.status='Not Started';
        insert objtask;
        
        system.debug('@@@lstStoreEmployee.CCPM_employee__r.IsActive ' + lstStoreEmployee[0].CCPM_employee__r.IsActive);
        list<User> lstUsr = [Select id,isactive from User where id=:lstStoreEmployee[0].CCPM_employee__r.id];
        system.debug('@@@lstUsr '+ lstUsr);
        lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreSalesRep;
        update lstStoreEmployee;
        lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreAssistantManager;
        update lstStoreEmployee;
        lstStoreEmployee[0].CCPM_IsActive__c = false;
        update lstStoreEmployee;
        lstStoreEmployee[0].CCPM_IsActive__c = true;
        update lstStoreEmployee;
        lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreManager;
        update lstStoreEmployee;
                lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreAssistantManager;
        lstStoreEmployee[0].CCPM_IsActive__c = false;
         lstStoreEmployee[0].CCPM_previousactive__c=true;
        update lstStoreEmployee;
         lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreAssistantManager;
         lstStoreEmployee[0].CCPM_IsActive__c = true;
         lstStoreEmployee[0].CCPM_previousactive__c=false;
        update lstStoreEmployee;
         lstStoreEmployee[0].CCPM_role__c = CCPM_staticConstants.strStoreAssistantManager;
         lstStoreEmployee[0].CCPM_IsActive__c = true;
         lstStoreEmployee[0].CCPM_previousactive__c=false;
        update lstStoreEmployee;
        
        Test.startTest();
        //Update Owner
        list<CCPM_storeEmployee__c> lstStoreEmployeOwner = [select id,CCPM_Store__c, ccpm_employee__c,CCPM_employee__r.id from CCPM_storeEmployee__c where CCPM_employee__r.id =: lstLead[0].OwnerId limit 1];
        if(lstStoreEmployeOwner!= null && lstStoreEmployeOwner.size()>0){
            system.debug('@@@lstStoreEmployeOwner Not Empty');
            lstStoreEmployeOwner[0].CCPM_IsActive__c = true;
            update lstStoreEmployeOwner;
            lstStoreEmployeOwner[0].CCPM_IsActive__c = false;
            update lstStoreEmployeOwner;
        }
        /*
        lstLead[0].Store__c = null;
        //lstLead[0].CCPM_storeID__c = null;
        Update lstLead[0];
        */
        list<CCPM_storeEmployee__c> lstStoreEmployeOwnerForEmptyStore = [select id,CCPM_Store__c, ccpm_employee__c,CCPM_employee__r.id from CCPM_storeEmployee__c where CCPM_employee__r.id =: lstLead[0].OwnerId limit 1];
        if(lstStoreEmployeOwnerForEmptyStore!= null && lstStoreEmployeOwnerForEmptyStore.size()>0){
            system.debug('@@@lstStoreEmployeOwnerForEmptyStore Not Empty');
            lstStoreEmployeOwnerForEmptyStore[0].CCPM_IsActive__c = true;
            update lstStoreEmployeOwnerForEmptyStore;
            lstStoreEmployeOwnerForEmptyStore[0].CCPM_IsActive__c = false;
            update lstStoreEmployeOwnerForEmptyStore;
            CCPM_storeEmployeeBatch storeEmployeeBatch =  new CCPM_storeEmployeeBatch();
             DataBase.executeBatch(storeEmployeeBatch);
        }
        CCPM_storeEmployeeBatch objbatch = new CCPM_storeEmployeeBatch();
			Database.executeBatch(objbatch,5);	
         String StrCRONEXP = ccpm_staticConstants.StrCRONEXP;
    CCPM_storeEmployeeBatch objSch = new CCPM_storeEmployeeBatch(); 
        system.schedule('CCPM_UpdateAccountUniqueIdBatchTest- 10 Mins', StrCRONEXP, objSch);
        Map<Id, CCPM_storeEmployee__c> mapstrEmp = new Map<id, CCPM_storeEmployee__c>(lstStoreEmployeOwner);
        CCPM_storeEmployeeTriggerHandler strEmpHdlr = new CCPM_storeEmployeeTriggerHandler();
        strEmpHdlr.BeforeInsert(mapstrEmp.values());
        strEmpHdlr.BeforeDelete(mapstrEmp);
        strEmpHdlr.AfterUpdate(mapstrEmp, mapstrEmp );
        strEmpHdlr.AfterDelete(mapstrEmp);
        strEmpHdlr.AfterUndelete(mapstrEmp);
        Test.stopTest();
    }
     
}