VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the individual&apos;s address, this is their geographically closest Verizon store.</description>
        <inlineHelpText>Nearest store to the account owner</inlineHelpText>
        <label>Nearest Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <fields>
        <fullName>CCPM_MessageStatus__c</fullName>
        <description>Refers to the status of the Message sent based on response code.</description>
        <inlineHelpText>Refers to the status of the Message sent based on response code.</inlineHelpText>
        <label>Message Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Resend Failed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_requestID__c</fullName>
        <label>RequestID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_responseCode__c</fullName>
        <description>Response codes recorded for each API call made</description>
        <label>Response Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_responseMessage__c</fullName>
        <description>Captures the Response Message for the Heywire API callout made.</description>
        <inlineHelpText>Captures the Response Message for the Heywire API callout made.</inlineHelpText>
        <label>Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_followupMessageBody__c</fullName>
        <description>This formula field builds up the follow up message for a customer.</description>
        <formula>&quot;Hi, this is &quot;+ Owner:User.FirstName +&quot; from Verizon. I&apos;m just following up on my earlier message. If you are interested in visiting a store please let me know! (FreeVzMsg)&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Follow-Up Message Body</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_initialMessageBodyPartII__c</fullName>
        <description>2nd part of initial message body so that customer does not receive single message cut-off message</description>
        <formula>&apos;Would you like me to book an appt &apos;+Store__r.CCPM_recommendedVisitingHours__c+&apos; to visit my store? If not, what time/day works for you? Reply &quot;X&quot; to stop msgs (FreeVzMsg).&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initial Message Body Part II</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_initialMessageBodyPartI__c</fullName>
        <description>Body of the initial SMS which needs to sent to customer 4 hours after cart has been created</description>
        <formula>&quot;Hi, &quot;+Owner:User.FirstName + &quot; here from Verizon. Come visit us at the &quot;+Store__r.Name + &quot; store to chat about the great items saved in your cart (FreeVzMsg)&quot;</formula>
        <label>Initial Message Body Part I</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_SMSMessageTriggerTest.cls
/**
*@name          CCPM_SMSMessageTriggerTest
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          07/17/2017
@description    Test class for CCPM_SMSMessageTrigger
@testClass      CCPM_SMSMessageTriggerTest
Modification    Log:
------------------------------------------------------------------------------------
Developer                               Date                 Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)       07/17/2017          Original Version
*/
@isTest
public class CCPM_SMSMessageTriggerTest {
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   This method is targeted to create Data required for the test class.
*/     
    Public static void CreateData()
    {	
        list<string> lstAccountUniqueID=new list<string>();
        list<string> lstLastName=new list<string>();
        list<string> lstcartUniqueId=new list<string>();
        list<string> lststoreID=new list<string>();
        list<string> lstcartLastHandledBy=new list<string>();
        list<id> lstLeadId= new list<id>();
        list<Lead> lstLead=new list<Lead>();
        
        //Create Custom setting
        CCPM_testDataFactory.createCustomSetting();
        CCPM_testDataFactory.createCustomer(1, 'abc');
        CCPM_testDataFactory.createStore(1);
        list<CCPM_Store__c > lststore=[select id,CCPM_storeID__c from CCPM_Store__c limit 1];
        if(lstStore!= null && lstStore.size()>0 && lstStore.isEmpty()==false){
            lststoreID.add(lstStore[0].CCPM_storeID__c);
        }
        list<Account > lstCustomer=[select CCPM_accountUniqueID__c from Account limit 1];
        if(lstCustomer!= null && lstCustomer.size()>0 &&lstCustomer.isEmpty()==false ){
            lstAccountUniqueID.add(lstCustomer[0].CCPM_accountUniqueID__c);
        }
        lstLastName.add('TestLastName');
        lstcartUniqueId.add('TestCartUniqueId');
        lstcartLastHandledBy.add('LHB'); 
        CCPM_testDataFactory.createCartdefaultRecordType(1, lstAccountUniqueID, lstLastName, lstcartUniqueId, lststoreID, lstcartLastHandledBy);
        lstLead=[Select Id,CCPM_mobileNumber__c,RecordTypeId,ownerid,Store__c,CCPM_followupMessageBody__c,CCPM_initialMessageBodyPartII__c,CCPM_initialMessageBodyPartI__c from lead limit 1];
        if(lstLead!= null && lstLead.size()>0 && lstLead.isEmpty()==false)
        {
            lstLeadId.add(lstLead[0].id);
        }
        CCPM_testDataFactory.createStoreEmployee('Man','RN', 'IDC','AM', lstStore[0].id);
        
    }
    
    /**
*@author        Brigadesh Chandrasekar(Deloitte)
*@description   This test method is targeted to test the Trigger logic for initial SMS
*@param :       None
*/
    static testMethod void sendInitialSMSPart1(){
        
        CreateData();
        list<Lead> lstLead = [select id, ownerid from lead where ownerid!= NULL limit 1];
        List<CCPM_SMSMessage__c> SMSObjRecord = CCPM_testDataFactory.insertSMSObjectRecord(50,'Hi%HI',CCPM_staticConstants.strMessageTypeInitialSMSPart1,lstLead[0].id);
        insert SMSObjRecord;
        system.debug('@@@ SMSObjRecord' +SMSObjRecord);
        SMSObjRecord[0].CCPM_responseCode__c = '204';
        SMSObjRecord[0].CCPM_responseMessage__c = 'No Content';
        SMSObjRecord[0].CCPM_requestID__c = 'abc^def';
        SMSObjRecord[0].CCPM_MessageStatus__c='Sent';
        update SMSObjRecord[0];
        System.assert(SMSObjRecord[0].CCPM_MessageStatus__c == CCPM_staticConstants.strMessageStatusSent);
        
    }
    
    /**
*@author        Brigadesh Chandrasekar(Deloitte)
*@description   This test method is targeted to test the Trigger logic for Prospect 1st SMS
*@param :       None
*/
    static testMethod void sendProspectSMSPart1(){
        
        CreateData();
        list<Lead> lstLead = [select id, ownerid from lead where ownerid!= NULL limit 1];
        List<CCPM_SMSMessage__c> SMSObjRecord = CCPM_testDataFactory.insertSMSObjectRecord(50,'Hi%HI',CCPM_staticConstants.strMessageTypeProspectFirstSMSPart1,lstLead[0].id);
        insert SMSObjRecord;
        system.debug('@@@ SMSObjRecord' +SMSObjRecord);
        SMSObjRecord[0].CCPM_responseCode__c = '204';
        SMSObjRecord[0].CCPM_responseMessage__c = 'No Content';
        SMSObjRecord[0].CCPM_requestID__c = 'abc^def';
        SMSObjRecord[0].CCPM_MessageStatus__c='Sent';
        update SMSObjRecord[0];
        System.assert(SMSObjRecord[0].CCPM_MessageStatus__c == CCPM_staticConstants.strMessageStatusSent);
        
    }
    
    /**
*@author        Brigadesh Chandrasekar(Deloitte)
*@description   This test method is targeted to test the Trigger logic for FollowUp SMS
*@param :       None
*/
    static testMethod void FollowUpSMS(){
        
        CreateData();
        list<Lead> lstLead = [select id, ownerid from lead where ownerid!= NULL limit 1];
        List<CCPM_SMSMessage__c> SMSObjRecord = CCPM_testDataFactory.insertSMSObjectRecord(50,'Hi',CCPM_staticConstants.strMessageTypeFollowUpSMS,lstLead[0].id);
        insert SMSObjRecord;
        system.debug('@@@ SMSObjRecord' +SMSObjRecord);
        SMSObjRecord[0].CCPM_responseCode__c = '204';
        SMSObjRecord[0].CCPM_responseMessage__c = 'No Content';
        SMSObjRecord[0].CCPM_requestID__c = 'abc';
        SMSObjRecord[0].CCPM_MessageStatus__c='Sent';
        update SMSObjRecord[0];
        System.assert(SMSObjRecord[0].CCPM_MessageStatus__c == CCPM_staticConstants.strMessageStatusSent);  
        
    }
    
    
    
}