VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This individual has indicated they do not want to receive SMS communications from Verizon.</description>
        <inlineHelpText>This individual has indicated they do not want to receive SMS communications from Verizon.</inlineHelpText>
        <label>Do Not SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_journey__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_Type__c</fullName>
        <label>Type</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Journey</relationshipLabel>
        <relationshipName>Journey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_createdDate__c</fullName>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_doubleOptOutSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Double Opt Out Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isFollowUpSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Follow-Up SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isInitialSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Initial SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isMerged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Merged?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isProspectSMSsent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Event SMS sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <label>MTN</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Journey</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Existing customer for whom abandoned cart has been created</description>
        <label>Account Holder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_DoubleOptOutSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Double Opt Out Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSFollowUpDate__c</fullName>
        <inlineHelpText>The date &amp; time for the SMS to be scheduled to be sent</inlineHelpText>
        <label>SMS Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_Type__c</fullName>
        <description>Type</description>
        <formula>IF(OR(AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = true),ISPICKVAL(CCPM_leadType__c,&apos;Customer SFDC Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales SFDC Manual&apos;)),&apos;Manual Lead&apos;, 
IF(OR(CONTAINS(TEXT(LeadSource), &quot;CRM&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Campaign&apos;)),&apos;Campaign Lead&apos;, 
IF(OR(CONTAINS(TEXT(CCPM_leadType__c),&quot;Customer Abandoned Cart&quot;), AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = false)),&apos;Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Abandoned Visit&apos;),&apos;Abandoned Visit Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Quotes&apos;),&apos;Quote Lead&apos;, 
IF(OR(ISPICKVAL(CCPM_leadType__c,&apos;Prospect SFDC Manual&apos;),CONTAINS(TEXT(CCPM_leadType__c),&quot;Prospect Abandoned Cart&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Prospect Telesales SFDC Manual&apos;), RecordType.Name = &apos;Prospect Cart&apos;, RecordType.Name = &apos;Prospect&apos;),&apos;Prospect&apos;, 
&apos;&apos; ))))))</formula>
        <inlineHelpText>Type of lead or prospect based on how it entered Salesforce</inlineHelpText>
        <label>Current Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_createdDate__c</fullName>
        <label>Cart Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_isFollowUpSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if follow up SMS was sent</description>
        <inlineHelpText>Has a follow up SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Follow-Up SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isInitialSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</description>
        <inlineHelpText>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Initial SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isManualLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if Prospect is Embedded Account</description>
        <inlineHelpText>if check Prospect is Embedded Account</inlineHelpText>
        <label>Manual Lead?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isMerged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Merged?</description>
        <inlineHelpText>This flag is automatically checked during the merge process once we merge the child lead</inlineHelpText>
        <label>Merged ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isProspectSMSsent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate whethet Prospect 1st SMS was sent.</description>
        <inlineHelpText>Has an Event SMS been sent based off the Event based SMS and event date selected?</inlineHelpText>
        <label>Event SMS sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_lastInteraction__c</fullName>
        <description>Date/Time being recorded for last interaction between the customer and Heywire process in salesforce</description>
        <label>Last Interaction Date/TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_leadChannel__c</fullName>
        <description>IF the &apos;Lead Source&apos; field value equals ATG-ECOM-DESK or ATG-ECOM-GGDESK or ATG-ECOM-GGMOB or ATG-ECOM-GGTAB or ATG-ECOM-MAPP or ATG-ECOM-MDOT or ATG-ECOM-MIPP or ATG-ECOM-TDOT then &apos;Lead Channel&apos; should be set as &apos;Digital&apos;
IF the &apos;Lead Source&apos; field value equals NETACE then &apos;Lead Channel&apos; should be set as &apos;Retail&apos;</description>
        <formula>IF(CONTAINS(TEXT(CCPM_leadType__c),&quot;Telesale&quot;),&apos;Telesales&apos;,
IF(CONTAINS(TEXT(LeadSource),&quot;ATG-ECOM&quot;),&apos;Digital&apos;,
IF(
OR(ISPICKVAL(LeadSource,&apos;NETACE&apos;), ISPICKVAL(LeadSource,&apos;Quote-Retail&apos;),ISPICKVAL(LeadSource,&apos;POS-Store Visit&apos;),ISPICKVAL(LeadSource,&apos;CRM&apos;),CONTAINS(TEXT(CCPM_leadType__c),&quot;Manual&quot;)
), &quot;Retail&quot;, &quot;&quot;
)
)
)</formula>
        <inlineHelpText>The channel the prospect abandoned cart in.</inlineHelpText>
        <label>Current Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_expireInActiveLeadsBatch.cls
/**
*@name          CCPM_expireInActiveLeadsBatch
*@author        Paras Shah (Deloitte)
*@date          05/23/2017
*@description   For Expiring Leads
*@testClass     CCPM_expireInActiveLeadsTest

Modification    Log:
------------------------------------------------------------------------------------
Developer                       Date                    Description
------------------------------------------------------------------------------------
Paras Shah(Deloitte)            05/23/2017              Original Version
Paras Shah(Deloitte)            12/14/2017              Changed the logic for DISTSCE-1721 to take SMS Followup Date into account 
                                                        for Prospects and Manual Leads
*/

global class CCPM_expireInActiveLeadsBatch implements Database.Batchable <sObject>  {
    
    public static Boolean executed = false;

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        //Days of Lead Expiry
        Integer intDaysOfLeadExpiry = 0;
        Set<String> setOpenLeadStatuses = CCPM_utility.setOpenLeadStatus;
        Set<String> setCartRectTypes = CCPM_utility.setRectTypestoExpire;
        
        if(Label.CCPM_daysOfLeadExpiry != null) {
            intDaysOfLeadExpiry = Integer.valueOf(Label.CCPM_daysOfLeadExpiry);
            
            //Check for date of today - the expiry days
            Date dtLeadExpirationDate = Date.today().addDays(intDaysOfLeadExpiry);
        }        
        
        String query= 'SELECT Id,Recordtype.Name,CCPM_isManualLead__c,CCPM_SMSFollowUpDate__c, CCPM_mobileNumber__c, CCPM_leadChannel__c, CCPM_Type__c,' +
            			'LeadSource, Status, CCPM_isMerged__c, CCPM_Account__c, CCPM_isInitialSMSSent__c, CCPM_isFollowUpSMSSent__c,' + 
            			'CCPM_isProspectSMSsent__c, CCPM_DoubleOptOutSent__c, CCPM_SMSOptOut__c, CCPM_CreatedDate__c from Lead WHERE '+
                      '((( CCPM_lastInteraction__c < :dtLeadExpirationDate OR ( CCPM_createdDate__c < :dtLeadExpirationDate ' +
                      'AND CCPM_lastInteraction__c = Null)) AND  (Recordtype.Name IN : setCartRectTypes) AND CCPM_isManualLead__c = false) '+
                      'OR  ( CCPM_isManualLead__c = true AND CCPM_lastInteraction__c < :dtLeadExpirationDate AND CCPM_SMSFollowUpDate__c < TODAY) '+
                      'OR  ( CCPM_isManualLead__c = true AND CCPM_lastInteraction__c = Null AND CCPM_SMSFollowUpDate__c < :dtLeadExpirationDate AND CCPM_SMSFollowUpDate__c < TODAY) '+
                      'OR  ( Recordtype.Name = \'Prospect\' AND CCPM_lastInteraction__c = Null AND CCPM_SMSFollowUpDate__c < :dtLeadExpirationDate AND CCPM_SMSFollowUpDate__c < TODAY) '+
                      'OR  ( Recordtype.Name = \'Prospect\' AND CCPM_lastInteraction__c  < :dtLeadExpirationDate AND CCPM_SMSFollowUpDate__c < TODAY) '+
                      'OR  ( Recordtype.Name = \'Customer Abandoned Visit\' AND CCPM_lastInteraction__c = Null AND CCPM_SMSFollowUpDate__c < :dtLeadExpirationDate AND CCPM_SMSFollowUpDate__c < TODAY) '+
                      'OR  ( Recordtype.Name = \'Customer Abandoned Visit\' AND CCPM_lastInteraction__c  < :dtLeadExpirationDate AND CCPM_SMSFollowUpDate__c < TODAY)) '+
                      'AND ( Status in :setOpenLeadStatuses)';
        
        return Database.getQueryLocator(query);
    }

 /**
*@author        Paras Shah (Deloitte)
*@description   Execute Method
*@return        Void(None)
*/ 
    
    global void execute(Database.BatchableContext BC, List<Lead> scope)
    {   
      List<Lead> lstLeadUpdate = new List<Lead>();
      List<CCPM_journey__c> lstJourney = new List<CCPM_journey__c>();

        //Add Leads that need to be expired in a list
        for(LEAD objLead: scope)
        {
            system.debug('objLead'+objLead);
                objLead.Status = Label.CCPM_expiredLeadStatus;
                lstLeadUpdate.add(objLead);
            	CCPM_journey__c objJourney = CCPM_utility.createJourneyForCLosedLead(objLead);
            	lstJourney.add(objJourney);
        }
        system.debug('objJourney');
        
        if(lstLeadUpdate.size()>0) {
            try {
                //Bulkified Update
                update lstLeadUpdate;
            }
            Catch(Exception e)
            {
                CCPM_LogMessageUtility.logMessage(e,'CCPM_expireInActiveLeads','expireInActiveLeads','Exception thrown while Expiring the Leads',true);
            }
        }
        if(CCPM_Collection.isNotNullEmpty(lstJourney)){
            try{
                insert lstJourney;
            }
            catch(Exception e){
                CCPM_LogMessageUtility.logMessage(e,'CCPM_expireInActiveLeads','expireInActiveLeads','Exception thrown while inserting Journey',true);
            }
        }
    }

    
    global void finish(Database.BatchableContext BC) { }

}