VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This individual has indicated they do not want to receive SMS communications from Verizon.</description>
        <inlineHelpText>This individual has indicated they do not want to receive SMS communications from Verizon.</inlineHelpText>
        <label>Do Not SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <encrypted>true</encrypted>
        <label>Account Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <encrypted>true</encrypted>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_isVisionAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this box is checked when account is saved from Vision</description>
        <label>VisionAccount?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_UpdateAccountUniqueIdBatchTest.cls
/**
*@name          CCPM_UpdateAccountUniqueIdBatchTest 
*@author        Manjunath Keshava (Deloitte)
*@date          06/21/2017
@description   @(US_0392) This is  a  method to Test CCPM_UpdateAccountUniqueIdBatch  
Modification    Log:
------------------------------------------------------------------------------------
Developer                       Date                                Description
------------------------------------------------------------------------------------
Manjunath Keshava (Deloitte)    11/03/2017               			 Original Version
*/
@isTest
public class CCPM_UpdateAccountUniqueIdBatchTest 
{
     @isTest
    public static void LeadUpdateTest()
    {
      CCPM_testdataFactory.createCustomSetting();
        Account objCustomer=new Account();
        objCustomer.Name='testuatCustomer';
        objCustomer.CCPM_accountNumber__c='3728-1';
        objCustomer.CCPM_accountUniqueID__c='';
        objCustomer.CCPM_isVisionAccount__c=true;
        objCustomer.Phone='1243658790';
        objCustomer.CCPM_email__c='test@salesforce.com';
        objCustomer.BillingStreet='testStreet';
        objCustomer.BillingCity='testStreet';
        objCustomer.BillingState='California';
        objCustomer.BillingPostalCode='32745';
        ObjCustomer.CCPM_SMSOptOut__c=false;
        ObjCustomer.CCPM_mobileNumber__c='3214249106';
       insert objCustomer;
        
        CCPM_updateAccountUniqueIDBatch objbatch = new CCPM_updateAccountUniqueIDBatch();
			Database.executeBatch(objbatch);	
 // Creating the object for the scheduler class and invoking the execution
       String StrCRONEXP = ccpm_staticConstants.StrCRONEXP;
    CCPM_updateAccountUniqueIDJob objSch = new CCPM_updateAccountUniqueIDJob(); 
        system.schedule('CCPM_UpdateAccountUniqueIdBatchTest- 10 Mins', StrCRONEXP, objSch); 
    }


}