VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This individual has indicated they do not want to receive SMS communications from Verizon.</description>
        <inlineHelpText>This individual has indicated they do not want to receive SMS communications from Verizon.</inlineHelpText>
        <label>Do Not SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in Staging(Oracle) based on Account Number. Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Owner’s MTN</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the individual&apos;s address, this is their geographically closest Verizon store.</description>
        <inlineHelpText>Nearest store to the account owner</inlineHelpText>
        <label>Nearest Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_processingQueue__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_InsertedDateTime__c</fullName>
        <label>Inserted Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SObjectType__c</fullName>
        <label>SObject Type</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_queueType__c</fullName>
        <label>Queue Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SMS Schedules To Be Removed</fullName>
                </value>
                <value>
                    <fullName>Cart Type Processing for Converted Leads</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Processing Queue</label>
    <nameField>
        <label>Processing Queue Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processing Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Existing customer for whom abandoned cart has been created</description>
        <label>Account Holder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_Type__c</fullName>
        <description>Type</description>
        <formula>IF(OR(AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = true),ISPICKVAL(CCPM_leadType__c,&apos;Customer SFDC Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales SFDC Manual&apos;)),&apos;Manual Lead&apos;, 
IF(OR(CONTAINS(TEXT(LeadSource), &quot;CRM&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Campaign&apos;)),&apos;Campaign Lead&apos;, 
IF(OR(CONTAINS(TEXT(CCPM_leadType__c),&quot;Customer Abandoned Cart&quot;), AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = false)),&apos;Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Abandoned Visit&apos;),&apos;Abandoned Visit Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Quotes&apos;),&apos;Quote Lead&apos;, 
IF(OR(ISPICKVAL(CCPM_leadType__c,&apos;Prospect SFDC Manual&apos;),CONTAINS(TEXT(CCPM_leadType__c),&quot;Prospect Abandoned Cart&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Prospect Telesales SFDC Manual&apos;), RecordType.Name = &apos;Prospect Cart&apos;, RecordType.Name = &apos;Prospect&apos;),&apos;Prospect&apos;, 
&apos;&apos; ))))))</formula>
        <inlineHelpText>Type of lead or prospect based on how it entered Salesforce</inlineHelpText>
        <label>Current Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/objects/LOG_LogMessage__c.object
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_accountHandler.cls
/**
*@name          CCPM_accountHandler
*@author        Deepak Mazumdar (Deloitte)
*@date          1/31/2017
@description    Handler class for CCPM_account trigger
@testClass      CCPM_accountHandlerTest
Modification    Log:
------------------------------------------------------------------------------------
Developer               Date                                Description
------------------------------------------------------------------------------------
Deepak Mazumdar(Deloitte)       1/31/2016                           Original Version
Sriraman Sridharan(Deloitte)    1/31/2016                           Original Version
Manjunath Keshava(Deloitte)     07/14/2017                          Added Null checks (US-1618)
Aneesha Ragireddy				7/13/2017							initial version insertRecordstoCustomObject
Sriraman Sridharan(Deloitte)    7/18/2017                           Updated Version insertRecordstoCustomObject
Paras Shah(Deloitte)			12/15/2017							Added a change to populate the Queue Type for Processing Queue object
*/
public class CCPM_accountHandler {
    public static List<LOG_LogMessage__c> lstleadhdlrLogMsg = new List<LOG_LogMessage__c>();
    /**
@author        Sriraman Sridharan (Deloitte)
@description   This method populates store reference based on store id
@param         list of new accounts and list of old accounts
@return        Void(None)
*/  
    public static void populateStoreBasedOnStoreId(list<Account> lstNewAccounts, list<Account> lstOldAccounts){
        // Contains the store records of the StoreID from the List of accounts
        List<CCPM_Store__c> lstStoreRecords=new  List<CCPM_Store__c>() ;
        // Contains the StoreId's from the list of accounts
        Set<String> storeIDs                    = new Set<String>();
        // Map of the StoreId's and the SFDC Id's from the store records
        Map<String, ID> storeIdToSFDCStoreID    = new Map<String, ID>();
        
        // This condition checks if its triggered is on Update
        if(lstOldAccounts != null && !lstOldAccounts.isEmpty())
        {
            for(Integer i=0;i<lstNewAccounts.size();i++){
                if(lstNewAccounts[i].CCPM_storeID__c!=lstOldAccounts[i].CCPM_storeID__c)
                {
                    if(lstNewAccounts[i].CCPM_storeID__c!=null)
                    {
                        storeIDs.add(lstNewAccounts[i].CCPM_storeID__c);
                    }
                    else{
                        lstNewAccounts[i].CCPM_store__c = null;
                    }
                } 
            }
        }
        // This condition checks if its triggered is on Insert
        else{
            if(lstNewAccounts!=null && !lstNewAccounts.isEmpty())
            {
                for(Account acc : lstNewAccounts)
                {
                    if( acc.CCPM_mobileNumber__c!= NULL )
                    {
                        acc.CCPM_mobileNumber__c = acc.CCPM_mobileNumber__c.replaceAll(CCPM_staticConstants.strnondigits,'');
                    } 
                    storeIDs.add(acc.CCPM_storeID__c);
                }
            }
        }
        
        // Query for the store records using the storeID's from the store object using the StoreId's from the list of accounts
        try{
            if(storeIDs!=null && !storeIDs.isEmpty())
                lstStoreRecords = [Select   Id, 
                                   Name, 
                                   CCPM_storeID__c 
                                   FROM     CCPM_Store__c 
                                   WHERE    CCPM_storeID__c IN: storeIDs];
        }
        catch(Exception e){
            
            CCPM_LogMessageUtility.logMessage(e,'CCPM_accountHandler','populateStoreBasedOnStoreId','Exception thrown while querying for store records',true);
        }
        
        
        // Iterate through the list of store records and populate the storeIdToSFDCStoreID map with StoreID's and the SFDC ID's of Stores
        if(lstStoreRecords!=null && !lstStoreRecords.isEmpty())
        {
            for(CCPM_Store__c Store : lstStoreRecords)
            {
                if(!storeIdToSFDCStoreID.containsKey(Store.CCPM_storeID__c)) 
                {
                    storeIdToSFDCStoreID.put(Store.CCPM_storeID__c, Store.Id );
                }
            } 
        }
        
        // Iterate through the list of accounts and update the store lookup field  using the storeIdToSFDCStoreID Map
        for(Account acc : lstNewAccounts)
        {
            if(storeIdToSFDCStoreID.containsKey(acc.CCPM_storeID__c) && storeIdToSFDCStoreID.get(acc.CCPM_storeID__c)!= null)
            {
                //if(storeIdToSFDCStoreID.get(acc.CCPM_storeID__c)!= null)
                acc.CCPM_store__c = storeIdToSFDCStoreID.get(acc.CCPM_storeID__c);
            }
        }
        
    }
    
    /**
@author        Sriraman Sridharan/Aneesha Ragireddy (Deloitte)
@description   This method inserts records in the custom object if the customer is opted out
@param         list of new accounts and list of old accounts
@return        Void(None)
*/  
    public static void insertRecordstoCustomObject(Map<Id,Account> mapNew, Map<Id,Account> mapOld)
    {
        List<CCPM_processingQueue__c> lstSMSSchedules = new List<CCPM_processingQueue__c>();
        set<string> setOpenStatus = ccpm_utility.setleadOpenStatus;
        if(CCPM_Collection.isNotNullEmpty(mapNew)){
            for(Account objAcc : [Select Id, (Select Id From Leads__r Where ccpm_type__c = 'Manual Lead' and Status in :setOpenStatus) From Account Where Id IN :mapNew.keySet()]){
                Account objAccNew = mapNew.get(objAcc.Id);
                Account objAccOld = mapOld.get(objAcc.Id);
                if((!CCPM_Collection.isNotNullEmpty(objAcc.Leads__r)) && objAccNew.CCPM_SMSOptOut__c != objAccOld.CCPM_SMSOptOut__c && objAccNew.CCPM_SMSOptOut__c == true){
                    lstSMSSchedules.add(new CCPM_processingQueue__c(CCPM_accountUniqueID__c = objAccNew.CCPM_accountUniqueID__c,
                                                                    CCPM_storeID__c = objAccNew.CCPM_storeID__c,
                                                                    CCPM_InsertedDateTime__c = system.now(),
                                                                    CCPM_Status__c = Label.CCPM_LeadNewStatus,
                                                                    CCPM_queueType__c    = Label.CCPM_SMSSchedulesToBeRemoved,
                                                                    CCPM_SObjectType__c = 'Account'));
                }
            }
        }
        
        try{
            if(CCPM_Collection.isNotNullEmpty(lstSMSSchedules)){
                insert lstSMSSchedules;
            }
            
        }catch(Exception e){
            LOG_LogMessage__c log = CCPM_utility.logMessage(e,'Error','CCPM_accountHandler','BeforeUpdate','Exception thrown while querying for Accounts','');
            lstleadhdlrLogMsg.add(log);
        }  
        
        if(CCPM_Collection.isNotNullEmpty(lstleadhdlrLogMsg)){
            upsert lstleadhdlrLogMsg;
        }
    }
}