VZDEV/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This individual has indicated they do not want to receive SMS communications from Verizon.</description>
        <inlineHelpText>This individual has indicated they do not want to receive SMS communications from Verizon.</inlineHelpText>
        <label>Do Not SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique ID of nearest store / outlet</description>
        <inlineHelpText>Nearest store ID to the account owner</inlineHelpText>
        <label>Nearest Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Based on the individual&apos;s address, this is their geographically closest Verizon store.</description>
        <inlineHelpText>Nearest store to the account owner</inlineHelpText>
        <label>Nearest Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_accountHandlerTest.cls
/**
*@name          CCPM_accountHandler
*@author        Sriraman Sridharan (Deloitte)
*@date          07/12/2016
@description    To Test the Handler class CCPM_accountHandler


@testClass:     CCPM_accountHandlerTest
Modification    Log:
------------------------------------------------------------------------------------
Developer               Date                                Description
------------------------------------------------------------------------------------
Sriraman(Deloitte)      01/31/2016                          Original Version
*/

@istest(SeeAllData=False)
public class CCPM_accountHandlerTest {    
    /**
*@author        Sriraman Sridharan (Deloitte)
*@description   This method is targeted to test the CCPM_accountHandler class
*@param :       None
*/
    @istest(SeeAllData=False) public static void testAccountCreation()
    {   
        test.startTest();
        User integrationUser=CCPM_testDataFactory.CreateUser('CCPM Integration User', 'integrationUser');
        System.runAs(integrationUser){
            try{
                CCPM_testDataFactory.createCustomSetting();
                //Create and query all the stores
                list<CCPM_Store__c> lstObjStore = CCPM_testDataFactory.createStore(CCPM_staticConstants.NoOfRecords);
                if(CCPM_staticConstants.NoOfRecords!=null)
                {
                list<CCPM_Store__c> stores=[Select id,CCPM_storeID__c from CCPM_store__c limit :CCPM_staticConstants.NoOfRecords];
                //Create Customers
                list<Account> lstCustomer = CCPM_testDataFactory.createCustomer(CCPM_staticConstants.NoOfRecords,'A');
                list<Account> lstCustomerWithStoreId = CCPM_testDataFactory.createCustomer(CCPM_staticConstants.NoOfRecords,'B');
                if(lstCustomer!=null && lstCustomer.size()>0 && lstCustomer.isEmpty()==false)
                {
                for(integer i=0;i<(lstCustomer.size()/2);i++)
                {
                    if(stores.size()>0 && stores!=null){
                        lstCustomer[i].CCPM_Store__c=stores[i].id;
                        lstCustomer[i].CCPM_storeID__c=stores[i].CCPM_storeID__c;
                         lstCustomer[i].CCPM_SMSOptOut__c=true;

                    }
                }
                
                Update lstCustomer;
                
                for(integer i=0;i<lstCustomer.size()/2;i++){
                    System.assert(lstCustomer[i].CCPM_store__c == stores[i].id);
                }
                for(integer i=0;i<lstCustomer.size();i++)
                {
                    lstCustomer[i].CCPM_storeID__c=null;
                }
                Update lstCustomer;
                }
                }
            }
            Catch(DMLException e)
            {
                CCPM_LogMessageUtility.logMessage(e,'CCPM_leadTest','testLeadCreation','Exception thrown while querying for store records',true);
            }
        }
        test.stopTest();
    }
}