VZDEV/src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>CCPM_communicationDirection__c</fullName>
        <description>This field describes if the SMS is either sent or received.</description>
        <inlineHelpText>This field describes if the SMS is either sent or received.</inlineHelpText>
        <label>Communication Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outbound</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountNumber__c</fullName>
        <description>Account Number is the customer&apos;s account which could have multiple lines and multiple carts</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account number for this mobile number</inlineHelpText>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_sendSMSToCustomerCentralRestWrapper.cls
/**
*@name          CCPM_sendSMSToCustomerCentralWrapper
*@author        Tanweer Maredia (Deloitte)
*@date          05/18/2017
@description    Creating a response body which have list of activity and lead object attributes
@testClass      CCPM_sendSMSToCustomerCentralRestTest
------------------------------------------------------------------------------------
Developer               Date                                Description
------------------------------------------------------------------------------------
Tanweer Maredia(Deloitte)    05/19/2017                          Original Version
*/

/*
 * Wrapper support class calls from getCustomerInteractions method to format all task and 
 * lead attribute naming convention in Json Response body
 */

global with sharing class CCPM_sendSMSToCustomerCentralRestWrapper {
    
    public String ActivityId;
    public String LeadId;
    public String AccountNumber;
    public String CustomerName;
    public String MTN;
    public String Subject;
    public String Comments;
    public String Type;
    public String CommunicationDirection;
    Public Datetime LastModifiedDate;
    public Datetime CreatedDate;
    
    //creating a response wrapper that calling from setSMStoCustomerCentral with list of task and accountnumber to generate responsebody
    public List<CCPM_sendSMSToCustomerCentralRestWrapper> setSMStoCustomerCentralResponse(List<Task> lstTaskResult, lead leadEncrptingAccountNumberAndMTN){
        List<CCPM_sendSMSToCustomerCentralRestWrapper> wrapActivityobjectlist = new List<CCPM_sendSMSToCustomerCentralRestWrapper>();
       
        if (lstTaskResult.size()>0){
            
            //looping through task query result assigned it and add in responsebody
            for( Task tsk : lstTaskResult){
                CCPM_sendSMSToCustomerCentralRestWrapper wrapActivity = new CCPM_sendSMSToCustomerCentralRestWrapper();
                wrapActivity.ActivityId =tsk.id;
                wrapActivity.AccountNumber = leadEncrptingAccountNumberAndMTN.CCPM_accountNumber__c;
                wrapActivity.MTN = leadEncrptingAccountNumberAndMTN.CCPM_mobileNumber__c;
                wrapActivity.Subject = tsk.Subject;
                wrapActivity.Comments = tsk.Description;
                wrapActivity.Type = tsk.Type;
                wrapActivity.CustomerName = tsk.who.name;
                wrapActivity.leadId = tsk.who.id;
                wrapActivity.CommunicationDirection = tsk.CCPM_communicationDirection__c;
                wrapActivity.LastModifiedDate = tsk.LastModifiedDate;
                wrapActivity.CreatedDate = tsk.CreatedDate;
               
                wrapActivityobjectlist.add(wrapActivity);
            }            
        }else{
           System.debug('Wrapper Activity was not found');
        }
        return wrapActivityobjectlist;
    }
 
}