VZDEV/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CCPM_eventLabel__c</fullName>
        <label>Event Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventStartDate__c</fullName>
        <inlineHelpText>This field is the text value of the field &apos;Event Start Date&apos; . Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event Start Date</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_leadCustomerType__c</fullName>
        <label>Lead Customer Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_segmentation__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field will capture which Territories’ Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Segmentations</relationshipLabel>
        <relationshipName>CCPM_segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_districts1__c</fullName>
        <inlineHelpText>This field will capture which District’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Districts 1</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK01</fullName>
                </value>
                <value>
                    <fullName>CAR01-Coastal Carolinas</fullName>
                </value>
                <value>
                    <fullName>CAR02-Eastern NC</fullName>
                </value>
                <value>
                    <fullName>CAR03-NC Triad</fullName>
                </value>
                <value>
                    <fullName>CAR04-SC Central</fullName>
                </value>
                <value>
                    <fullName>CAR05-SCSE Coast</fullName>
                </value>
                <value>
                    <fullName>CAR06-Triangle North</fullName>
                </value>
                <value>
                    <fullName>CAR07-Triangle South</fullName>
                </value>
                <value>
                    <fullName>CC01</fullName>
                </value>
                <value>
                    <fullName>CC02</fullName>
                </value>
                <value>
                    <fullName>CC03</fullName>
                </value>
                <value>
                    <fullName>CC04</fullName>
                </value>
                <value>
                    <fullName>CC05</fullName>
                </value>
                <value>
                    <fullName>CC06</fullName>
                </value>
                <value>
                    <fullName>CP01</fullName>
                </value>
                <value>
                    <fullName>CP02</fullName>
                </value>
                <value>
                    <fullName>CP03</fullName>
                </value>
                <value>
                    <fullName>CP04</fullName>
                </value>
                <value>
                    <fullName>CP05</fullName>
                </value>
                <value>
                    <fullName>CP06</fullName>
                </value>
                <value>
                    <fullName>CP07</fullName>
                </value>
                <value>
                    <fullName>DS01-Las Vegas West</fullName>
                </value>
                <value>
                    <fullName>DS02-Phoenix North</fullName>
                </value>
                <value>
                    <fullName>DS03-Phoenix West</fullName>
                </value>
                <value>
                    <fullName>DS04-Scottsdale</fullName>
                </value>
                <value>
                    <fullName>DS05-Phoenix East</fullName>
                </value>
                <value>
                    <fullName>DS06-Phoenix South</fullName>
                </value>
                <value>
                    <fullName>DS07-Tucson West</fullName>
                </value>
                <value>
                    <fullName>DS08-Tucson East</fullName>
                </value>
                <value>
                    <fullName>DS09-Albuquerque</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_districts2__c</fullName>
        <inlineHelpText>This field will capture which District’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Districts 2</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GLW04-Far West Chicago</fullName>
                </value>
                <value>
                    <fullName>GLW05-South Chicago-NW IN</fullName>
                </value>
                <value>
                    <fullName>GLW06-Peoria-Davenport</fullName>
                </value>
                <value>
                    <fullName>GLW07-SW Chicago</fullName>
                </value>
                <value>
                    <fullName>GLW08-W MI-Grand Rapids</fullName>
                </value>
                <value>
                    <fullName>GLW09-NE Indiana</fullName>
                </value>
                <value>
                    <fullName>HI01</fullName>
                </value>
                <value>
                    <fullName>HI02</fullName>
                </value>
                <value>
                    <fullName>HQ-Telesales</fullName>
                </value>
                <value>
                    <fullName>KM01-Southern IL</fullName>
                </value>
                <value>
                    <fullName>KM02-St Louis</fullName>
                </value>
                <value>
                    <fullName>KM03-Southern MO</fullName>
                </value>
                <value>
                    <fullName>KM04-KC East</fullName>
                </value>
                <value>
                    <fullName>KM05-KC West</fullName>
                </value>
                <value>
                    <fullName>KM06-Central KS</fullName>
                </value>
                <value>
                    <fullName>LA01</fullName>
                </value>
                <value>
                    <fullName>LA02</fullName>
                </value>
                <value>
                    <fullName>LA03</fullName>
                </value>
                <value>
                    <fullName>LA04</fullName>
                </value>
                <value>
                    <fullName>LA05</fullName>
                </value>
                <value>
                    <fullName>LA06</fullName>
                </value>
                <value>
                    <fullName>LA07</fullName>
                </value>
                <value>
                    <fullName>LA08</fullName>
                </value>
                <value>
                    <fullName>MS01</fullName>
                </value>
                <value>
                    <fullName>MS02</fullName>
                </value>
                <value>
                    <fullName>MS03</fullName>
                </value>
                <value>
                    <fullName>MS04</fullName>
                </value>
                <value>
                    <fullName>MS05</fullName>
                </value>
                <value>
                    <fullName>MS06</fullName>
                </value>
                <value>
                    <fullName>MT01-Northern CO-WY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_districts3__c</fullName>
        <inlineHelpText>This field will capture which District’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Districts 3</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SN02</fullName>
                </value>
                <value>
                    <fullName>SN03</fullName>
                </value>
                <value>
                    <fullName>SN04</fullName>
                </value>
                <value>
                    <fullName>SN05</fullName>
                </value>
                <value>
                    <fullName>SN06</fullName>
                </value>
                <value>
                    <fullName>ST01-San Antonio</fullName>
                </value>
                <value>
                    <fullName>ST02-RGV</fullName>
                </value>
                <value>
                    <fullName>ST03-Houston Southwest</fullName>
                </value>
                <value>
                    <fullName>ST04-Houston West</fullName>
                </value>
                <value>
                    <fullName>ST05-Houston North</fullName>
                </value>
                <value>
                    <fullName>ST06-Houston East</fullName>
                </value>
                <value>
                    <fullName>ST07-Houston Southeast</fullName>
                </value>
                <value>
                    <fullName>ST08-Houston Central</fullName>
                </value>
                <value>
                    <fullName>TA01-East Texas</fullName>
                </value>
                <value>
                    <fullName>TA02-South Oklahoma</fullName>
                </value>
                <value>
                    <fullName>TA03-North Oklahoma</fullName>
                </value>
                <value>
                    <fullName>TA04-West Arkansas</fullName>
                </value>
                <value>
                    <fullName>TA05-East Arkansas</fullName>
                </value>
                <value>
                    <fullName>TA06-South Arkansas</fullName>
                </value>
                <value>
                    <fullName>TCW01-Charlotte North</fullName>
                </value>
                <value>
                    <fullName>TCW02-Charlotte South</fullName>
                </value>
                <value>
                    <fullName>TCW03-Nashville</fullName>
                </value>
                <value>
                    <fullName>TCW04-Chattanooga</fullName>
                </value>
                <value>
                    <fullName>TCW05-Knoxville</fullName>
                </value>
                <value>
                    <fullName>TCW06-Tri-Cities</fullName>
                </value>
                <value>
                    <fullName>TCW07-Upstate SC</fullName>
                </value>
                <value>
                    <fullName>TCW08-Western NC</fullName>
                </value>
                <value>
                    <fullName>UP01</fullName>
                </value>
                <value>
                    <fullName>UP02</fullName>
                </value>
                <value>
                    <fullName>UP03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_markets__c</fullName>
        <inlineHelpText>This field will capture which Market’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Markets</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>HQ-Telesales</fullName>
                </value>
                <value>
                    <fullName>North Central</fullName>
                </value>
                <value>
                    <fullName>North East</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>South East</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segmentation</label>
    <nameField>
        <displayFormat>SEG-{000000}</displayFormat>
        <label>Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_segmentationTriggerHandlerTest.cls
/**
*@name          CCPM_segmentationTriggerHandlerTest 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          Apr 17, 2018
*@description   This is a Test class for
*@Class         CCPM_segmentationTriggerHandlerTest
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    XX/XX/2017   Initial Implementation.
*/

@isTest
private class CCPM_segmentationTriggerHandlerTest {
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  This is the constructor
	@param        N/A
	@return       Void(None)
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Chrissen Joseph (Deloitte)       04/19/2018   Initial Implementation.
	**/ 
    //This method is to cover the Before Insert and Before Update Scenarios
    static testMethod void myUnitTest1() { 
        Test.startTest();
        Campaign ca = new Campaign(Name='TestCampaign',
                                   CCPM_leadCustomerType__c = 'Customer',
                                   CCPM_eventStartDate__c = '2018-09-09 02:02:02',
                                   CCPM_eventLabel__c = 'testlabel',
                                   IsActive = true,
                                   recordtypeid = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Event Type').getRecordTypeId());
        insert ca;
        CCPM_segmentation__c seg1 = new CCPM_segmentation__c	(CCPM_isActive__c = true, 
                                                             CCPM_campaign__c = ca.id, 
                                                             CCPM_districts1__c = 'AK01',
                                                             CCPM_districts2__c = 'GLW05-South Chicago-NW IN',
                                                             CCPM_districts3__c = 'ST03-Houston Southwest',
                                                             CCPM_markets__c = 'Great Lakes',
                                                             CCPM_territories__c = 'Alaska',
                                                             CCPM_channels__c = 'Retail');
        insert seg1;
        CCPM_segmentation__c seg2 = new CCPM_segmentation__c	(CCPM_isActive__c = True, 
                                                             CCPM_campaign__c = ca.id, 
                                                             CCPM_districts1__c = 'CC01',
                                                             CCPM_districts2__c = 'HI01',
                                                             CCPM_districts3__c = 'SN02',
                                                             CCPM_markets__c = 'HQ-Telesales',
                                                             CCPM_territories__c = 'Carolinas East',
                                                             CCPM_channels__c = 'Retail');
        
        insert seg2;
        seg1.CCPM_districts1__c = 'CAR01-Coastal Carolinas';
        seg1.CCPM_districts2__c = 'HQ-Telesales';
        seg1.CCPM_districts3__c = 'SN03';
        update seg1;
        Test.stopTest();
    }
    //This method is to cover the addError scenarios in Insert and Update  
    static testMethod void myUnitTest12() { 
        Test.startTest();
        Campaign ca = new Campaign(Name='TestCampaign',
                                   CCPM_leadCustomerType__c = 'Customer',
                                   CCPM_eventStartDate__c = '2018-09-09 02:02:02',
                                   CCPM_eventLabel__c = 'testlabel',
                                   IsActive = true,
                                   recordtypeid = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Event Type').getRecordTypeId());
        insert ca;
        CCPM_segmentation__c seg1 = new CCPM_segmentation__c	(CCPM_isActive__c = true, 
                                                             CCPM_campaign__c = ca.id, 
                                                             CCPM_districts1__c = 'AK01',
                                                             CCPM_districts2__c = 'GLW05-South Chicago-NW IN',
                                                             CCPM_districts3__c = 'ST03-Houston Southwest',
                                                             CCPM_markets__c = 'Great Lakes',
                                                             CCPM_territories__c = 'Alaska',
                                                             CCPM_channels__c = 'Retail');
      insert seg1;
      Test.stopTest();
    }
    //This method is to cover the BeforeDelete class method
    static testMethod void myUnitTest2() {   
        Test.startTest();
        CCPM_segmentation__c seg1 = new CCPM_segmentation__c(CCPM_isActive__c = true, 
                                                             CCPM_districts1__c = 'AK01',
                                                             CCPM_markets__c = 'Great Lakes',
                                                             CCPM_territories__c = 'Alaska',
                                                             CCPM_channels__c = 'Retail');
        insert seg1;
        Map<id, CCPM_segmentation__c> segMap = new Map<id, CCPM_segmentation__c> ([select id from CCPM_segmentation__c where id =:seg1.id]);
        Map<id, sObject> mapOld = (Map<id, sObject>)segMap;
        CCPM_segmentationTriggerHandler segHandler = new CCPM_segmentationTriggerHandler();
        segHandler.BeforeDelete(mapOld);
        Test.stopTest();
    }
    //This method is to cover the AfterUpdate class method
    static testMethod void myUnitTest3() {   
        Test.startTest();
        CCPM_segmentation__c seg1 = new CCPM_segmentation__c(CCPM_isActive__c = true, 
                                                             CCPM_districts1__c = 'AK01',
                                                             CCPM_markets__c = 'Great Lakes',
                                                             CCPM_territories__c = 'Alaska',
                                                             CCPM_channels__c = 'Retail');
        insert seg1;
        Map<id, CCPM_segmentation__c> segMap = new Map<id, CCPM_segmentation__c> ([select id from CCPM_segmentation__c where id =:seg1.id]);
        Map<id, sObject> mapOld = (Map<id, sObject>)segMap;
        CCPM_segmentationTriggerHandler segHandler = new CCPM_segmentationTriggerHandler();
        segHandler.AfterUpdate(mapOld,mapOld);
        Test.stopTest();
    }
    //This method is to cover the AfterDelete class method
    static testMethod void myUnitTest4() {   
        Test.startTest();
        CCPM_segmentation__c seg1 = new CCPM_segmentation__c(CCPM_isActive__c = true, 
                                                             CCPM_districts1__c = 'AK01',
                                                             CCPM_markets__c = 'Great Lakes',
                                                             CCPM_territories__c = 'Alaska',
                                                             CCPM_channels__c = 'Retail');
        insert seg1;
        Map<id, CCPM_segmentation__c> segMap = new Map<id, CCPM_segmentation__c> ([select id from CCPM_segmentation__c where id =:seg1.id]);
        Map<id, sObject> mapOld = (Map<id, sObject>)segMap;
        CCPM_segmentationTriggerHandler segHandler = new CCPM_segmentationTriggerHandler();
        segHandler.AfterDelete(mapOld);
        Test.stopTest();
    }
    //This method is to cover the AfterUndelete class method
    static testMethod void myUnitTest5() {   
        Test.startTest();
        CCPM_segmentation__c seg1 = new CCPM_segmentation__c(CCPM_isActive__c = true, 
                                                             CCPM_districts1__c = 'AK01',
                                                             CCPM_markets__c = 'Great Lakes',
                                                             CCPM_territories__c = 'Alaska',
                                                             CCPM_channels__c = 'Retail');
        insert seg1;
        Map<id, CCPM_segmentation__c> segMap = new Map<id, CCPM_segmentation__c> ([select id from CCPM_segmentation__c where id =:seg1.id]);
        Map<id, sObject> mapOld = (Map<id, sObject>)segMap;
        CCPM_segmentationTriggerHandler segHandler = new CCPM_segmentationTriggerHandler();
        segHandler.AfterUndelete(mapOld);
        Test.stopTest();
    }
    
}