VZDEV/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CCPM_eventEndDate__c</fullName>
        <inlineHelpText>This field is the text value of the field &apos;Event End&apos;. Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event End Date</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventLabel__c</fullName>
        <label>Event Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventOrder__c</fullName>
        <label>Event Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_eventSMSFollowUpEndDate__c</fullName>
        <inlineHelpText>Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event SMS Follow Up End Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventSMSFollowUpStartDate__c</fullName>
        <inlineHelpText>Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event SMS Follow Up Start Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventStartDate__c</fullName>
        <inlineHelpText>This field is the text value of the field &apos;Event Start Date&apos; . Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event Start Date</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_leadCustomerType__c</fullName>
        <label>Lead Customer Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_uniqueName__c</fullName>
        <label>Campaign Name</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_segmentation__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field will capture which Territories’ Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Segmentations</relationshipLabel>
        <relationshipName>CCPM_segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_channels__c</fullName>
        <inlineHelpText>This field will capture a value if the Event type should be available based on the Channel nation-wide when Market, District and Territory are left blank.</inlineHelpText>
        <label>Channels</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Telesales</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_markets__c</fullName>
        <inlineHelpText>This field will capture which Market’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Markets</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>HQ-Telesales</fullName>
                </value>
                <value>
                    <fullName>North Central</fullName>
                </value>
                <value>
                    <fullName>North East</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>South East</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_territories__c</fullName>
        <inlineHelpText>This field will capture which Territories’ Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Territories</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Carolinas East</fullName>
                </value>
                <value>
                    <fullName>Central California</fullName>
                </value>
                <value>
                    <fullName>Central Pacific</fullName>
                </value>
                <value>
                    <fullName>Desert</fullName>
                </value>
                <value>
                    <fullName>FL Northwest</fullName>
                </value>
                <value>
                    <fullName>FL Southeast</fullName>
                </value>
                <value>
                    <fullName>GA/AL North</fullName>
                </value>
                <value>
                    <fullName>GA/AL South</fullName>
                </value>
                <value>
                    <fullName>Great Lakes Central</fullName>
                </value>
                <value>
                    <fullName>Great Lakes East</fullName>
                </value>
                <value>
                    <fullName>Great Lakes North</fullName>
                </value>
                <value>
                    <fullName>Great Lakes South</fullName>
                </value>
                <value>
                    <fullName>Great Lakes West</fullName>
                </value>
                <value>
                    <fullName>Great Plains North</fullName>
                </value>
                <value>
                    <fullName>Great Plains South</fullName>
                </value>
                <value>
                    <fullName>Greater LA</fullName>
                </value>
                <value>
                    <fullName>Gulf</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>HQ-Telesales</fullName>
                </value>
                <value>
                    <fullName>Kansas/Missouri</fullName>
                </value>
                <value>
                    <fullName>Mid-State</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>New Jersey North</fullName>
                </value>
                <value>
                    <fullName>New York City</fullName>
                </value>
                <value>
                    <fullName>North Texas</fullName>
                </value>
                <value>
                    <fullName>Northern New England</fullName>
                </value>
                <value>
                    <fullName>Northwest</fullName>
                </value>
                <value>
                    <fullName>NY East</fullName>
                </value>
                <value>
                    <fullName>Philadelphia Tri-State</fullName>
                </value>
                <value>
                    <fullName>Southern California</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segmentation</label>
    <nameField>
        <displayFormat>SEG-{000000}</displayFormat>
        <label>Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_smsTemplate__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>CCPM_smsTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_segmentation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segmentation</label>
        <referenceTo>CCPM_segmentation__c</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>CCPM_smsTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>SMSTEMP-{000000}</displayFormat>
        <label>SMS Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag  to indicate if store is active or not</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_district__c</fullName>
        <description>The district store belongs to</description>
        <label>District</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_market__c</fullName>
        <description>The market store belongs to</description>
        <label>Market</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_territory__c</fullName>
        <description>The territory store belongs to</description>
        <label>Territory</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if employee is active for that store</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_Store__c</fullName>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Store Employees</relationshipLabel>
        <relationshipName>Store_Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_eventSMSUtilTest.cls
@isTest
public class CCPM_eventSMSUtilTest {
	
    static String eventTypeRec = schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Event Type').getRecordTypeId();
    static testmethod void testgetMapLeadTypeMapEvntLstSmsTemp() {
        
        list<user> lstUser = ccpm_testdatautil.createTestUsers('CCPM Sales Rep', 1);
        insert lstUser;
        
        list<ccpm_Store__c> lstStore = ccpm_testDataUtil.createStore(1);
        lststore[0].ccpm_market__c = 'Great Lakes';
        lstStore[0].CCPM_territory__c = 'Southern California';
        lstStore[0].ccpm_district__c = 'DS04-Scottsdale';
        insert lstStore;
        
        list<ccpm_storeEmployee__c> lstStEmp = ccpm_testDataUtil.createStoreEmployee(1, lstStore[0].id, lstUser[0].id, 'Store Manager');
        insert lstStEmp;
        
        campaign objCmp = new campaign();
        objCmp.recordTypeId = eventTypeRec;
        objCmp.CCPM_uniqueName__c = 'SMB';
        objCmp.CCPM_eventStartDate__c = '2016-02-02 00:00:00';
        objCmp.CCPM_eventEndDate__c = '2099-12-12 00:00:00';
        objCmp.CCPM_eventSMSFollowUpEndDate__c = '2099-12-12 00:00:00';
        objCmp.CCPM_eventSMSFollowUpStartDate__c = '2016-02-02 00:00:00';
        objCmp.IsActive = true;
        objCmp.Name = 'SMB';
        objCmp.CCPM_eventLabel__c = 'SMB';
        objCmp.CCPM_eventOrder__c = 1;
        objCmp.CCPM_leadCustomerType__c = 'Customer;Prospect';
        insert objCmp;
        
        ccpm_segmentation__c objSeg = new ccpm_segmentation__c();
        objSeg.CCPM_campaign__c = objCmp.Id;
        objSeg.CCPM_channels__c = 'Retail;Telesales';
        objSeg.CCPM_isActive__c = true;
        objSeg.CCPM_markets__c = 'Great Lakes;North Central;North East;Pacific;South Central;South East';
        objSeg.CCPM_territories__c = Label.ccpm_territories;
        objSeg.CCPM_districts1__c = Label.ccpm_districts1;
        objSeg.CCPM_districts2__c = Label.ccpm_districts2;
        objSeg.CCPM_districts3__c = Label.ccpm_districts3;
        insert objSeg;
        
        ccpm_smsTemplate__c objTemp = new ccpm_smsTemplate__c();
        objTemp.CCPM_isActive__c = true;
        objTemp.CCPM_segmentation__c = objSeg.Id;
        objTemp.CCPM_messageType__c = 'NewProspectSMS1';
        objTemp.CCPM_eventMessageStartDate__c='2016-02-02 00:00:00';
        objTemp.CCPM_eventMessageEndDate__c = '2099-12-12 00:00:00';
        objTemp.CCPM_customerMessage__c = 'Hello';
        objTemp.CCPM_prospectMessage__c = 'Hello';
        insert objTemp;
        test.starttest();
        map<String,map<String,list<ccpm_SMSTemplate__c>>> retMap = ccpm_eventSMSUtil.getMapLeadTypeMapEvntLstSmsTemp(lstuser[0].id);
        system.assert(retMap != null);
        test.stopTest();
    }
}