VZDEV/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CCPM_eventEndDate__c</fullName>
        <inlineHelpText>This field is the text value of the field &apos;Event End&apos;. Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event End Date</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventLabel__c</fullName>
        <label>Event Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventSMSFollowUpEndDate__c</fullName>
        <inlineHelpText>Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event SMS Follow Up End Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventSMSFollowUpStartDate__c</fullName>
        <inlineHelpText>Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event SMS Follow Up Start Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventStartDate__c</fullName>
        <inlineHelpText>This field is the text value of the field &apos;Event Start Date&apos; . Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event Start Date</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_leadCustomerType__c</fullName>
        <label>Lead Customer Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_segmentation__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field will capture which Territories’ Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Segmentations</relationshipLabel>
        <relationshipName>CCPM_segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_channels__c</fullName>
        <inlineHelpText>This field will capture a value if the Event type should be available based on the Channel nation-wide when Market, District and Territory are left blank.</inlineHelpText>
        <label>Channels</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Telesales</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_markets__c</fullName>
        <inlineHelpText>This field will capture which Market’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Markets</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>HQ-Telesales</fullName>
                </value>
                <value>
                    <fullName>North Central</fullName>
                </value>
                <value>
                    <fullName>North East</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>South East</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segmentation</label>
    <nameField>
        <displayFormat>SEG-{000000}</displayFormat>
        <label>Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_smsTemplate__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>CCPM_smsTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_customerMessage__c</fullName>
        <inlineHelpText>This field will be used to store the Event SMS to sent to the Customers</inlineHelpText>
        <label>Customer Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_endDate__c</fullName>
        <inlineHelpText>This field is the text value of the field SMS Follow up End Date</inlineHelpText>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_eventCampaignId__c</fullName>
        <formula>CCPM_segmentation__r.CCPM_campaign__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Campaign Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventMessageEndDate__c</fullName>
        <inlineHelpText>This field is the text value of the field SMS Event End Date. Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event Message End Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventMessageStartDate__c</fullName>
        <inlineHelpText>This field is the text value of the field SMS Event Start Date. Please enter the date in &quot;YYYY-MM-DD HH:MM:SS&quot; format.</inlineHelpText>
        <label>Event Message Start Date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_prospectMessage__c</fullName>
        <inlineHelpText>This field will be used to store the Event SMS to sent to the Prospects.</inlineHelpText>
        <label>Prospect Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_segmentation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Segmentation</label>
        <referenceTo>CCPM_segmentation__c</referenceTo>
        <relationshipLabel>SMS Templates</relationshipLabel>
        <relationshipName>CCPM_smsTemplates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_startDate__c</fullName>
        <inlineHelpText>This field is the text value of the field SMS Follow up Start Date</inlineHelpText>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>SMSTEMP-{000000}</displayFormat>
        <label>SMS Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag  to indicate if store is active or not</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_TimeZone__c</fullName>
        <description>TimeZones of the store to identify business hours for sending outbound communication</description>
        <label>TimeZone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EST</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>CST</fullName>
                </value>
                <value>
                    <fullName>MST</fullName>
                </value>
                <value>
                    <fullName>PST</fullName>
                </value>
                <value>
                    <fullName>HAST</fullName>
                </value>
                <value>
                    <fullName>AKST</fullName>
                </value>
                <value>
                    <fullName>Alaskan</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Hawaiian</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_district__c</fullName>
        <description>The district store belongs to</description>
        <label>District</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_market__c</fullName>
        <description>The market store belongs to</description>
        <label>Market</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_source__c</fullName>
        <description>This field contains source of store which markets store belongs  i.e Retail or Telesales</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_territory__c</fullName>
        <description>The territory store belongs to</description>
        <label>Territory</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if employee is active for that store</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_Store__c</fullName>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Store Employees</relationshipLabel>
        <relationshipName>Store_Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_eventSMSUtil.cls
/**
*@name          CCPM_eventSMSUtil 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          03/10/2018
*@description   This is a class For Event Framework. 
*@Class         CCPM_eventSMSUtil
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    03/10/2018   Initial Implementation.
*/
public class CCPM_eventSMSUtil {
    
    /**
@author        Bharath Ammanamanchi(Deloitte)
@description   Method to return Map of Lead Type and Map of event types and List of Sms templates to be displayed on the UI
				This method is put here as this is needed only for UI and webservice.
@param         String
@return        Map<String, Map<String, List<CCPM_smsTemplate__c>>>
*/    
    public static Map<String, Map<String, List<CCPM_smsTemplate__c>>> getMapLeadTypeMapEvntLstSmsTemp(string strUserId){
        Map<String, Map<String, List<CCPM_smsTemplate__c>>> mapLeadTypeEvntTypeLstSmsTempMap = new Map<String, Map<String, List<CCPM_smsTemplate__c>>>();
        String strTimeZone = UserInfo.getTimeZone()+'';
        
        String strSegQuery = 'Select id, CCPM_campaign__r.Name, CCPM_campaign__r.CCPM_eventStartDate__c, CCPM_campaign__r.CCPM_eventEndDate__c,'+
            'CCPM_campaign__r.CCPM_eventSMSFollowUpStartDate__c, CCPM_campaign__r.CCPM_eventSMSFollowUpEndDate__c, CCPM_campaign__r.CCPM_leadCustomerType__c, CCPM_campaign__r.CCPM_eventLabel__c,'+
            '(Select id, CCPM_eventMessageStartDate__c, CCPM_eventMessageEndDate__c, CCPM_startDate__c, CCPM_endDate__c, CCPM_customerMessage__c,'+ 
            '	CCPM_eventCampaignId__c, CCPM_prospectMessage__c  FROM CCPM_smsTemplates__r Where CCPM_isActive__c = true)'+
            'From CCPM_segmentation__c Where CCPM_isActive__c = true AND CCPM_campaign__r.IsActive=true ';
        String strChannel = '';
        String strMarket = '';
        String strTerritory = '';
        String strDisctict = '';
        
        if(String.isNotBlank(strUserId)){
            CCPM_storeEmployee__c objrStoreEmpRec = CCPM_utility.getUserStoreEmpRec(strUserId);
            if(objrStoreEmpRec != null){
                if(String.isNOtBlank(objrStoreEmpRec.CCPM_Store__r.CCPM_TimeZone__c)){
                    strTimeZone = CCPM_utility.mapBusinessHoursNameRec.get(objrStoreEmpRec.CCPM_Store__r.CCPM_TimeZone__c).TimeZoneSidkey;
                }
                
                strChannel = (objrStoreEmpRec.CCPM_Store__r.CCPM_source__c == null || objrStoreEmpRec.CCPM_Store__r.CCPM_source__c == 'Retail') ? 'Retail' : objrStoreEmpRec.CCPM_Store__r.CCPM_source__c;
                strMarket = objrStoreEmpRec.CCPM_Store__r.CCPM_market__c;
                strTerritory = objrStoreEmpRec.CCPM_Store__r.CCPM_territory__c;
                strDisctict = objrStoreEmpRec.CCPM_Store__r.CCPM_district__c;
                strSegQuery = strSegQuery + 'AND CCPM_channels__c includes (:strChannel) AND CCPM_markets__c includes (:strMarket) AND CCPM_territories__c includes (:strTerritory) AND '+
                    '(CCPM_districts1__c includes (:strDisctict) OR CCPM_districts2__c includes (:strDisctict) OR CCPM_districts3__c includes (:strDisctict)) ';
            }
        }
        strSegQuery = strSegQuery+'Order By CCPM_campaign__r.CCPM_eventOrder__c ASC';
        List<CCPM_segmentation__c> lstSeg= Database.query(strSegQuery);
        
        if(CCPM_Collection.isNotNullEmpty(lstSeg)){
            for(CCPM_segmentation__c objseg: lstSeg){        
                DateTime dtmEvntStartDate = objseg.CCPM_campaign__r.CCPM_eventStartDate__c != null ? CCPM_utility.getDtTimeForTimeZone(objseg.CCPM_campaign__r.CCPM_eventStartDate__c, strTimeZone) : null;
                DateTime dtmEvntEndDate = objseg.CCPM_campaign__r.CCPM_eventEndDate__c != null ? CCPM_utility.getDtTimeForTimeZone(objseg.CCPM_campaign__r.CCPM_eventEndDate__c, strTimeZone) : null;
                Datetime datTSysNowForEvent = CCPM_utility.datTSysNowForEvent;
                if(dtmEvntStartDate != null && datTSysNowForEvent >= dtmEvntStartDate && (dtmEvntEndDate == null || (dtmEvntEndDate != null && datTSysNowForEvent <= dtmEvntEndDate))){
                    if(CCPM_Collection.isNotNullEmpty(objseg.CCPM_smsTemplates__r)){
                        for(CCPM_smsTemplate__c objSMSTemp : objseg.CCPM_smsTemplates__r){
                            if(objSMSTemp.CCPM_eventMessageStartDate__c != null){
                                objSMSTemp.CCPM_startDate__c = CCPM_utility.getDtTimeForTimeZone(objSMSTemp.CCPM_eventMessageStartDate__c,strTimeZone);
                            }
                            if(objSMSTemp.CCPM_eventMessageEndDate__c != null){
                                objSMSTemp.CCPM_endDate__c = CCPM_utility.getDtTimeForTimeZone(objSMSTemp.CCPM_eventMessageEndDate__c,strTimeZone);
                            }
                        }
                    }
                   
                    if(String.isNotBlank(objseg.CCPM_campaign__r.CCPM_leadCustomerType__c)){
                        for(String strLeadType : CCPM_utility.getSetFromString(objseg.CCPM_campaign__r.CCPM_leadCustomerType__c, ';')){
                            strLeadType = strLeadType.trim();
                            String strEventName = objseg.CCPM_campaign__r.CCPM_eventLabel__c+'_'+objseg.CCPM_campaign__r.Name;
                            if(mapLeadTypeEvntTypeLstSmsTempMap.containsKey(strLeadType)){
                                mapLeadTypeEvntTypeLstSmsTempMap.get(strLeadType).put(strEventName, objseg.CCPM_smsTemplates__r);
                            }
                            else{
                                mapLeadTypeEvntTypeLstSmsTempMap.put(strLeadType, new Map<String, List<CCPM_smsTemplate__c>>{strEventName =>objseg.CCPM_smsTemplates__r });
                            }
                        }   
                    }
                }                
            }
        }
        
        return mapLeadTypeEvntTypeLstSmsTempMap;
    }  
}