VZDEV/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <fields>
        <fullName>CCPM_MessageStatus__c</fullName>
        <description>Refers to the status of the Message sent based on response code.</description>
        <inlineHelpText>Refers to the status of the Message sent based on response code.</inlineHelpText>
        <label>Message Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Resend Failed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_communicationDirection__c</fullName>
        <description>Refers tot the communication Direction.</description>
        <inlineHelpText>Refers tot the communication Direction.</inlineHelpText>
        <label>Communication Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <description>Lead type from lead record</description>
        <formula>TEXT(CCPM_leadRecord__r.CCPM_leadType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_messageType__c</fullName>
        <description>Indicates the type of SMS being sent.</description>
        <inlineHelpText>Indicates the type of SMS being sent.</inlineHelpText>
        <label>Message Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_message__c</fullName>
        <description>Message body to be sent.</description>
        <inlineHelpText>Message body to be sent.</inlineHelpText>
        <label>Message</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_requestID__c</fullName>
        <label>RequestID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_responseCode__c</fullName>
        <description>Response codes recorded for each API call made</description>
        <label>Response Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_responseMessage__c</fullName>
        <description>Captures the Response Message for the Heywire API callout made.</description>
        <inlineHelpText>Captures the Response Message for the Heywire API callout made.</inlineHelpText>
        <label>Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_smssentactualtime__c</fullName>
        <description>This field stores the time the SMS was actually sent out from Heroku</description>
        <inlineHelpText>This field stores the time the SMS was actually sent out from Heroku</inlineHelpText>
        <label>SMS Sent Actual Time</label>
        <type>DateTime</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Existing customer for whom abandoned cart has been created</description>
        <label>Account Holder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_followUpSMSDate__c</fullName>
        <description>Records date/time when follow up SMS was sent</description>
        <label>Follow-Up SMS Sent Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_initialSMSSentDateTime__c</fullName>
        <description>Records date/time when initial SMS was sent</description>
        <label>Initial SMS Sent Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_isInitialSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</description>
        <inlineHelpText>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Initial SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isManualLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if Prospect is Embedded Account</description>
        <inlineHelpText>if check Prospect is Embedded Account</inlineHelpText>
        <label>Manual Lead?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_lastInteraction__c</fullName>
        <description>Date/Time being recorded for last interaction between the customer and Heywire process in salesforce</description>
        <label>Last Interaction Date/TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_prospectSMSSentDate__c</fullName>
        <label>Event Date/Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_HerokuWebsServicev1Test.cls
/**
*@name          CCPM_HerokuWebsServicev1Test
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          01/15/2018
@Description    Test Class for CCPM_HerokuWebsServicev1 
@Endpoint       {Salesforce Base URL}/services/apexrest/api/v1/coresync/
Modification    Log:
------------------------------------------------------------------------------------
Developer                                   Date                   Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)          01/15/2018              Original Version
*/


@isTest
public class CCPM_HerokuWebsServicev1Test {
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   This method is used to creatCart
*@return :      Lead 
*/   
    public static Lead createCustomerCart(String leadtype,String lastName, String Status, String MTN, String numberOfLinesInterestedIn,Id accountID, String storeID)
    {
        Lead objLead                    =   new Lead();      
        
        objLead.CCPM_mobileNumber__c    =   MTN;
        objLead.LastName                =   lastName;
        objLead.Company                 =   numberOfLinesInterestedIn;
        objLead.CCPM_SMSLegalOptIn__c = true;
        objLead.Status                  =   Status;
        objLead.CCPM_leadtype__c        =   leadtype;
        
     /*   if (!leadType.contains('Prospect'))   {
            objLead.CCPM_Account__c     =   accountID;
        }
        
        if (leadType == 'Customer Campaign')  {
            objLead.LeadSource              = 'CRM';
        }
        
        if (leadType.contains('Manual'))    {
            objLead.CCPM_isManualLead__c    = true;
        }
        
        if (leadType == 'Customer Campaign' || 
            ((leadType == 'Telesales'       || 
            leadType.contains('Manual'))&& leadType.contains('Customer')))   {
                
                objLead.RecordTypeId            =   Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Customer Cart').getRecordTypeId();
                
            } else {
                
                objLead.RecordTypeId            =   Schema.SObjectType.Lead.getRecordTypeInfosByName().get(recordType).getRecordTypeId();
            } */
        
        return objLead;   
    }
    
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   This method makes the call the Rest Service
*@return :      None 
*/
    
    public static testMethod void testPostMethod()
    {   
        Test.startTest();
        RestRequest request = new RestRequest();
        CCPM_HerokuWebsServicev1.responseWrapper resWrapper = new CCPM_HerokuWebsServicev1.responseWrapper();
        Lead objLead = createCustomerCart('Customer Campaign','TestLastname','Eligible','3213187287','2',null,null);
        insert objLead;
        CCPM_smsmessage__c sms = new ccpm_smsmessage__c();
        insert sms;
        
        JSONGenerator JSONgen = createGenerateJSONRequest(objLead.id,sms.Id);
        String myString = JSONgen.getAsString();
        System.debug(myString);
        Blob myBlob = Blob.valueOf(myString);
        request.requestBody = myBlob;
        request.requestUri ='/services/apexrest/api/v1/coresync/';
        request.httpMethod = 'POST';
        RestContext.request = request;
        resWrapper = CCPM_HerokuWebsServicev1.updateFieldsOnHerokuRequest();
        System.debug('Response->'+CCPM_HerokuWebsServicev1.updateFieldsOnHerokuRequest()+resWrapper.HTTPstatus);
        System.assertEquals('200', resWrapper.HTTPstatus);
        Test.stopTest();
    }
    
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   This method creates the JSON Request
*@return :      JSONGenerator 
*/
    public static JSONGenerator createGenerateJSONRequest(id LeadID,id SMSID) {
        JSONGenerator JSONgen = JSON.createGenerator(true);
        JSONgen.writeStartObject();
        JSONgen.writeFieldName('lead');
        JSONgen.writeStartObject();
        JSONgen.writeStringField('Id',LeadID );
        JSONgen.writeBooleanField('CCPM_isInitialSMSSent__c', True);
        JSONgen.writeStringField('CCPM_initialSMSSentDateTime__c', '2018-01-01 00:00:00');
        JSONgen.writeStringField('CCPM_lastInteraction__c', '2018-01-01 00:00:00');
        JSONgen.writeStringField('CCPM_followUpSMSDate__c', '2018-01-01 00:00:00');
        JSONgen.writeStringField('CCPM_prospectSMSSentDate__c', '2018-01-01 00:00:00');
        JSONgen.writeStringField('CCPM_prospectSMSSentDate__c', '2018-01-01 00:00:00');
        JSONgen.writeBooleanField('CCPM_isInitialSMSSent__c', True);
        JSONgen.writeStringField('status', 'Contacted');
        JSONgen.writeEndObject();
        
        JSONgen.writeFieldName('sms message');
        JSONgen.writeStartObject();
        JSONgen.writeStringField('Id',SMSID );
        JSONgen.writeStringField('CCPM_messageType__c', 'TestType');
        JSONgen.writeStringField('CCPM_smssentactualtime__c', '2018-01-01 00:00:00');
        JSONgen.writeStringField('CCPM_message__c', 'Hello');
        JSONgen.writeStringField('CCPM_requestID__c', '213123^123123');
        JSONgen.writeStringField('CCPM_responseMessage__c', 'No Content');
        JSONgen.writeStringField('CCPM_prospectSMSSentDate__c', '2018-01-01 00:00:00');
        JSONgen.writeStringField('CCPM_responseCode__c', '204');
        JSONgen.writeStringField('CCPM_messagestatus__c', 'Queued');
        JSONgen.writeEndObject();
        
        JSONgen.writeFieldName('TaskPart1');
        JSONgen.writeStartObject();
        JSONgen.writeStringField('description','testDescription' );
        JSONgen.writeStringField('CCPM_communicationDirection__c', 'Inbound');
        JSONgen.writeStringField('CCPM_SMSMessageType__c', 'Test type');
        JSONgen.writeStringField('Priority', 'Normal');
        JSONgen.writeStringField('Status', 'Completed');
        JSONgen.writeStringField('Subject', 'TextMessageSent');
        JSONgen.writeStringField('Whoid',LeadID);
        JSONgen.writeEndObject();
        
        JSONgen.writeFieldName('TaskPart2');
        JSONgen.writeStartObject();
        JSONgen.writeStringField('description','testDescription' );
        JSONgen.writeStringField('CCPM_communicationDirection__c', 'Inbound');
        JSONgen.writeStringField('CCPM_SMSMessageType__c', 'Test type');
        JSONgen.writeStringField('Priority', 'Normal');
        JSONgen.writeStringField('Status', 'Completed');
        JSONgen.writeStringField('Subject', 'TextMessageSent');
        JSONgen.writeStringField('Whoid',LeadID);
        JSONgen.writeEndObject();
        
        JSONgen.writeEndObject();
        return JSONgen;
        
    }
    
    
    
    
}