VZDEV/src/objects/CCPM_UIComponentSetting__mdt.object
<CustomObject>
    <description>Parameters required to be set for UI components Lightning.</description>
    <fields>
        <fullName>CCPM_orderByField__c</fullName>
        <description>Orders by a specific Field.</description>
        <inlineHelpText>Orders by a specific Field.</inlineHelpText>
        <label>Order By Field</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_order__c</fullName>
        <description>Metadata property to set the order by which the Query should sort Data</description>
        <inlineHelpText>Metadata property to set the order by which the Query should sort Data</inlineHelpText>
        <label>Order</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASC</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>DESC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_recordLimit__c</fullName>
        <label>Record Limit</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UI Component Setting</label>
    <pluralLabel>UI Component Settings</pluralLabel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSFollowUpDate__c</fullName>
        <inlineHelpText>The date &amp; time for the SMS to be scheduled to be sent</inlineHelpText>
        <label>SMS Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_Type__c</fullName>
        <description>Type</description>
        <formula>IF(OR(AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = true),ISPICKVAL(CCPM_leadType__c,&apos;Customer SFDC Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales SFDC Manual&apos;)),&apos;Manual Lead&apos;, 
IF(OR(CONTAINS(TEXT(LeadSource), &quot;CRM&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Campaign&apos;)),&apos;Campaign Lead&apos;, 
IF(OR(CONTAINS(TEXT(CCPM_leadType__c),&quot;Customer Abandoned Cart&quot;), AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = false)),&apos;Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Abandoned Visit&apos;),&apos;Abandoned Visit Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Quotes&apos;),&apos;Quote Lead&apos;, 
IF(OR(ISPICKVAL(CCPM_leadType__c,&apos;Prospect SFDC Manual&apos;),CONTAINS(TEXT(CCPM_leadType__c),&quot;Prospect Abandoned Cart&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Prospect Telesales SFDC Manual&apos;), RecordType.Name = &apos;Prospect Cart&apos;, RecordType.Name = &apos;Prospect&apos;),&apos;Prospect&apos;, 
&apos;&apos; ))))))</formula>
        <inlineHelpText>Type of lead or prospect based on how it entered Salesforce</inlineHelpText>
        <label>Current Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventType__c</fullName>
        <inlineHelpText>The Conversation Topic that requires an SMS follow up to be sent.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samsung GS9 BOGO</fullName>
                </value>
                <value>
                    <fullName>TMP OE - Q2 2018</fullName>
                </value>
                <value>
                    <fullName>Add a Line</fullName>
                </value>
                <value>
                    <fullName>Confirming with Family First</fullName>
                </value>
                <value>
                    <fullName>Connected Device</fullName>
                </value>
                <value>
                    <fullName>Contract Terminating Soon</fullName>
                </value>
                <value>
                    <fullName>Feature Add</fullName>
                </value>
                <value>
                    <fullName>Gift for Upcoming Occasion</fullName>
                </value>
                <value>
                    <fullName>iPhone X</fullName>
                </value>
                <value>
                    <fullName>iPhone X send message</fullName>
                </value>
                <value>
                    <fullName>New Service</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>Special Event</fullName>
                </value>
                <value>
                    <fullName>Tablets</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_leadSubStatus__c</fullName>
        <description>This field is used to store the Lead Sub Status</description>
        <inlineHelpText>Populated when the status is “Responded” or “Qualified”</inlineHelpText>
        <label>Lead Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>Action Required</fullName>
                </value>
                <value>
                    <fullName>In Discussion</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Needs Store Reassignment</fullName>
                </value>
                <value>
                    <fullName>Service Issue</fullName>
                </value>
                <value>
                    <fullName>Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart-Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart Opt Out</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_myActiveLeadsApexController.cls
/**
*@name          CCPM_myActiveLeadsApexController
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          12/07/2017
*@description   For "My Active Leads" Component in UI
Modification    Log:
------------------------------------------------------------------------------------
Developer                                     Date               Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)             12/07/2017         Original Version       
*/
public with sharing class CCPM_myActiveLeadsApexController {
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   Method that queries and Loads data for Lead
*@return        wrapperClass
*/ 
    @AuraEnabled
    public static myActiveLeadswrapper loadComponentWithRecords(string strSortBy,string strOrderby,string strLimit,string strOffSet){
        //Instantiate Wrapper Class
        myActiveLeadswrapper objwrapperClass = new myActiveLeadswrapper();
        //Instantiate a list of Leads
        list<Lead> lstlead = new list<Lead>();
        //Instantiate Metadata settings
        CCPM_UIComponentSetting__mdt mdtUIComponentSetting=new CCPM_UIComponentSetting__mdt();
        //Check if the values from attributes are null for the initial Load and obtain settings from metadata
        if(String.isBlank(strSortBy) || String.isBlank(strOrderby) || String.isBlank(strLimit))
        {
            mdtUIComponentSetting= CCPM_myActiveLeadsApexController.setQueryParam();
            strSortBy=mdtUIComponentSetting.CCPM_orderByField__c;
            strOrderby=mdtUIComponentSetting.CCPM_order__c;
            strLimit=mdtUIComponentSetting.CCPM_recordLimit__c;
        }
        //Get the total number of records in the expected Status in order to calculate offset for Pagination
        integer intMaxSize= database.countQuery('select count() from Lead where Status =\''+CCPM_staticConstants.strLeadStatusContacted +'\' or Status=\''+CCPM_staticConstants.strLeadStatusEligible+'\' or (Status=\''+CCPM_staticConstants.strLeadStatusQualified+'\' and (CCPM_leadSubStatus__c=\''+CCPM_staticConstants.strLeadSubStatusInDiscussion+'\' or CCPM_leadSubStatus__c=\'' +CCPM_staticConstants.strLeadSubStatusAppointmentScheduled+'\'))');
        objwrapperClass.intMaxSize=intMaxSize;
        //Build the Query String
        string queryInitialString ='SELECT Id,Name,Status,CCPM_mobileNumber__c,Owner.Name ,CCPM_Type__c,CCPM_SMSFollowUpDate__c,CCPM_leadSubStatus__c ,CCPM_eventType__c, (select Campaign.name from CampaignMembers order by createddate asc limit 1) from lead where Status =\''+CCPM_staticConstants.strLeadStatusContacted +'\' or Status=\''+CCPM_staticConstants.strLeadStatusEligible+'\' or (Status=\''+CCPM_staticConstants.strLeadStatusQualified+'\' and (CCPM_leadSubStatus__c=\''+CCPM_staticConstants.strLeadSubStatusInDiscussion+'\' or CCPM_leadSubStatus__c=\'' +CCPM_staticConstants.strLeadSubStatusAppointmentScheduled+'\'))'+' ORDER BY '+strSortBy+' '+strOrderby+' NULLS LAST LIMIT '+strLimit+ ' OFFSET '+strOffSet;
    	System.debug('queryInitialString'+queryInitialString);
        //Obtain results from the query into the List of Leads   
        lstlead=Database.query(queryInitialString);
        if(lstlead.size()>0)
        {
            objwrapperClass.lstLead=lstlead;
        }
        if(mdtUIComponentSetting!=null)
        {
            objwrapperClass.metadataSettings=mdtUIComponentSetting;
        }
        return objwrapperClass;    
    }
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   Method that queries for Metadata settings to get the Limit in the query being used,Order By Field,Order
*@return        Metadata
*/ 
    @AuraEnabled
    public static CCPM_UIComponentSetting__mdt setQueryParam(){
        CCPM_UIComponentSetting__mdt mdtActiveLeadSettings = new CCPM_UIComponentSetting__mdt();
        //Obtain the metadata settings to set the initial Attributes
        mdtActiveLeadSettings = [select CCPM_orderByField__c,CCPM_order__c,CCPM_recordLimit__c from CCPM_UIComponentSetting__mdt where DeveloperName =:Label.CCPM_UIHomePageMyActiveLeadsLabel];
        System.debug('Metadata Values returned from query->'+mdtActiveLeadSettings);
        return mdtActiveLeadSettings;
    }
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   Wrapper class to provision a datastructure containing collection of Objects
*@return        None
*/ 
    public class myActiveLeadswrapper{
        @AuraEnabled public List<Lead> lstLead{get;set;}
        @AuraEnabled public CCPM_UIComponentSetting__mdt metadataSettings{get;set;}
        @AuraEnabled public Integer intMaxSize{get;set;}
        
    }  
    
    
}