VZDEV/src/objects/CCPM_OrganizationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CCPM_DisableOldTriggerForTest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DisableOldTriggerForTest</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization Setting</label>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_finalPreDefinedSMSFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Pre Defined SMS Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_firstPredefinedSMSFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Predefined SMS Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isFollowUpSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if follow up SMS was sent</description>
        <inlineHelpText>Has a follow up SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Follow-Up SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isInitialSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</description>
        <inlineHelpText>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Initial SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_leadSubStatus__c</fullName>
        <description>This field is used to store the Lead Sub Status</description>
        <inlineHelpText>Populated when the status is “Responded” or “Qualified”</inlineHelpText>
        <label>Lead Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>Action Required</fullName>
                </value>
                <value>
                    <fullName>In Discussion</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Needs Store Reassignment</fullName>
                </value>
                <value>
                    <fullName>Service Issue</fullName>
                </value>
                <value>
                    <fullName>Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart-Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart Opt Out</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_sendSMSControllerTest.cls
/**
*@name          CCPM_sendSMSControllerTest 
*@author        Ritwik Koneru (Deloitte)
*@date          02/08/2018
*@description   This is a Test class for
*@Class         CCPM_sendSMSController
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Ritwik Koneru (Deloitte)    02/08/2018   Initial Implementation.
*/

@isTest(seeAllData=false)
private class CCPM_sendSMSControllerTest {
    
    static String strLeadCustomerCartRT = 
        Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.CCPM_leadCustomerCartRT).getRecordTypeId();
    
    /**
	@author       Ritwik Koneru (Deloitte)
	@description  Test method for ccpm_sendSMSController class
	@param        N/A
	@return       Void(None)
	*/ 
    static testMethod void testsendPreDefinedSMSToCustomer() {
        
        list<user> lstUser = ccpm_testDataUtil.createTestUsers('System Administrator',1);
        insert lstUser;
        system.runAs(lstUser[0]){
      
            CCPM_OrganizationSetting__c settings = CCPM_OrganizationSetting__c.getInstance(lstUser[0].id);
            settings.CCPM_DisableOldTriggerForTest__c = false;
            insert settings;
            
            Integer resInt = 0;
            integer resInt1 = 0;
            
            list<lead> lstLead = ccpm_testDataUtil.createLead(2,strLeadCustomerCartRT,false,'Prospect SFDC Manual');
            lstLead[0].Status = 'Eligible';
            lstLead[0].CCPM_isInitialSMSSent__c = true;
            lstLead[0].CCPM_isFollowUpSMSSent__c = false;
            lstLead[0].CCPM_firstPredefinedSMSFlag__c = false;
            lstLead[0].CCPM_finalPreDefinedSMSFlag__c = false;
            insert lstLead[0];
            
            test.startTest();
            ccpm_sendsmsController.SendSMSWrapper resWrapper1 = new ccpm_sendsmsController.sendsmsWrapper('Test');
            resWrapper1 = ccpm_sendSMSController.getLeadAndSendSMSWrapperInfo(lstLead[0].id);
            system.assertEquals('Lead has to be in Responded - Action Required State.',resWrapper1.strMessage);
            
            lstLead[0].status='Responded';
            update lstLead[0];
            
            lstLead[0].ccpm_leadsubstatus__c = 'Action Required';
            update lstLead[0];

            ccpm_sendsmsController.SendSMSWrapper resWrapper2 = new ccpm_sendsmsController.sendsmsWrapper('Test');
            resWrapper2 = ccpm_sendSMSController.getLeadAndSendSMSWrapperInfo(lstLead[0].id);
            system.assertEquals('Customer',resWrapper2.strMessage);
            
            Test.setMock(HttpCalloutMock.class, new CCPM_PreMockHttpResponseGenerator());
			list<String> lstStr = new list<String>();           
            try{
                resInt = ccpm_sendSMSController.sendPreDefinedSMSToCustomer(lstLead[0],'Custom Reply','Test',lstStr);
            } catch (exception e){}
            //system.assertEquals(204, resInt);
            lstLead[0].CCPM_firstPredefinedSMSFlag__c = true;
				update lstLead[0];
            try {
				integer	resInt2 = ccpm_sendSMSController.sendPreDefinedSMSToCustomer(lstLead[0],'Custom Reply','Test',lstStr);
				} catch (exception e){}
            system.assert(resInt!=null);
            lstStr.add('cock');
				try {
					resInt1 = ccpm_sendSMSController.sendPreDefinedSMSToCustomer(lstLead[0],'Custom Reply','Test',lstStr);
				} catch (exception e){}
			system.assertEquals(0,resInt1);
            ccpm_sendSMSController.createCustomeMessageRecord(lstLead[0], 'Hi', 'Blocked', lstStr, 'Custom Reply');
            test.stopTest();
        }
    }
}