VZDEV/src/objects/CCPM_callDetails__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_callStatus__c</fullName>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Call In-Progress</fullName>
                </value>
                <value>
                    <fullName>Call Complete</fullName>
                </value>
                <value>
                    <fullName>Response Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Details</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Call Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/LOG_LogMessage__c.object
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_clickToCallScheduleJob.cls
/**
*@name          CCPM_clickToCallScheduleJob
*@author        Sriraman Sridharan (Deloitte)
*@date          04/06/2018
@description    DISTSCE-3054  
@testClass      
Modification    Log:
------------------------------------------------------------------------------------
Developer               			Date                           Description
------------------------------------------------------------------------------------
Sriraman Sridharan (Deloitte)    04/06/2018          			Original Version   
   
*/ 
global class CCPM_clickToCallScheduleJob implements Schedulable {
/* 
* Method Name: execute
* Author     : Sriraman Sridharan (Deloitte)
* Date       : 04/06/2018
* Description: This method is used to execute the batch job with specific batch size    
*/  
    
    global void execute(SchedulableContext BG)    
    {
        // Creating the object for the Batch Class and invoking the batch execution  
        Datetime objCurrentDateTime = System.now().addMinutes(-30);
        string strDate = objCurrentDateTime.format('yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX');
        string strquery = 'select id, CreatedDate, CCPM_callStatus__c from CCPM_callDetails__c where CCPM_callStatus__c = \'Call In-Progress\' AND CreatedDate < ' + strDate;
       // system.debug('@@@strquery : ' + strquery);
        List<CCPM_callDetails__c> lstcallDetails = Database.query(strquery);
       // system.debug('@@@lstcallDetails : ' + lstcallDetails);
        
        if(CCPM_Collection.isNotNullEmpty(lstcallDetails)){
            for(CCPM_callDetails__c objCallDetails : lstcallDetails){
                objCallDetails.CCPM_callStatus__c = label.CCPM_StatusResponseFailed;
            }
            try{
                update lstcallDetails;
            }
            Catch(Exception e){
                LOG_LogMessage__c objLogError = CCPM_utility.logMessage(e,'Error','execute','CCPM_clickToCallScheduleJob','Exception thrown while updating call details','');
                insert objLogError;
            }
        }
        /*
        String StrCRONEXP = '0 15 * * * ?'; 
		CCPM_clickToCallScheduleJob objSch = new CCPM_clickToCallScheduleJob(); 
		system.schedule('CCPM_clickToCallBatchJob- 15 Mins', StrCRONEXP, objSch);*/
    }   
}