VZDEV/src/objects/CCPM_promoMessage__mdt.object
<CustomObject>
    <fields>
        <fullName>CCPM_MessageContentForLeads__c</fullName>
        <label>Message Content For Leads</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_finalPreDefinedResponse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Pre Defined Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_firstPreDefinedResponse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Pre Defined Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_messageContentForProspects__c</fullName>
        <label>Message Content For Prospects</label>
        <type>TextArea</type>
    </fields>
    <label>Send  Pre Defined SMS</label>
    <pluralLabel>Send Pre Defined SMS</pluralLabel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_city__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_phone__c</fullName>
        <description>Contact number of the store</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_storeEcode__c</fullName>
        <label>Store Ecode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_zipcode__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <description>Email address specified by the customer when creating the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Email of the lead / prospect. Required to save a Prospect if the MTN is unavailable.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_finalPreDefinedResponse__c</fullName>
        <label>Final Pre Defined Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ok, thank you! Have a great day.</fullName>
                </value>
                <value>
                    <fullName>Ok, I’ll be reaching out to you via phone, shortly.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_finalPreDefinedSMSFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Pre Defined SMS Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_firstPreDefinedResponse__c</fullName>
        <label>First PreDefined Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ok, thanks! Please call our customer service department at 1-800-922-0204.</fullName>
                </value>
                <value>
                    <fullName>Ok, thanks! We will make the necessary changes.</fullName>
                </value>
                <value>
                    <fullName>Ok, thank you! Have a great day.</fullName>
                </value>
                <value>
                    <fullName>Yes, thank you! See you then.</fullName>
                </value>
                <value>
                    <fullName>Ok, I’ll be reaching out to you via phone, shortly.</fullName>
                </value>
                <value>
                    <fullName>What would be the best time to follow up with you via phone call?</fullName>
                </value>
                <value>
                    <fullName>-- None --</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, I’ll be reaching out to you via phone, shortly. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, thank you! Have a great day. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, thanks! Please call our customer service department at 1-800-922-0204. (Free VzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, thanks! We will make the necessary changes. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, we will dismiss your cart. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Yes, thank you! See you then. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_firstPredefinedSMSFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Predefined SMS Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isInformaticaMerge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Informatica Merge Flag</description>
        <inlineHelpText>Informatica Merge Flag. this will be checked by Informatica Feed when there is an update to the existing cart  with new cart details (Merge Scenarios)</inlineHelpText>
        <label>Informatica Merge ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isMergedUIFlag__c</fullName>
        <description>Merged Record</description>
        <formula>IF(OR( CCPM_isMerged__c, CCPM_isInformaticaMerge__c ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Merged Record</inlineHelpText>
        <label>Merged Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isMerged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Merged?</description>
        <inlineHelpText>This flag is automatically checked during the merge process once we merge the child lead</inlineHelpText>
        <label>Merged ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_lastPromoSent__c</fullName>
        <label>Last Promo Sent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_leadSubStatus__c</fullName>
        <description>This field is used to store the Lead Sub Status</description>
        <inlineHelpText>Populated when the status is “Responded” or “Qualified”</inlineHelpText>
        <label>Lead Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>Action Required</fullName>
                </value>
                <value>
                    <fullName>In Discussion</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Needs Store Reassignment</fullName>
                </value>
                <value>
                    <fullName>Service Issue</fullName>
                </value>
                <value>
                    <fullName>Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart-Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart Opt Out</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_ownerEcode__c</fullName>
        <formula>Owner:User.CCPM_commissionableRepID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Ecode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_promoFirstSent__c</fullName>
        <label>Promo 1 Sent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_promoSecondSent__c</fullName>
        <label>Promo 2 Sent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeEcode__c</fullName>
        <formula>(Store__r.CCPM_storeEcode__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Ecode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_sendPreDefinedSMSTest.cls
/**
*@name          CCPM_sendPreDefinedSmsTest 
*@author        Manjunath Keshava (Deloitte)
*@date          06/09/2017
@description    This is the Unit Test Class for the sendPreDefinedSms Class  
@testClass      
Modification    Log:
------------------------------------------------------------------------------------
Developer                       Date                                Description
------------------------------------------------------------------------------------
Manjunath Keshava (Deloitte)    06/09/2017               			 Original Version
Manjunath Keshava (Deloitte)    07/09/2017               			 Modified Version
*/

@istest(SeeAllData=False)
public class CCPM_sendPreDefinedSMSTest 
{
/**
 *  *@author        Manjunath Keshava (Deloitte)
*@description   This method is targeted to test the CCPM_sendPreDefinedSms class
*/
    @testsetup
    public static void leadCreation()
    {
      CCPM_testDataFactory.createCustomSetting();
        ccpm_staticConstants.strColon='';
        lead objNewLead = new lead(LastName = 'Mike', CCPM_mobileNumber__c='3473483204', CCPM_email__c='keshavamanjuth@gmail.com',phone ='1234567890',email='mk@gmail.com' ,Company='1',CCPM_SMSLegalOptIn__c=true, CCPM_LeadType__c = 'Customer Abandoned Cart Digital');
        if(objNewLead!=null)
        insert objNewLead;
        system.assertEquals('3473483204',objNewLead.CCPM_mobileNumber__c );
     }
     public static  testmethod void  getLeadPhone_Test()
    {
        CCPM_testDataFactory.createStore(2);
        list<CCPM_Store__c > lststore=[select id,CCPM_storeID__c from CCPM_Store__c limit 1];
        lead testLead = [Select Id, Name,email,Store__c from lead where phone= '1234567890'];
        //testLead.Store__c=lststore[0].id;
        CCPM_sendPreDefinedSMS.getLeadPhone (testLead.Id); 
        // lead NewtestLead = [SELECT Id,CCPM_ownerEcode__c,RecordTypeId,CCPM_promoFirstSent__c,CCPM_promoSecondSent__c,CCPM_lastPromoSent__c,CCPM_isMerged__c,CCPM_isInformaticaMerge__c,CCPM_isMergedUIFlag__c, recordtype.name,CCPM_mobileNumber__c, Store__r.name, Store__r.CCPM_street__c, Store__r.CCPM_city__c, Store__r.CCPM_phone__c,Store__r.CCPM_zipcode__c, Status,CCPM_leadSubStatus__c,CCPM_firstPredefinedSMSFlag__c,CCPM_finalPreDefinedSMSFlag__c FROM  lead where Id=:testLead.Id];
        //CCPM_sendPreDefinedSMS.getLeadPhone ( NewtestLead.Id);   
    }
      
    @istest(SeeAllData=False)
    public static  void SendPreDefinedSMSCustomer_Test()
    {
         Test.startTest();
         // Set mock callout class
	     Test.setMock(HttpCalloutMock.class, new CCPM_MockHttpResponseGenerator());
        List<CCPM_promoMessage__mdt> listPromoSMSSetting = [Select MasterLabel,CCPM_finalPreDefinedResponse__c,CCPM_firstPreDefinedResponse__c,CCPM_MessageContentForLeads__c,CCPM_messageContentForProspects__c From CCPM_promoMessage__mdt ];
        List<CCPM_promoMessage__mdt> listNewPromoSMSSetting=( List<CCPM_promoMessage__mdt>)Json.deserialize('[{"MasterLabel":"Promo iPhone-8","CCPM_finalPreDefinedResponse__c":"false","CCPM_MessageContentForLeads__c":"Testmessage for Leads","CCPM_messageContentForProspects__c":"TestMessage for Prospects"}]',list<CCPM_promoMessage__mdt>.class);
		 lead newtestLead = [Select Id,RecordTypeId,CCPM_storeEcode__c, Name,CCPM_ownerEcode__c,email from lead where phone= '1234567890'];
         CCPM_sendPreDefinedSMS.sendPreDefinedSMSToCustomer (newtestLead.id,' message','Promo iPhone-8', true, 'In Discussion',newtestLead.RecordTypeId, newtestLead.CCPM_ownerEcode__c,'iPhone X','iPhone 8','iPhone 8',newtestLead.CCPM_storeEcode__c);
         test.stopTest();
    }
    @isTest
    public static  void SendPreDefinedSMSCustomer_Test2()
    {
        Test.startTest();
	     Test.setMock(HttpCalloutMock.class, new CCPM_PreMockHttpResponseGenerator());
		 lead newtestLead = [Select Id,RecordTypeId,CCPM_ownerEcode__c, Name,email from lead where phone= '1234567890'];
        System.debug('CCPM_staticconstants.strProspectAbandonedCartRecordTypeID ' + newtestLead.RecordTypeId );
        newtestLead.recordTypeId = CCPM_staticConstants.strLeadCustomerAbandonedCartRecordTypeID;
        List<CCPM_promoMessage__mdt> listPromoSMSSetting = [Select MasterLabel,CCPM_finalPreDefinedResponse__c,CCPM_firstPreDefinedResponse__c,CCPM_MessageContentForLeads__c,CCPM_messageContentForProspects__c From CCPM_promoMessage__mdt ];
        List<CCPM_promoMessage__mdt> listNewPromoSMSSetting=( List<CCPM_promoMessage__mdt>)Json.deserialize('[{"MasterLabel":"Promo iPhone-8","CCPM_finalPreDefinedResponse__c":"false","CCPM_MessageContentForLeads__c":"Testmessage for Leads","CCPM_messageContentForProspects__c":"TestMessage for Prospects"}]',list<CCPM_promoMessage__mdt>.class);
         CCPM_sendPreDefinedSMS.sendPreDefinedSMSToCustomer (newtestLead.id,' message','Yes! Our Store Address Is:the--true response--the end result is unknown and the error is yet to be found and then it must be resolved and end result is unknown and the error is yet to be found and then it must be resolved ', false, 'In Discussion',newtestLead.RecordTypeId,null,null,'iPhone 8','iPhone 8',newtestLead.CCPM_storeEcode__c);
        test.stopTest();
    }
    
    @isTest
    public static void  getLeadSubStatus()
    {
         CCPM_sendPreDefinedSms.getLeadSubStatus();
    }
     @isTest 
    public static void getFirstpreDefinedSMSReponse_Test()  
       {
                   CCPM_staticConstants.strRecordTypesWithFreeVzMsg='manjunath:keshava';
           lead testLead = [Select Id, Name,email,Store__c from lead where phone= '1234567890'];
        //testLead.Store__c=lststore[0].id;
        CCPM_sendPreDefinedSMS.getLeadPhone (testLead.Id); 
           CCPM_sendPreDefinedSms.getFirstpreDefinedSMSReponse();
           
       }
     @isTest 
    public static void getFinalpreDefinedSMSReponse_Test()
    {
        CCPM_sendPreDefinedSms.getFinalPreDefinedSMSReponse();
    }
    @isTest
    public static void determineFreeVzMsgSuffi_Test()
      {
        CCPM_staticConstants.strRecordTypesWithFreeVzMsg='manjunath:keshava';		
    	CCPM_sendPreDefinedSms.determineFreeVzMsgSuffix();
      }    
   
}