VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <fields>
        <fullName>CCPM_MessageStatus__c</fullName>
        <description>Refers to the status of the Message sent based on response code.</description>
        <inlineHelpText>Refers to the status of the Message sent based on response code.</inlineHelpText>
        <label>Message Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Resend Failed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_message__c</fullName>
        <description>Message body to be sent.</description>
        <inlineHelpText>Message body to be sent.</inlineHelpText>
        <label>Message</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_requestID__c</fullName>
        <label>RequestID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_SMSMessageTriggerHandlerTest.cls
@isTest
public class CCPM_SMSMessageTriggerHandlerTest {
@isTest
     public static void InsertSMSMessageRecordsforPart2BeforeUpdateTest(){
         CCPM_testDataFactory.createCustomSetting();
         CCPM_testDataFactory.createCartProspectTest(1,CCPM_staticConstants.strContractTerminatingSoon);
        list<Lead> lstLead = [select id, ownerid from lead where ownerid!= NULL limit 1];
         system.debug('lstLead' +lstLead);
        List<CCPM_SMSMessage__c> SMSObjRecord = CCPM_testDataFactory.insertSMSObjectRecord(50,'Hi%HI',CCPM_staticConstants.strMessageTypeInitialSMSPart1,lstLead[0].id);
        insert SMSObjRecord;
        CCPM_SMSMessageTriggerHandler.InsertSMSMessageRecordsforPart2BeforeUpdate(SMSObjRecord);
    }
    
@isTest
    public static void UpdateSMSMessageRecordsforPart1BeforeUpdateTest(){
        CCPM_testDataFactory.createCustomSetting();
         //CCPM_staticconstants.strMessageStatusSent='sent';
        CCPM_testDataFactory.createCartProspectTest(1,CCPM_staticConstants.strContractTerminatingSoon);
        list<Lead> lstLead = [select id, ownerid from lead where ownerid!= NULL limit 1];
        List<CCPM_SMSMessage__c> SMSObjRecord = CCPM_testDataFactory.insertSMSObjectRecord(1, 'Hi%HI', CCPM_staticConstants.strMessageTypeInitialSMSPart1, lstLead[0].id);
        insert SMSObjRecord;
        system.debug('SMSObjRecord1' +SMSObjRecord);
        //CCPM_SMSMessage__c newSMSObj = new CCPM_SMSMessage__c();
        //newSMSObj.id=SMSObjRecord[0].id;
        SMSObjRecord[0].CCPM_message__c = 'Test%test';
        //SMSObjRecord[0].CCPM_MessageStatus__c = CCPM_staticConstants.strMessageStatusSent;
        system.debug('SMSObjRecord' +SMSObjRecord);
        List<CCPM_SMSMessage__c> newSMSObjRecord = new List<CCPM_SMSMessage__c>();
        for(CCPM_SMSMessage__c c: SMSObjRecord){
            c.CCPM_requestID__c = '65791bda-40fb-4d00\\^a35c-7b7cd314ae6b';
            c.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusSent;
            newSMSObjRecord.add(c);
        }
        
       // SMSObjRecord.add(newSMSObj);
        
        
     /*   List<CCPM_SMSMessage__c> lstSMSObjRecord = new List<CCPM_SMSMessage__c>();
        CCPM_SMSMessage__c smsMessageObj = new CCPM_SMSMessage__c();
        if(lstSMSObjRecord.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusQueued){
        lstSMSObjRecord.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusSent;
        } */
        update newSMSObjRecord; 
       
    }
    @isTest
    public static void UpdateSMSMessageRecordsforPart1BeforeUpdateTestPart2(){
         CCPM_testDataFactory.createCustomSetting();
         //CCPM_staticconstants.strMessageStatusSent='sent';
        CCPM_testDataFactory.createCartProspectTest(1,CCPM_staticConstants.strContractTerminatingSoon);
        list<Lead> lstLead = [select id, ownerid from lead where ownerid!= NULL limit 1];
        List<CCPM_SMSMessage__c> SMSObjRecord = CCPM_testDataFactory.insertSMSObjectRecord(1, 'Hi%HI', CCPM_staticConstants.strMessageTypeCampaignInitialSMSPart1, lstLead[0].id);
        insert SMSObjRecord;
        system.debug('SMSObjRecord1' +SMSObjRecord);
        //CCPM_SMSMessage__c newSMSObj = new CCPM_SMSMessage__c();
        //newSMSObj.id=SMSObjRecord[0].id;
        SMSObjRecord[0].CCPM_message__c = 'Test%test';
        //SMSObjRecord[0].CCPM_MessageStatus__c = CCPM_staticConstants.strMessageStatusSent;
        system.debug('SMSObjRecord' +SMSObjRecord);
        List<CCPM_SMSMessage__c> newSMSObjRecord = new List<CCPM_SMSMessage__c>();
        for(CCPM_SMSMessage__c c: SMSObjRecord){
            c.CCPM_requestID__c = '65791bda-40fb-4d00\\^a35c-7b7cd314ae6b';
            c.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusSent;
            newSMSObjRecord.add(c);
        }
        
       // SMSObjRecord.add(newSMSObj);
        
        
     /*   List<CCPM_SMSMessage__c> lstSMSObjRecord = new List<CCPM_SMSMessage__c>();
        CCPM_SMSMessage__c smsMessageObj = new CCPM_SMSMessage__c();
        if(lstSMSObjRecord.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusQueued){
        lstSMSObjRecord.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusSent;
        } */
        update newSMSObjRecord;    
    }
        @isTest
    public static void UpdateSMSMessageRecordsforPart1BeforeUpdateTestPart3(){
         CCPM_testDataFactory.createCustomSetting();
         //CCPM_staticconstants.strMessageStatusSent='sent';
        CCPM_testDataFactory.createCartProspectTest(1,CCPM_staticConstants.strContractTerminatingSoon);
        list<Lead> lstLead = [select id, ownerid from lead where ownerid!= NULL limit 1];
        List<CCPM_SMSMessage__c> SMSObjRecord = CCPM_testDataFactory.insertSMSObjectRecord(1, 'Hi%HI', CCPM_staticConstants.strMessageTypeProspectFirstSMSPart1, lstLead[0].id);
        insert SMSObjRecord;
        system.debug('SMSObjRecord1' +SMSObjRecord);
        //CCPM_SMSMessage__c newSMSObj = new CCPM_SMSMessage__c();
        //newSMSObj.id=SMSObjRecord[0].id;
        SMSObjRecord[0].CCPM_message__c = 'Test%test';
        //SMSObjRecord[0].CCPM_MessageStatus__c = CCPM_staticConstants.strMessageStatusSent;
        system.debug('SMSObjRecord' +SMSObjRecord);
        List<CCPM_SMSMessage__c> newSMSObjRecord = new List<CCPM_SMSMessage__c>();
        for(CCPM_SMSMessage__c c: SMSObjRecord){
            c.CCPM_requestID__c = '65791bda-40fb-4d00\\^a35c-7b7cd314ae6b';
            c.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusSent;
            newSMSObjRecord.add(c);
        }
        
       // SMSObjRecord.add(newSMSObj);
        
        
     /*   List<CCPM_SMSMessage__c> lstSMSObjRecord = new List<CCPM_SMSMessage__c>();
        CCPM_SMSMessage__c smsMessageObj = new CCPM_SMSMessage__c();
        if(lstSMSObjRecord.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusQueued){
        lstSMSObjRecord.CCPM_MessageStatus__c = CCPM_staticconstants.strMessageStatusSent;
        } */
        update newSMSObjRecord;    
    }

}