VZDEV/src/objects/CCPM_SMSSchedulesToBeRemoved__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_InsertedDateTime__c</fullName>
        <description>Time during which the record was inserted</description>
        <label>Inserted DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>SMS Schedules To Be Removed</label>
    <nameField>
        <displayFormat>SMS2R-{00}</displayFormat>
        <label>SMS Schedules To Be Removed</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Schedules To Be Removed</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_RemoveSmsScheduleBatch.cls
/**
*@name          RemoveSmsScheduleBatch
*@author        Sriraman Sridharan (Deloitte)
*@date          07/14/2017
@description    Batch class to remove the sms schedules
@testClass      
Modification    Log:
------------------------------------------------------------------------------------
Developer             				  Date                                Description
------------------------------------------------------------------------------------
Sriraman Sridharan(Deloitte)        07/14/2017                       Original Version
*/

global class CCPM_RemoveSmsScheduleBatch implements Database.Batchable<sObject>{
    
    global final string strQuery;
    global string status = CCPM_staticConstants.StatusNew;
    /**
*@author        Sriraman Sridharan (Deloitte)
*@description   This Constructor builds up the query to fetch the custom records that .
*@return        Void(None) 
*/ 
    
    global CCPM_RemoveSmsScheduleBatch(){
        // Construct the Query for the custom object
        
       this.strQuery = 'select id, name, CCPM_accountUniqueID__c, CCPM_storeID__c, CCPM_Status__c, CCPM_InsertedDateTime__c from CCPM_SMSSchedulesToBeRemoved__c where CCPM_Status__c ='+ '\'' + status + '\'' +' limit '+CCPM_staticConstants.strRemoveSmsScheduleBatchLimit;
    	//system.debug('@@@Querry ' +this.strQuery);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Returning the records obtained by querying
        system.debug('@@@Querry' + this.strQuery);
        return Database.getQueryLocator(this.strQuery);
    }
    /**
*@author        Sriraman Sridharan (Deloitte)
*@description   Execute method in batchable context to make a callout to the handler
*@return        Void(None)
*/    
    global void execute(Database.BatchableContext BC, List<CCPM_SMSSchedulesToBeRemoved__c> scope) {
        system.debug('# List of records from query in batchable context -> '+scope);
        CCPM_RemoveSmsScheduleBatchHandler.CCPM_RemoveSmsScehdules(Scope);
    }
    /**
*@author        Sriraman Sridharan (Deloitte)
*@description   This method schedules the Batch class for every 5 min(Need to confirm)
*@return        Void(None)
*/     
    global void finish(Database.BatchableContext BC){
        
    }
}