VZDEV/src/objects/CCPM_OrganizationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CCPM_DisableTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization Setting</label>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_Store__c</fullName>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Store Employees</relationshipLabel>
        <relationshipName>Store_Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCPM_employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>CCPM Sales Rep,CCPM Retail Sales Rep,CCPM Retail Store Management,CCPM Retail District Management,CCPM Telesales Rep,CCPM Telesales Supervisor,CCPM Telesales Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_isStoreActive__c</fullName>
        <formula>CCPM_Store__r.CCPM_IsActive__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Store Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Store Manager</fullName>
                </value>
                <value>
                    <fullName>Assistant Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_storeEmployeeTriggerHandler.cls
/**
*@name          CCPM_storeEmployeeTriggerHandler 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          11/08/2017
*@description   This is a handler for CCPM_storeEmployeeTrigger
*@Class         CCPM_storeEmployeeTriggerHandler
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    11/08/2017   Initial Implementation.
*/
public with sharing class CCPM_storeEmployeeTriggerHandler  implements CCPM_ITriggerHandler{
    
    // Allows unit tests (or other code) to disable this trigger for the transaction
    public static Boolean boolTriggerDisabled = false;
    
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  Checks to see if the trigger has been disabled either by custom setting or by running code
	@param        N/A
	@return       Boolean
	*/ 
    public Boolean IsDisabled()
    {
        CCPM_OrganizationSetting__c settings = CCPM_OrganizationSetting__c.getInstance(UserInfo.getUserId());
	    if(settings != null && settings.CCPM_DisableTrigger__c == true){
	        return true;
	    }
        else
            return boolTriggerDisabled;
    }
    
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the before insert trigger context
	@param        List<SObject>
	@return       void
	*/     
    public void BeforeInsert(List<SObject> lstNewItems) {
    	/**************Method Declarations Start*/
    	List<CCPM_storeEmployee__c> lstNew = (List<CCPM_storeEmployee__c>) lstNewItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the before update trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void BeforeUpdate(Map<Id, SObject> mapNewItems, Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_storeEmployee__c> mapNew = (Map<id, CCPM_storeEmployee__c>)mapNewItems;
    	Map<id, CCPM_storeEmployee__c> mapOld = (Map<id, CCPM_storeEmployee__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	for(CCPM_storeEmployee__c objStrEmp : mapNew.values()){
    		
    		CCPM_strEmpTriggerHandlerHelper.flagRecForBatchProcess(objStrEmp, mapOld.get(objStrEmp.id)); 	
    	}
    	/**************First loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the before delete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void BeforeDelete(Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_storeEmployee__c> mapOld = (Map<id, CCPM_storeEmployee__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after insert trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterInsert(Map<Id, SObject> mapNewItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_storeEmployee__c> mapNew = (Map<id, CCPM_storeEmployee__c>)mapNewItems;
    	Map<String, Set<String>> mapStoreIdStoreEmpId = new Map<String, Set<String>>();
    	List<Lead> lstLeadToBeConsideredforSharing = new List<Lead>();
        List<leadShare> lstleadShrToInsert    = new List<leadShare>();
        Map<String, List<Lead>> mapStoreIdLeadlist = new Map<String, List<Lead>>();
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	for(CCPM_storeEmployee__c objStrEmp : mapNew.values()){
    		//Validate if Role is Assistant Manager
    		if(objStrEmp.CCPM_role__c == Label.CCPM_storeAssistantManager && objStrEmp.CCPM_Store__c!=null && objStrEmp.CCPM_employee__c!=null
    		  && objStrEmp.CCPM_isStoreActive__c){
    		  	//Put in Map of SE and store associated
    			if(mapStoreIdStoreEmpId.containsKey(objStrEmp.CCPM_Store__c)){
	    			mapStoreIdStoreEmpId.get(objStrEmp.CCPM_Store__c).add(objStrEmp.CCPM_employee__c);
	    		}  	
	    		else{
	    			mapStoreIdStoreEmpId.put(objStrEmp.CCPM_Store__c, new Set<String>{objStrEmp.CCPM_employee__c});
	    		}
    		}
    	}
    	/**************First loop End*/
    	
    	
    	//Code to provide access by iserting records to Leadshare 
    	if(CCPM_Collection.isNotNullEmpty(mapStoreIdStoreEmpId)){
    		//Query for all associated open Leads
    		lstLeadToBeConsideredforSharing = [Select id,Store__c,ownerid from Lead where Store__c in :mapStoreIdStoreEmpId.keySet() AND status IN :CCPM_utility.setleadOpenStatus];
    	}
    	//putting into map by store id
    	if(CCPM_Collection.isNotNullEmpty(lstLeadToBeConsideredforSharing)){
    		for(Lead objl : lstLeadToBeConsideredforSharing){
    			if(mapStoreIdLeadlist.containsKey(objl.Store__c)){
	    			mapStoreIdLeadlist.get(objl.Store__c).add(objl);
	    		}  	
	    		else{
	    			mapStoreIdLeadlist.put(objl.Store__c, new List<Lead>{objl}); 
	    		}
    		}
    	}
    	for(String strStoreId: mapStoreIdLeadlist.keySet()){
    		for(Lead objl: mapStoreIdLeadlist.get(strStoreId)){
    			for(String strStoreRepId : mapStoreIdStoreEmpId.get(objl.Store__c)){
    				lstleadShrToInsert.add(CCPM_globalUtility.apexShareReadAccess(objl.id,strStoreRepId));
    			}
    		}
    	}
    	
    	try{
            //Try to Insert Apex Sharing
            if(CCPM_Collection.isNotNullEmpty(lstleadShrToInsert))
            {
                insert lstleadShrToInsert;
            }
        }
        catch(Exception e)
        {
            //Catch statement in case of failure in DML Statements
            CCPM_LogMessageUtility.logMessage(e,'CCPM_storeEmployeeTriggerHandler','AfterInsert','Exception thrown while inserting Lead Shares',true);
        }
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after update trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterUpdate(Map<Id, SObject> mapNewItems, Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_storeEmployee__c> mapNew = (Map<id, CCPM_storeEmployee__c>)mapNewItems;
    	Map<id, CCPM_storeEmployee__c> mapOld = (Map<id, CCPM_storeEmployee__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after delete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterDelete(Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	
    	Map<id, CCPM_storeEmployee__c> mapOld = (Map<id, CCPM_storeEmployee__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the After undelete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterUndelete(Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_storeEmployee__c> mapOld = (Map<id, CCPM_storeEmployee__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
}