VZDEV/src/objects/CCPM_logLevelSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to set the default logging</description>
    <fields>
        <fullName>CCPM_purgeLogAfter__c</fullName>
        <inlineHelpText>Number of days that log are keep in this Org. Logs are automatically deleted if the
Apex Batch is setup</inlineHelpText>
        <label>Purge Log After</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Log Level Settings</label>
</CustomObject>

VZDEV/src/objects/LOG_LogMessage__c.object
<CustomObject>
    <description>Container for custom exception/log messages</description>
    <fields>
        <fullName>CCPM_age__c</fullName>
        <description>Age in Days</description>
        <formula>TODAY() - DATEVALUE(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Age in Days</inlineHelpText>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_deleteLogMessagesScheduler.cls
/********************************************************************************************************
* @author         Deloitte
* @description    This class is the implementation of the Schedulable interface and allows to schedule a job in 
*                 order to delete old messages
* @date           2015-06-26
* @group          Message Logs
*********************************************************************************************************/
global class CCPM_deleteLogMessagesScheduler implements Schedulable 
{
    
    // Fetch the Log Message Custom Settings in order to retrieve the Log_Purge__c
    private CCPM_logLevelSetting__c lms = CCPM_LogMessageUtility.getLogSettings();
    
    /********************************************************************************************************
    * @author       Karolinski Stephane
    * @date         2015-08-17
    * @description  This method is the implementation of the Schedule interface and invokes a Batch apex in order
    *               to delete old messages
    * @param        sc (SchedulableContext): the context of the scheduled job
    * @return       void
    *********************************************************************************************************/
    global void execute(SchedulableContext sc)
    {
        String queryString = 'SELECT  id, CCPM_age__c from LOG_LogMessage__c WHERE CCPM_age__c > ' + lms.CCPM_purgeLogAfter__c;
        Database.executeBatch(new CCPM_DeleteLogMessagesBatch(queryString), 200);
    }
}