VZDEV/src/objects/CCPM_Action__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_RE_Action_ID__c</fullName>
        <externalId>true</externalId>
        <label>RE Action ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_actionObject__c</fullName>
        <label>Action Object</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CCPM_type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>CCPM_journey__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_endDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_masterObject__c</fullName>
        <label>Master Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_relatedObjectAction__c</fullName>
        <label>Related Object Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Remove Queued And Attach to Winner</fullName>
                </value>
                <value>
                    <fullName>Close And Attach To Winner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_relatedObject__c</fullName>
        <label>Related Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SMSMessage</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_startDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RE Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_ActionComponent__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_Action__c</fullName>
        <label>Action</label>
        <referenceTo>CCPM_Action__c</referenceTo>
        <relationshipLabel>Action Components</relationshipLabel>
        <relationshipName>CCPM_ActionComponents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCPM_RE_Action_Component_ID__c</fullName>
        <externalId>true</externalId>
        <label>RE Action Component ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_fieldAPIName__c</fullName>
        <label>Field API Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_fieldValue__c</fullName>
        <label>Field Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_mergeCopyIfNullOrBlank__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Merge Copy If Null Or Blank</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_mergeCopy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Merge Copy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_variableName__c</fullName>
        <label>Variable Name</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RE Action Component</label>
    <nameField>
        <displayFormat>AC{00000}</displayFormat>
        <label>Action Components Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Action Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_fieldName__c</fullName>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_fieldType__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Double</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule</label>
        <referenceTo>CCPM_Rule__c</referenceTo>
        <relationshipLabel>Criterias</relationshipLabel>
        <relationshipName>CCPM_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RE Criteria</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Criteria Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_RERecord__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_RE_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>RE Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_primaryObject__c</fullName>
        <label>Primary Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_recordNameUnique__c</fullName>
        <inlineHelpText>This field is to make sure the Name is Unique. This field is filled in by a workflow with the Name of the Record.</inlineHelpText>
        <label>Record Name Unique</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RE Record</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Rule__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_RE_Rule_ID__c</fullName>
        <externalId>true</externalId>
        <label>RE Rule ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_endDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_existingRecord__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Existing Record</label>
        <referenceTo>CCPM_RERecord__c</referenceTo>
        <relationshipLabel>RE Rules (Existing Record)</relationshipLabel>
        <relationshipName>CCPM_exitingRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_mergeUniqueField__c</fullName>
        <description>This is filled in by workflow. THis is a combination of the Winner reference field and Looser Reference field.</description>
        <label>Merge Unique Field</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_newRecord__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>New Record</label>
        <referenceTo>CCPM_RERecord__c</referenceTo>
        <relationshipLabel>RE Rules (New Record)</relationshipLabel>
        <relationshipName>CCPM_newRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_primaryObject__c</fullName>
        <label>Primary Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_startDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_winningRecord__c</fullName>
        <label>Winning Record</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Record</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Existing Record</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RE Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_RuleAction__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_action__c</fullName>
        <label>Action</label>
        <referenceTo>CCPM_Action__c</referenceTo>
        <relationshipLabel>RE Rule Actions</relationshipLabel>
        <relationshipName>CCPM_RERuleActions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_rule__c</fullName>
        <label>Rule</label>
        <referenceTo>CCPM_Rule__c</referenceTo>
        <relationshipLabel>RE Rule Actions</relationshipLabel>
        <relationshipName>CCPM_RERuleActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RE Rule Action</label>
    <nameField>
        <displayFormat>RA{00000}</displayFormat>
        <label>Rule Action Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_Type__c</fullName>
        <description>Type</description>
        <formula>IF(OR(AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = true),ISPICKVAL(CCPM_leadType__c,&apos;Customer SFDC Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales SFDC Manual&apos;)),&apos;Manual Lead&apos;, 
IF(OR(CONTAINS(TEXT(LeadSource), &quot;CRM&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Campaign&apos;)),&apos;Campaign Lead&apos;, 
IF(OR(CONTAINS(TEXT(CCPM_leadType__c),&quot;Customer Abandoned Cart&quot;), AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = false)),&apos;Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Abandoned Visit&apos;),&apos;Abandoned Visit Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Quotes&apos;),&apos;Quote Lead&apos;, 
IF(OR(ISPICKVAL(CCPM_leadType__c,&apos;Prospect SFDC Manual&apos;),CONTAINS(TEXT(CCPM_leadType__c),&quot;Prospect Abandoned Cart&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Prospect Telesales SFDC Manual&apos;), RecordType.Name = &apos;Prospect Cart&apos;, RecordType.Name = &apos;Prospect&apos;),&apos;Prospect&apos;, 
&apos;&apos; ))))))</formula>
        <inlineHelpText>Type of lead or prospect based on how it entered Salesforce</inlineHelpText>
        <label>Current Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_REMergeTestDataFactory.cls
public class CCPM_REMergeTestDataFactory {

    /**
@author        Paras Shah (Deloitte)
@description   This method is used to create records
@param         ???? 
@return        ????
*/
    public Static CCPM_RERecord__c createRecords(String strUniqueRERecordName){
        CCPM_RERecord__c objRERecord = new CCPM_RERecord__c();
        objRERecord.CCPM_active__c = true;
        objRERecord.CCPM_primaryObject__c = 'Lead';
        objRERecord.CCPM_recordNameUnique__c = strUniqueRERecordName;
        //objRERecord.CCPM_RE_Record_ID__c = 
        
        return objRERecord;

    }    
    
    /**
@author        Paras Shah (Deloitte)
@description   This method is used to create rulese
@param         ???? 
@return        ????
*/
    public Static CCPM_Rule__c createRules(Id idExistingRERecord, Id idNewRecord,String strMergeUniqueField,String strWinningRecord,String strRERuleId){
        
        CCPM_Rule__c objRERuleRecord = new CCPM_Rule__c();
        objRERuleRecord.Name = 'Name';
        objRERuleRecord.CCPM_active__c = true;
        objRERuleRecord.CCPM_description__c = 'Sample Description';
        objRERuleRecord.CCPM_endDate__c = system.today();
        objRERuleRecord.CCPM_existingRecord__c = idExistingRERecord;
        objRERuleRecord.CCPM_mergeUniqueField__c = strMergeUniqueField;
        objRERuleRecord.CCPM_newRecord__c = idNewRecord;
        objRERuleRecord.CCPM_primaryObject__c = 'Lead';
        objRERuleRecord.CCPM_RE_Rule_ID__c = '999';
        objRERuleRecord.CCPM_startDate__c = system.today();
        objRERuleRecord.CCPM_winningRecord__c = strWinningRecord;
		
        return objRERuleRecord;
    }    
    
    /**
@author        Paras Shah (Deloitte)
@description   This method is used to create Action
@param         ???? 
@return        ????
*/
    public Static CCPM_Action__c createAction(String strActionID,String strRelatedObjectAction){
        
        CCPM_Action__c objAction = new CCPM_Action__c();
        objAction.Name = 'Name';
        objAction.CCPM_actionObject__c = 'Lead';
		objAction.CCPM_active__c = true;
		objAction.CCPM_description__c = 'Sample Decscription';
        objAction.CCPM_endDate__c = system.today();
        objAction.CCPM_masterObject__c = 'Lead';
        objAction.CCPM_RE_Action_ID__c = strActionID;
        objAction.CCPM_relatedObject__c = 'Task';
        objAction.CCPM_relatedObjectAction__c = strRelatedObjectAction;
        objAction.CCPM_startDate__c = system.today();
        objAction.CCPM_type__c = 'Insert';
        
        return objAction;
    }        

    /**
@author        Paras Shah (Deloitte)
@description   This method is used to create Action
@param         ???? 
@return        ????
*/
    public Static CCPM_ActionComponent__c createActionComponent(Id idActionID,String strFieldAPIName,String strActionComponentId){
        
        CCPM_ActionComponent__c objActionComponent = new CCPM_ActionComponent__c();
        objActionComponent.CCPM_Action__c = idActionID;
        objActionComponent.CCPM_active__c = true;
        objActionComponent.CCPM_fieldAPIName__c = strFieldAPIName;
		objActionComponent.CCPM_fieldValue__c = 'Sample Value';        
        objActionComponent.CCPM_mergeCopy__c = true;
        objActionComponent.CCPM_mergeCopyIfNullOrBlank__c = true;
        objActionComponent.CCPM_order__c = 123;
        objActionComponent.CCPM_RE_Action_Component_ID__c = strActionComponentId;
        objActionComponent.CCPM_variableName__c = 'Sample Name';
        
        return objActionComponent;
    }       
    
    /**
@author        Paras Shah (Deloitte)
@description   This method is used to create Action
@param         ???? 
@return        ????
*/
    public Static CCPM_Criteria__c createRuleCriteria(String strFieldType,String strOperator,Id idRERecord,id idRERuleRecord){
        
        CCPM_Criteria__c objCriteria = new CCPM_Criteria__c();
        
        objCriteria.CCPM_active__c = true;
        objCriteria.CCPM_fieldName__c = 'Sample field name';
        objCriteria.CCPM_fieldType__c = strFieldType;
        objCriteria.CCPM_operator__c = strOperator;
        objCriteria.CCPM_Record__c = idRERecord;
        objCriteria.CCPM_RE_Criteria_ID__c = '9999';
        objCriteria.CCPM_rule__c = idRERuleRecord;
        objCriteria.CCPM_valueDate__c = system.today();
        objCriteria.CCPM_valueDouble__c = 10.00;
        objCriteria.CCPM_valueText__c = 'Value Text';
        
        return objCriteria;
    }       
    
    /**
@author        Paras Shah (Deloitte)
@description   This method is used to create Action
@param         ???? 
@return        ????
*/
    public Static CCPM_RuleAction__c createRuleAction(Id idAction,String strRuleActionID,Id idRule){
        
        CCPM_RuleAction__c objRuleAction = new CCPM_RuleAction__c();
        objRuleAction.CCPM_action__c = idAction;
        objRuleAction.CCPM_active__c = true;
        objRuleAction.CCPM_RE_Rule_Action_ID__c = strRuleActionID;
        objRuleAction.CCPM_rule__c = idRule;
        
        return objRuleAction;
    }         
    
}