VZDEV/src/objects/CCPM_promoMessage__mdt.object
<CustomObject>
    <fields>
        <fullName>CCPM_MessageContentForLeads__c</fullName>
        <label>Message Content For Leads</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_dispalyOrignialMessage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dispaly Orginal Message</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_finalPreDefinedResponse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Pre Defined Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_firstPreDefinedResponse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Pre Defined Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_messageContentForProspects__c</fullName>
        <label>Message Content For Prospects</label>
        <type>TextArea</type>
    </fields>
    <label>Send  Pre Defined SMS</label>
    <pluralLabel>Send Pre Defined SMS</pluralLabel>
</CustomObject>

VZDEV/src/objects/CCPM_UIComponentSetting__mdt.object
<CustomObject>
    <description>Parameters required to be set for UI components Lightning.</description>
    <fields>
        <fullName>CCPM_orderByField__c</fullName>
        <description>Orders by a specific Field.</description>
        <inlineHelpText>Orders by a specific Field.</inlineHelpText>
        <label>Order By Field</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_order__c</fullName>
        <description>Metadata property to set the order by which the Query should sort Data</description>
        <inlineHelpText>Metadata property to set the order by which the Query should sort Data</inlineHelpText>
        <label>Order</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASC</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>DESC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_recordLimit__c</fullName>
        <label>Record Limit</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UI Component Setting</label>
    <pluralLabel>UI Component Settings</pluralLabel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSFollowUpDate__c</fullName>
        <inlineHelpText>The date &amp; time for the SMS to be scheduled to be sent</inlineHelpText>
        <label>SMS Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSResponseReceivedDateTime__c</fullName>
        <description>Holds the date/time when SMS response was received</description>
        <label>SMS Response Received Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_Type__c</fullName>
        <description>Type</description>
        <formula>IF(OR(AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = true),ISPICKVAL(CCPM_leadType__c,&apos;Customer SFDC Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales POS Manual&apos;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Telesales SFDC Manual&apos;)),&apos;Manual Lead&apos;, 
IF(OR(CONTAINS(TEXT(LeadSource), &quot;CRM&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Customer Campaign&apos;)),&apos;Campaign Lead&apos;, 
IF(OR(CONTAINS(TEXT(CCPM_leadType__c),&quot;Customer Abandoned Cart&quot;), AND(RecordType.Name = &apos;Customer Cart&apos; ,CCPM_isManualLead__c = false)),&apos;Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Abandoned Visit&apos;),&apos;Abandoned Visit Lead&apos;, 
IF(ISPICKVAL(CCPM_leadType__c,&apos;Customer Quotes&apos;),&apos;Quote Lead&apos;, 
IF(OR(ISPICKVAL(CCPM_leadType__c,&apos;Prospect SFDC Manual&apos;),CONTAINS(TEXT(CCPM_leadType__c),&quot;Prospect Abandoned Cart&quot;),ISPICKVAL(CCPM_leadType__c,&apos;Prospect Telesales SFDC Manual&apos;), RecordType.Name = &apos;Prospect Cart&apos;, RecordType.Name = &apos;Prospect&apos;),&apos;Prospect&apos;, 
&apos;&apos; ))))))</formula>
        <inlineHelpText>Type of lead or prospect based on how it entered Salesforce</inlineHelpText>
        <label>Current Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_eventType__c</fullName>
        <inlineHelpText>The Conversation Topic that requires an SMS follow up to be sent.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samsung GS9 BOGO</fullName>
                </value>
                <value>
                    <fullName>TMP OE - Q2 2018</fullName>
                </value>
                <value>
                    <fullName>Add a Line</fullName>
                </value>
                <value>
                    <fullName>Confirming with Family First</fullName>
                </value>
                <value>
                    <fullName>Connected Device</fullName>
                </value>
                <value>
                    <fullName>Contract Terminating Soon</fullName>
                </value>
                <value>
                    <fullName>Feature Add</fullName>
                </value>
                <value>
                    <fullName>Gift for Upcoming Occasion</fullName>
                </value>
                <value>
                    <fullName>iPhone X</fullName>
                </value>
                <value>
                    <fullName>iPhone X send message</fullName>
                </value>
                <value>
                    <fullName>New Service</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>Special Event</fullName>
                </value>
                <value>
                    <fullName>Tablets</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_finalPreDefinedResponse__c</fullName>
        <label>Final Pre Defined Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ok, thank you! Have a great day.</fullName>
                </value>
                <value>
                    <fullName>Ok, I’ll be reaching out to you via phone, shortly.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_finalPreDefinedSMSFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Pre Defined SMS Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_firstPreDefinedResponse__c</fullName>
        <label>First PreDefined Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ok, thanks! Please call our customer service department at 1-800-922-0204.</fullName>
                </value>
                <value>
                    <fullName>Ok, thanks! We will make the necessary changes.</fullName>
                </value>
                <value>
                    <fullName>Ok, thank you! Have a great day.</fullName>
                </value>
                <value>
                    <fullName>Yes, thank you! See you then.</fullName>
                </value>
                <value>
                    <fullName>Ok, I’ll be reaching out to you via phone, shortly.</fullName>
                </value>
                <value>
                    <fullName>What would be the best time to follow up with you via phone call?</fullName>
                </value>
                <value>
                    <fullName>-- None --</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, I’ll be reaching out to you via phone, shortly. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, thank you! Have a great day. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, thanks! Please call our customer service department at 1-800-922-0204. (Free VzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, thanks! We will make the necessary changes. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Ok, we will dismiss your cart. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Yes, thank you! See you then. (FreeVzMsg)</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_firstPredefinedSMSFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Predefined SMS Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_leadSubStatus__c</fullName>
        <description>This field is used to store the Lead Sub Status</description>
        <inlineHelpText>Populated when the status is “Responded” or “Qualified”</inlineHelpText>
        <label>Lead Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>Action Required</fullName>
                </value>
                <value>
                    <fullName>In Discussion</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Needs Store Reassignment</fullName>
                </value>
                <value>
                    <fullName>Service Issue</fullName>
                </value>
                <value>
                    <fullName>Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart-Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart Opt Out</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_ownerEcode__c</fullName>
        <formula>Owner:User.CCPM_commissionableRepID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Ecode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_storeEcode__c</fullName>
        <formula>(Store__r.CCPM_storeEcode__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Ecode</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_LeadsAwaitingResponseApexController.cls
/**
*@name          CCPM_myActiveLeadsApexController
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          12/07/2017
*@description   For "My Active Leads" Component in UI
Modification    Log:
------------------------------------------------------------------------------------
Developer                      				  Date               Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)             12/07/2017         Original Version       
*/
public with sharing class CCPM_LeadsAwaitingResponseApexController {
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   Method that queries and Loads data for Lead
*@return        wrapperClass
*/ 
    @AuraEnabled
    public static CCPM_leadsAwaitingResponseWrapper loadComponentWithRecords(string strSortBy,string strOrderby,string strLimit,string strOffSet){
        CCPM_leadsAwaitingResponseWrapper objwrapperClass = new CCPM_leadsAwaitingResponseWrapper();
        list<Lead> lstlead = new list<Lead>();
        List<CCPM_leadWrapper> lstLeadAndSMSOptns = new List<CCPM_leadWrapper>();
        CCPM_UIComponentSetting__mdt mdtUIComponentSetting=new CCPM_UIComponentSetting__mdt();
        System.debug('Values in Sort->'+strSortBy+strOrderby+strLimit+strOffSet);
        if(String.isBlank(strSortBy) || String.isBlank(strOrderby) || String.isBlank(strLimit))
        {
            mdtUIComponentSetting= CCPM_LeadsAwaitingResponseApexController.setQueryParam();
            strSortBy=mdtUIComponentSetting.CCPM_orderByField__c;
            strOrderby=mdtUIComponentSetting.CCPM_order__c;
            strLimit=mdtUIComponentSetting.CCPM_recordLimit__c;
        }
        
        integer intMaxSize= database.countQuery('select count() from Lead where Status=\''+CCPM_staticConstants.strLeadStatusResponded+'\' and CCPM_leadSubStatus__c=\''+CCPM_staticConstants.strLeadSubStatusActionRequired+'\'');
        objwrapperClass.intMaxSize=intMaxSize;
        string queryInitialString ='SELECT Id,CCPM_ownerEcode__c,CCPM_storeEcode__c,RecordTypeId,CCPM_firstPredefinedSMSFlag__c,CCPM_finalPreDefinedSMSFlag__c,Name,CCPM_mobileNumber__c,CCPM_SMSResponseReceivedDateTime__c,owner.name,CCPM_Type__c,CCPM_SMSFollowUpDate__c,CCPM_leadSubStatus__c,Status,CCPM_eventType__c, (select Id,Description,CreatedDate,CCPM_communicationDirection__c from tasks order by createddate desc) from lead where Status=\''+CCPM_staticConstants.strLeadStatusResponded+'\' and CCPM_leadSubStatus__c=\''+CCPM_staticConstants.strLeadSubStatusActionRequired+'\''+' ORDER BY '+strSortBy+' '+strOrderby+' NULLS LAST LIMIT '+strLimit+ ' OFFSET '+strOffSet;
        //where CCPM_communicationDirection__c=\''+ CCPM_staticConstants.strTaskCommunicationDirection+'\'
        System.debug('queryInitialString->+'+queryInitialString);
        for(Lead objLead : Database.query(queryInitialString)){
            boolean boolNeedsAttention = false;
            if(objLead.CCPM_SMSResponseReceivedDateTime__c!=null && objLead.CCPM_SMSResponseReceivedDateTime__c.addHours(6)<System.now())
            {
                boolNeedsAttention=true;
            }
            lstLeadAndSMSOptns.add(new CCPM_leadWrapper(objLead,boolNeedsAttention));
            system.debug('SMSResponse Received->'+objLead.CCPM_SMSResponseReceivedDateTime__c);
        }
        System.debug('lstLeadAndSMSOptns->'+lstLeadAndSMSOptns);
        if(lstLeadAndSMSOptns.size() > 0)
        {
            objwrapperClass.lstLeadWrapper=lstLeadAndSMSOptns;
        }
        if(mdtUIComponentSetting!=null)
        {
            objwrapperClass.metadataSettings=mdtUIComponentSetting;
        }
        
        return objwrapperClass;    
    }
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   Method that queries for Metadata settings to get the Limit in the query being used,Order By Field,Order
*@return        Metadata
*/ 
    @AuraEnabled
    public static CCPM_UIComponentSetting__mdt setQueryParam(){
        CCPM_UIComponentSetting__mdt mdtActiveLeadSettings = new CCPM_UIComponentSetting__mdt();
        mdtActiveLeadSettings = [select CCPM_orderByField__c,CCPM_order__c,CCPM_recordLimit__c from CCPM_UIComponentSetting__mdt where DeveloperName =:Label.CCPM_UIHomePageLARLabel];
        System.debug('Metadata Values returned from query->'+mdtActiveLeadSettings);
        return mdtActiveLeadSettings;
    }
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   Wrapper class to provision a datastructure containing collection of Objects
*@return        None
*/ 
    public class CCPM_leadsAwaitingResponseWrapper{
        @AuraEnabled public List<CCPM_leadWrapper> lstLeadWrapper{get;set;}
        @AuraEnabled public CCPM_UIComponentSetting__mdt metadataSettings{get;set;}
        @AuraEnabled public Integer intMaxSize{get;set;}
        
        // @AuraEnabled public Map<String,String> mapQualifiedSubStatus{get;set;}
        
        /*public CCPM_leadsAwaitingResponseWrapper()
{
mapQualifiedSubStatus = new Map<String,String>();
string strSubStatus = Label.CCPM_qualifiedSubStatus;
list<String> lstSubStatus = new list<String>();
lstSubStatus = strSubStatus.split(',');

for(String strOptions : lstSubStatus)
{
mapQualifiedSubStatus.put(strOptions,strOptions);
}
}*/
        
        
    }  
    
    /**
*@author        Bharath Ammanamanchi (Deloitte)
*@description   Wrapper class to provision a datastructure containing collection of Objects
*@return        None
*/ 
    public class CCPM_leadWrapper{
        @AuraEnabled public Lead objLead{get;set;}
        @AuraEnabled public Map<String, String> mapSmsMessage{get;set;}
        @AuraEnabled public boolean booldoesNeedAttention{get;set;}
        @AuraEnabled public boolean boolShowPopUp{get;set;}
        
        
        public CCPM_leadWrapper(Lead objLeadIn, boolean booldoesNeedAttentionIn){
            objLead = new Lead();
            objLead = objLeadIn;
            booldoesNeedAttention=booldoesNeedAttentionIn;
            boolShowPopUp=false;
            mapSmsMessage = new Map<String, String>();
            if(Label.CCPM_none!=null)
            {
                mapSmsMessage.put(Label.CCPM_none, Label.CCPM_none);
                
                
            }
            if(CCPM_Collection.isNotNullEmpty(CCPM_utility.lstPreDefinedSMSRecords) && !objLeadIn.CCPM_finalPreDefinedSMSFlag__c){
                for(CCPM_promoMessage__mdt mdtPM : CCPM_utility.lstPreDefinedSMSRecords){
                    if(mdtPM.MasterLabel != 'Custom Reply'){
                        String strMsg = '';
                        if(objLeadIn.CCPM_firstPredefinedSMSFlag__c){
                            if(mdtPM.CCPM_finalPreDefinedResponse__c){
                                strMsg = getSMSPickListDisplayValue(objLead, mdtPM);
                            }
                        }
                        else {
                            if(mdtPM.CCPM_firstPreDefinedResponse__c){
                                strMsg = getSMSPickListDisplayValue(objLead, mdtPM);
                            }
                        }
                        if(String.isNotBlank(strMsg)){
                            mapSmsMessage.put(mdtPM.DeveloperName, strMsg);
                        }
                    }
                }            
            }	
            System.debug('MapSMSMessage->'+mapSmsMessage);
        }
        
        public String getSMSPickListDisplayValue(Lead objLead, CCPM_promoMessage__mdt mdtPM){
            String strLeadCustomerCartRT = Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.CCPM_leadCustomerCartRT).getRecordTypeId();
            String strLeadCustomerAbandonedVisit = Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.CCPM_CustomerAbandonedVisitlead).getRecordTypeId();
            String strLeadCustomerQuoteRT = Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.CCPM_CustomerQuotesRT).getRecordTypeId();
            Set<String> setCustomerRecordTypeids = new Set<String>{strLeadCustomerCartRT,strLeadCustomerAbandonedVisit,strLeadCustomerQuoteRT};
            String strMsg = mdtPM.MasterLabel;
            if(mdtPM.CCPM_dispalyOrignialMessage__c){
                if(objLead.RecordTypeId == Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.CCPM_LeadProspectRecordType).getRecordTypeId()){
                    strMsg = CCPM_utility.checkForDynamicContentInMsg('', mdtPM.CCPM_messageContentForProspects__c);    
                }
                else if(setCustomerRecordTypeids.contains(objLead.RecordTypeId)){
                    strMsg = CCPM_utility.checkForDynamicContentInMsg('(FreeVzMsg)', mdtPM.CCPM_MessageContentForLeads__c);
                }    
            }
            return strMsg;
        }
    }
    
    @AuraEnabled
    public static Boolean getUserRole() {
        
        Boolean result = false;
        String roleId = userinfo.getUserRoleId();       
        if (String.isNotBlank(roleId)) {
            userRole objRole = [Select id, name 
                                From UserRole 
                                where id=:UserInfo.getUserRoleId()];
            
            if (objRole != null && (objRole.name.tolowercase().contains('solutions') 
                                    || objRole.name.tolowercase().contains('solutions'))) {
                                        result = true;
                                    }
        }
        return result;
    }
    
}