VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <fields>
        <fullName>CCPM_LiveTextNumber__c</fullName>
        <description>Stores the Live Text Number Used.</description>
        <inlineHelpText>Stores the Live Text Number Used.</inlineHelpText>
        <label>Live Text Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_MessageStatus__c</fullName>
        <description>Refers to the status of the Message sent based on response code.</description>
        <inlineHelpText>Refers to the status of the Message sent based on response code.</inlineHelpText>
        <label>Message Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Resend Failed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_ScheduleDateTime__c</fullName>
        <description>Refers to the Date/Time the SMS is to be sent.</description>
        <inlineHelpText>Refers to the Date/Time the SMS is to be sent.</inlineHelpText>
        <label>Schedule Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_communicationDirection__c</fullName>
        <description>Refers tot the communication Direction.</description>
        <inlineHelpText>Refers tot the communication Direction.</inlineHelpText>
        <label>Communication Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_leadRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the associated lead.</description>
        <inlineHelpText>Refers to the associated lead.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>SMS Messages</relationshipLabel>
        <relationshipName>SMS_Message_Sent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_messageType__c</fullName>
        <description>Indicates the type of SMS being sent.</description>
        <inlineHelpText>Indicates the type of SMS being sent.</inlineHelpText>
        <label>Message Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_message__c</fullName>
        <description>Message body to be sent.</description>
        <inlineHelpText>Message body to be sent.</inlineHelpText>
        <label>Message</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_requestID__c</fullName>
        <label>RequestID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_responseCode__c</fullName>
        <description>Response codes recorded for each API call made</description>
        <label>Response Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_responseMessage__c</fullName>
        <description>Captures the Response Message for the Heywire API callout made.</description>
        <inlineHelpText>Captures the Response Message for the Heywire API callout made.</inlineHelpText>
        <label>Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_smssentactualtime__c</fullName>
        <description>This field stores the time the SMS was actually sent out from Heroku</description>
        <inlineHelpText>This field stores the time the SMS was actually sent out from Heroku</inlineHelpText>
        <label>SMS Sent Actual Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_toPhoneNumber__c</fullName>
        <description>Refers to the number the SMS should be sent.</description>
        <inlineHelpText>Refers to the number the SMS should be sent.</inlineHelpText>
        <label>To Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_SMSMessageTriggerHandler.cls
/**
*@name          CCPM_SMSMessageTriggerHandler
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          06/14/2017
@description    US-500, US-498:SMS Message Trigger to update Lead fields and create tasks for associated Leads
@testClass      
Modification    Log:
------------------------------------------------------------------------------------
Developer               				Date                     Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)      06/14/2017              Original Version
*/
public class CCPM_SMSMessageTriggerHandler {
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   Create Part 2 SMS messages with status sent
@param         list of CCPM_SMSMessage__c
@return        Void(None)
*/ 
    public static void InsertSMSMessageRecordsforPart2BeforeUpdate(List<CCPM_SMSMessage__c> lstNewSMSMessages)
    {	
        try{
            System.debug('# List lstNewSMSMessagesPart2-> ' + lstNewSMSMessages);
            insert lstNewSMSMessages;
            System.debug('# Insert Task DML Operation-> ' + lstNewSMSMessages); 
        }
        catch(DMLException e)
        {
            CCPM_LogMessageUtility.logMessage(e,'CCPM_SMSMessageTriggerHandler','Insert Part 2 SMS sent','Exception thrown during Insert',true);
        } 
        
    }
    
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   Update SMS body for part1 and create Part2 in salesforce
@param         list of new CCPM_SMSMessage__c, Map of Old CCPM_SMSMessage__c
@return        Void(None)
*/  
    public static void UpdateSMSMessageRecordsforPart1BeforeUpdate(List<CCPM_SMSMessage__c> lstNewSMSMessages,map<id,CCPM_SMSMessage__c> mapOldSMSMessages)
    {	
        list<CCPM_SMSMessage__c> lstSMSMessagePart2 = new list<CCPM_SMSMessage__c>(); 
        for(CCPM_SMSMessage__c SMS : lstNewSMSMessages)
        {
            if(mapOldSMSMessages.get(SMS.Id).CCPM_MessageStatus__c!=SMS.CCPM_MessageStatus__c && SMS.CCPM_MessageStatus__c==CCPM_staticConstants.strMessageStatusSent )
            {
                if(SMS.CCPM_messageType__c==CCPM_staticConstants.strMessageTypeInitialSMSPart1)
                {
                    lstSMSMessagePart2.addAll(generateSecondSMSPart(SMS,CCPM_staticConstants.strMessageTypeInitialSMSPart2));
                }
                else if(SMS.CCPM_messageType__c==CCPM_staticConstants.strMessageTypeCampaignInitialSMSPart1)
                {
                    lstSMSMessagePart2.addAll(generateSecondSMSPart(SMS,CCPM_staticConstants.strMessageTypeCampaignInitialSMSPart2));
                    
                }
                else if(SMS.CCPM_messageType__c== CCPM_staticConstants.strMessageTypeProspectFirstSMSPart1)
                {
                    lstSMSMessagePart2.addAll(generateSecondSMSPart(SMS,CCPM_staticConstants.strMessageTypeProspectFirstSMSPart2));
                }
                else if(SMS.CCPM_messageType__c== Label.CCPM_customerQuoteSMSPart1)
                {
                    lstSMSMessagePart2.addAll(generateSecondSMSPart(SMS,Label.CCPM_customerQuoteSMSPart2)); 
                }
               else if(SMS.CCPM_messageType__c== Label.CCPM_abandonedVisitInitialSMS)
                {
                    lstSMSMessagePart2.addAll(generateSecondSMSPart(SMS,Label.CCPM_AbandonedVisitInitialSMSPartII)); 
                }
                
            } 
            
        }
        
        if(lstSMSMessagePart2!=null && lstSMSMessagePart2.size()>0)
        {
            InsertSMSMessageRecordsforPart2BeforeUpdate(lstSMSMessagePart2);
        }
    } 
    
   
    /**
@author        Brigadesh Chandrasekar(Deloitte)
@description   Return Second Part of SMS to be created
@param         CCPM_SMSMessage__c
@return        list of CCPM_SMSMessage__c
*/ 
    public static list<CCPM_SMSMessage__c> generateSecondSMSPart(CCPM_SMSMessage__c objSMS,String strMessageType){
        list<CCPM_SMSMessage__c> lstSMSMessagePart2Temp = new list<CCPM_SMSMessage__c>(); 
        
        list<String> lstSMSBody = objSMS.CCPM_message__c.split('%');
        list<String> lstRequestID = objSMS.CCPM_requestID__c.split('\\^');
        system.debug('lstRequestID->'+lstRequestID);
        objSMS.CCPM_message__c= lstSMSBody[0];
        objSMS.CCPM_requestID__c = lstRequestID[0];
        lstSMSMessagePart2Temp.add(new CCPM_SMSMessage__c(CCPM_communicationDirection__c=objSMS.CCPM_communicationDirection__c,CCPM_leadRecord__c=objSMS.CCPM_leadRecord__c,
                                                      CCPM_LiveTextNumber__c=objSMS.CCPM_LiveTextNumber__c,CCPM_message__c=lstSMSBody[1],CCPM_MessageStatus__c=objSMS.CCPM_MessageStatus__c,CCPM_requestID__c = lstRequestID[1],
                                                      CCPM_responseCode__c=objSMS.CCPM_responseCode__c , CCPM_responseMessage__c = objSMS.CCPM_responseMessage__c, CCPM_messageType__c=strMessageType,
                                                      CCPM_ScheduleDateTime__c=objSMS.CCPM_ScheduleDateTime__c,CCPM_toPhoneNumber__c=objSMS.CCPM_toPhoneNumber__c,CCPM_smssentactualtime__c = objSMS.CCPM_smssentactualtime__c));
        
        return lstSMSMessagePart2Temp;
        
        
    }
    
}