VZDEV/src/objects/CCPM_CartType__c.object
<CustomObject>
    <description>To store Cart Types Records</description>
    <fields>
        <fullName>CCPM_CartType__c</fullName>
        <description>Cart Type for the Lead record</description>
        <label>Cart Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Cart Type</label>
    <nameField>
        <label>Cart Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>Unique Id of the store (data mastered in KRONOS)</description>
        <externalId>true</externalId>
        <label>Store ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SKU__c</fullName>
        <description>Product SKU&apos;s in the cart</description>
        <inlineHelpText>IDs of the products that are in the individual&apos;s cart&apos;</inlineHelpText>
        <label>SKU</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSFollowUpDate__c</fullName>
        <inlineHelpText>The date &amp; time for the SMS to be scheduled to be sent</inlineHelpText>
        <label>SMS Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Suppress SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartID__c</fullName>
        <description>Unique reference id of the cart</description>
        <externalId>true</externalId>
        <label>Cart ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartModifiedDate__c</fullName>
        <label>Cart Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_cartType__c</fullName>
        <description>PRP (feature change) | ACC (accessory only) | AAL (add a line) | EUP (equipment upgrade) | NEW (new customer order)</description>
        <inlineHelpText>PRP (feature change) | ACC (accessory only) | AAL (add a line) | EUP (equipment upgrade) | NEW (new customer order)</inlineHelpText>
        <label>Cart Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_cartUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique Identified to create/update carts(leads). The format will be &apos;A:&apos;+Account Number&apos; +&apos;-M:&apos; + Mobile Number + &apos;-S:&apos; + Lead Status. This field will be used to upset leads in Salesforce for carts (leads) for existing customers.</description>
        <externalId>true</externalId>
        <label>Cart Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_cartlastHandledBy__c</fullName>
        <description>ID of the rep who last handled the cart</description>
        <label>Cart Last Handled By</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_createdDate__c</fullName>
        <label>Cart Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_creditApplicationNo__c</fullName>
        <description>Credit application number</description>
        <label>Credit Application No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_creditClass__c</fullName>
        <description>Credit Class of the credit application</description>
        <label>Credit Class</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <description>Email address specified by the customer when creating the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Email of the lead / prospect. Required to save a Prospect if the MTN is unavailable.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_eventType__c</fullName>
        <inlineHelpText>The Conversation Topic that requires an SMS follow up to be sent.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samsung GS9 BOGO</fullName>
                </value>
                <value>
                    <fullName>TMP OE - Q2 2018</fullName>
                </value>
                <value>
                    <fullName>Add a Line</fullName>
                </value>
                <value>
                    <fullName>Confirming with Family First</fullName>
                </value>
                <value>
                    <fullName>Connected Device</fullName>
                </value>
                <value>
                    <fullName>Contract Terminating Soon</fullName>
                </value>
                <value>
                    <fullName>Feature Add</fullName>
                </value>
                <value>
                    <fullName>Gift for Upcoming Occasion</fullName>
                </value>
                <value>
                    <fullName>iPhone X</fullName>
                </value>
                <value>
                    <fullName>iPhone X send message</fullName>
                </value>
                <value>
                    <fullName>New Service</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>Special Event</fullName>
                </value>
                <value>
                    <fullName>Tablets</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_isManualLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if Prospect is Embedded Account</description>
        <inlineHelpText>if check Prospect is Embedded Account</inlineHelpText>
        <label>Manual Lead?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_lastInteraction__c</fullName>
        <description>Date/Time being recorded for last interaction between the customer and Heywire process in salesforce</description>
        <label>Last Interaction Date/TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mergeMasterID__c</fullName>
        <description>Merge Master Prospect Record ID</description>
        <inlineHelpText>Merge Master Prospect Record ID</inlineHelpText>
        <label>Merge Master Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_sendLeadsRequiringActionSMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to trigger the SMS to Store Managers and Assistant Managers to Trigger SMS for Leads or Prospects Requiring Action</description>
        <label>Send Leads Requiring Action SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_storeID__c</fullName>
        <description>ID of store / outlet where customer has transacted</description>
        <label>Store ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_tobeMerged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Merge Flag for the Prospect Cart</description>
        <inlineHelpText>Merge Flag for the Prospect Cart</inlineHelpText>
        <label>To Be Merged ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>US-0024 :: Reference of the nearest store of the prospect based on customer&apos;s history</description>
        <inlineHelpText>Verizon store that this lead is associated with.</inlineHelpText>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_mergeLeadCartsWithManualLeadsTest.cls
/**
*@name          CCPM_mergeProspectCartWithProspectTest 
*@author        Sudhakara Reddy Nallamilli (Deloitte)
*@date          05/25/2017
@description    This is the Unit Test Class for the Leads Merging Functionality
                  
@testClass      
Modification    Log: US-429, US-495, US-496 and US-497
------------------------------------------------------------------------------------
Developer               Date                                Description
------------------------------------------------------------------------------------
Sudhakara Reddy Nallamilli (Deloitte)    05/04/2017          Original Version
*/
@isTest(SeeAllData=false)
private class CCPM_mergeLeadCartsWithManualLeadsTest {

    static testMethod void mergeLeadCartsWithManualLeadsUnitTest() {
        // TO DO: implement unit test
        list<lead> lstManualLeads = new list<lead>();
        list<lead> lstLeadCarts = new list<lead>(); 
        list<CCPM_Store__c> lstStoreObj = new list<CCPM_Store__c>();   
        CCPM_Store__c objStore = new CCPM_Store__c();
                 
        CCPM_testDataFactory.createCustomSetting();
         // Creating the Store Data using Test Data Factory
        lstStoreObj = CCPM_testDataFactory.createStore(1);
        if(lstStoreObj != NULL && !lstStoreObj.isEmpty() )
        {
         objStore.Id = lstStoreObj[0].Id;
         objStore.Name = lstStoreObj[0].Name;
         objStore.CCPM_storeID__c = lstStoreObj[0].CCPM_storeID__c;         
        } 
        
        
        // Populating Test Data with the Lead Record Type for the Prospects
        lead l1 = new lead();
 // Scenario with MTN on Prospect       
        l1.LastName = 'ABCMergeMLOne';
        l1.FirstName = 'TestingMLOne';
        l1.Status = 'New';
        l1.CCPM_accountUniqueID__c = 'MergeML1';
        l1.CCPM_isManualLead__c = true;
        l1.CCPM_leadType__c = 'Customer SFDC Manual';
        l1.CCPM_lastInteraction__c = system.now().addHours(-5);
        l1.CCPM_mobileNumber__c = '9999999991';
        l1.Company = '1';
        l1.LeadSource = 'ATG-ECOM-DESK';
        l1.CCPM_sendLeadsRequiringActionSMS__c = false;
        l1.CCPM_storeID__c = objStore.CCPM_storeID__c;
        l1.store__c = objStore.Id;
        l1.CCPM_tobeMerged__c = false;
        l1.CCPM_SMSLegalOptIn__c = true; 
   //     l1.CCPM_eventType__c = 'Other Event';
        l1.CCPM_SMSFollowUpDate__c = system.now().addDays(1);

        lstManualLeads.add(l1);
        
        
        // Populating Test Data with the Lead Record Type for the Prospects
        lead l2 = new lead();
 // Scenario with MTN on Prospect       
        l2.LastName = 'ABCMergeMLTwo';
        l2.FirstName = 'TestingMLTwo';
        l2.Status = 'New';
        l2.CCPM_accountUniqueID__c = 'MergeML2';
        l2.CCPM_isManualLead__c = true;
        l2.CCPM_leadType__c = 'Customer SFDC Manual';
        l2.CCPM_lastInteraction__c = system.now().addHours(-5);
        l2.CCPM_mobileNumber__c = '9999999992';
        l2.Company = '1';
        l2.LeadSource = 'ATG-ECOM-DESK';
        l2.CCPM_sendLeadsRequiringActionSMS__c = false;
        l2.CCPM_storeID__c = objStore.CCPM_storeID__c;
        l2.store__c = objStore.Id;
        l2.CCPM_tobeMerged__c = false;
        l2.CCPM_SMSLegalOptIn__c = true; 
   //     l1.CCPM_eventType__c = 'Other Event';
        l2.CCPM_SMSFollowUpDate__c = system.now().addDays(1);

        lstManualLeads.add(l2);
        
            // Populating Test Data with the Lead Record Type for the Prospects
        lead l3 = new lead();
 // Scenario with MTN on Prospect       
        l3.LastName = 'ABCMergeMLThree';
        l3.FirstName = 'TestingMLThree';
        l3.Status = 'New';
        l3.CCPM_accountUniqueID__c = 'MergeML3';
        l3.CCPM_isManualLead__c = true;
        l3.CCPM_leadType__c = 'Customer SFDC Manual';
        l3.CCPM_lastInteraction__c = system.now().addHours(-5);
        //l3.CCPM_mobileNumber__c = '9999999992';
        l3.CCPM_email__c = 'abc@gmail.com';
        l3.Company = '1';
        l3.LeadSource = 'ATG-ECOM-DESK';
        l3.CCPM_sendLeadsRequiringActionSMS__c = false;
        l3.CCPM_storeID__c = objStore.CCPM_storeID__c;
        l3.store__c = objStore.Id;
        l3.CCPM_tobeMerged__c = false;
        l3.CCPM_SMSLegalOptIn__c = true; 
   //     l1.CCPM_eventType__c = 'Other Event';
        l3.CCPM_SMSFollowUpDate__c = system.now().addDays(1);

        lstManualLeads.add(l3);
        
        Id [] fixedSearchResults= new Id[15];

  // Creating the Prospects
       if(lstManualLeads!=null && lstManualLeads.size()>0 && !lstManualLeads.isEmpty())
       {
         insert lstManualLeads;
         integer i = 0;
        for(lead objManualLead: lstManualLeads)
        {
          if(i < 10) fixedSearchResults[i] = objManualLead.id;
          i++;
        }
       
       }
       
       lead lc1 = new lead();
 // Scenario with MTN on and No Merge Master ID and TobeMerged flag is true on Prospect Cart   
        lc1.LastName = 'ABCMergeMLCOne';
        lc1.FirstName = 'TestingMLCOne';
        lc1.CCPM_LeadType__c = 'Customer Abandoned Cart Digital';
        lc1.Status = 'New';
        lc1.CCPM_SMSOptOut__c = true;
        lc1.CCPM_cartUniqueID__c = 'MergeMLC1';
        lc1.CCPM_accountUniqueID__c = 'MergeMLC1';
        lc1.CCPM_lastInteraction__c = system.now().addHours(-5);
        lc1.Company = '3';
        lc1.LeadSource = 'ATG-ECOM-GGDESK';
        lc1.CCPM_mobileNumber__c = '9999999991';
        lc1.CCPM_sendLeadsRequiringActionSMS__c = false;
        lc1.CCPM_tobeMerged__c = true;
        lc1.CCPM_SMSLegalOptIn__c = true; 
        lc1.CCPM_storeID__c = objStore.CCPM_storeID__c;
        lc1.store__c = objStore.Id;
   //     lc1.CCPM_eventType__c = 'Other Event';
        lc1.CCPM_SMSFollowUpDate__c = system.now().addDays(1);
        
        lstLeadCarts.add(lc1);
  
        lead lc2 = new lead();
        
 // Scenario with MTN on and with Email and With Merge Master ID and TobeMerged flag is true on Prospect Cart  
        lc2.LastName = 'ABCMergeMLCTwo';
        lc2.FirstName = 'TestingMLCTwo';
        lc2.CCPM_leadType__c = 'Customer Abandoned Cart Digital';
        lc2.Status = 'New';
        lc2.CCPM_accountUniqueID__c = 'MergeMLC2';
        lc2.CCPM_cartUniqueID__c = 'MergeMLC2';
        lc2.CCPM_lastInteraction__c = system.now().addHours(-1);
        lc2.Company = '4';
        lc2.LeadSource = 'ATG-ECOM-DESK';
        lc2.CCPM_mobileNumber__c = '9999999992'; 
        lc2.CCPM_sendLeadsRequiringActionSMS__c = false;
   //     lc2.CCPM_mergeMasterID__c = lstLeadProspect[1].ID;
        lc2.CCPM_tobeMerged__c = true;
        lc2.CCPM_SMSLegalOptIn__c = true; 
        lc2.CCPM_cartID__c = 'MergeMLC2';
       // lc2.CCPM_email__c = 'abc@gmail.com';
        lc2.CCPM_cartlastHandledBy__c = 'MergeMLC2';
        lc2.CCPM_createdDate__c = system.now().addHours(-10);
        lc2.CCPM_cartModifiedDate__c = system.now().addHours(-1);
        lc2.CCPM_cartType__c = 'TestType';
        lc2.CCPM_SKU__c = 'Test';
        lc2.Phone = '9999999991';
        lc2.PostalCode = '43016';
        lc2.CCPM_creditApplicationNo__c = 12345;
        lc2.CCPM_creditClass__c = 'TestClass';
        lc2.CCPM_storeID__c = objStore.CCPM_storeID__c;
        lc2.store__c = objStore.Id;
//        lc2.CCPM_eventType__c = 'Other Event';
        lc2.CCPM_SMSFollowUpDate__c = system.now().addDays(1);
       
        lstLeadCarts.add(lc2); 
        
        lead lc3 = new lead();
 // Scenario with MTN on and No Merge Master ID and TobeMerged flag is true on Prospect Cart   
        lc3.LastName = 'ABCMergeMLCThree';
        lc3.FirstName = 'TestingMLCThree';
        lc3.CCPM_leadType__c = 'Customer Abandoned Cart Digital';
        lc3.Status = 'New';
        lc3.CCPM_SMSOptOut__c = true;
        lc3.CCPM_cartUniqueID__c = 'MergeMLC';
        lc3.CCPM_accountUniqueID__c = 'MergeMLC3';
        lc3.CCPM_lastInteraction__c = system.now().addHours(-5);
        lc3.Company = '3';
        lc3.LeadSource = 'ATG-ECOM-GGDESK';
    //    lc3.CCPM_mobileNumber__c = '9999999991';
        lc3.CCPM_email__c = 'abc@gmail.com';
        lc3.CCPM_sendLeadsRequiringActionSMS__c = false;
        lc3.CCPM_tobeMerged__c = true;
        lc3.CCPM_SMSLegalOptIn__c = true; 
        lc3.CCPM_storeID__c = objStore.CCPM_storeID__c;
        lc3.store__c = objStore.Id;
   //     lc3.CCPM_eventType__c = 'Other Event';
        lc3.CCPM_SMSFollowUpDate__c = system.now().addDays(1);
        
        lstLeadCarts.add(lc3);
        
   //     test.startTest();
        if(lstLeadCarts!=null && !lstLeadCarts.isEmpty())
        {          
          insert lstLeadCarts;
          Test.setFixedSearchResults(fixedSearchResults);
        //  system.assertNotEquals(null,lstLeadCarts); 
        }
     //   test.stopTest(); 
        
         // Creating the object for the scheduler class and invoking the execution
        String CRON_EXP = ccpm_staticConstants.StrCRONInt; 
        CCPM_mergeLeadCartsWithManualLeadsJob sch = new CCPM_mergeLeadCartsWithManualLeadsJob(); 
        sch.scheduleIt();
     
        // Creating the object for the Batch Class and invoking the batch execution  
        CCPM_mergeLeadCartsWithManualLeadsBatch objLeadMergeBatch = new CCPM_mergeLeadCartsWithManualLeadsBatch();
        database.executebatch(objLeadMergeBatch,25);         
        
    }

    static testMethod void mergeLeadCartsWithManualLeadsUnitTestTwo() 
    {
         // TO DO: implement unit test
        list<lead> lstManualLeads = new list<lead>();
        list<lead> lstLeadCarts = new list<lead>(); 
        list<CCPM_Store__c> lstStoreObj = new list<CCPM_Store__c>();   
        CCPM_Store__c objStore = new CCPM_Store__c();
                 
        CCPM_testDataFactory.createCustomSetting();
         // Creating the Store Data using Test Data Factory
        lstStoreObj = CCPM_testDataFactory.createStore(1);
        if(lstStoreObj != NULL && !lstStoreObj.isEmpty() )
        {
         objStore.Id = lstStoreObj[0].Id;
         objStore.Name = lstStoreObj[0].Name;
         objStore.CCPM_storeID__c = lstStoreObj[0].CCPM_storeID__c;         
        } 
        
        
        // Populating Test Data with the Lead Record Type for the Prospects
        lead l1 = new lead();
 // Scenario with MTN on Prospect       
        l1.LastName = 'ABCMergeMLOne';
        l1.FirstName = 'TestingMLOne';
        l1.Status = 'New';
        l1.CCPM_accountUniqueID__c = 'MergeML1';
        l1.CCPM_isManualLead__c = true;
        l1.RecordTypeId = CCPM_staticConstants.strLeadCustomerAbandonedCartRecordTypeID;
        l1.CCPM_leadType__c = 'Customer Abandoned Cart Digital';
        l1.CCPM_lastInteraction__c = system.now().addHours(-5);
        l1.CCPM_mobileNumber__c = '9999999991';
        l1.Company = '1';
        l1.LeadSource = 'ATG-ECOM-DESK';
        l1.CCPM_sendLeadsRequiringActionSMS__c = false;
        l1.CCPM_storeID__c = objStore.CCPM_storeID__c;
        l1.store__c = objStore.Id;
        l1.CCPM_tobeMerged__c = false;
        l1.CCPM_SMSLegalOptIn__c = true; 
   //     l1.CCPM_eventType__c = 'Other Event';
        l1.CCPM_SMSFollowUpDate__c = system.now().addDays(1);

        lstManualLeads.add(l1);
        
        
        // Populating Test Data with the Lead Record Type for the Prospects
        lead l2 = new lead();
 // Scenario with MTN on Prospect       
        l2.LastName = 'ABCMergeMLTwo';
        l2.FirstName = 'TestingMLTwo';
        l2.Status = 'New';
        l2.CCPM_accountUniqueID__c = 'MergeML2';
        l2.CCPM_isManualLead__c = true;
        l2.CCPM_leadType__c = 'Customer SFDC Manual';
        l2.CCPM_lastInteraction__c = system.now().addHours(-5);
        l2.CCPM_mobileNumber__c = '9999999991';
        l2.Company = '1';
        l2.LeadSource = 'ATG-ECOM-DESK';
        l2.CCPM_sendLeadsRequiringActionSMS__c = false;
        l2.CCPM_storeID__c = objStore.CCPM_storeID__c;
        l2.store__c = objStore.Id;
        l2.CCPM_tobeMerged__c = false;
        l2.CCPM_SMSLegalOptIn__c = true; 
   //     l1.CCPM_eventType__c = 'Other Event';
        l2.CCPM_SMSFollowUpDate__c = system.now().addDays(1);

        lstManualLeads.add(l2);
        
       Id [] fixedSearchResults= new Id[15];

      // Creating the Prospects
       if(lstManualLeads!=null && lstManualLeads.size()>0 && !lstManualLeads.isEmpty())
       {
         insert lstManualLeads;
         integer i = 0;
        for(lead objManualLead: lstManualLeads)
        {
          if(i < 10) fixedSearchResults[i] = objManualLead.id;
          i++;
        }
       
       }    
        // Creating the object for the scheduler class and invoking the execution
        String CRON_EXP = ccpm_staticConstants.StrCRONInt; 
        CCPM_mergeLeadCartsWithManualLeadsJob sch = new CCPM_mergeLeadCartsWithManualLeadsJob(); 
        sch.scheduleIt();
     
        // Creating the object for the Batch Class and invoking the batch execution  
        CCPM_mergeLeadCartsWithManualLeadsBatch objLeadMergeBatch = new CCPM_mergeLeadCartsWithManualLeadsBatch();
        database.executebatch(objLeadMergeBatch,25);  
        
    }    
    
}