VZDEV/src/objects/CCPM_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule</label>
        <referenceTo>CCPM_Rule__c</referenceTo>
        <relationshipLabel>Criterias</relationshipLabel>
        <relationshipName>CCPM_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RE Criteria</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Criteria Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Rule__c.object
<CustomObject>
    <label>RE Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_RuleAction__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_rule__c</fullName>
        <label>Rule</label>
        <referenceTo>CCPM_Rule__c</referenceTo>
        <relationshipLabel>RE Rule Actions</relationshipLabel>
        <relationshipName>CCPM_RERuleActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RE Rule Action</label>
    <nameField>
        <displayFormat>RA{00000}</displayFormat>
        <label>Rule Action Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_RERuleControllerTest.cls
/**
*@name          CCPM_RERuleControllerTest 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          03/21/2018
*@description   This is a Test class for CCPM_RERuleController
*@Class         CCPM_RERuleControllerTest
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    03/21/2018   Initial Implementation.
*/

@isTest
private class CCPM_RERuleControllerTest {
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  This is the constructor
	@param        N/A
	@return       Void(None)
	*/ 
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        CCPM_RERuleController objRERuleController = new CCPM_RERuleController();
        objRERuleController.save();
        objRERuleController.getFieldTypes();
        objRERuleController.setFieldType();
        objRERuleController.removeCriteriaRow();
        objRERuleController.removeRuleActionRow();
        objRERuleController.edit();
        objRERuleController.cloneRulePackage();
        
        CCPM_Rule__c objRule = new CCPM_Rule__c();
        List<CCPM_Criteria__c> lstcriteria = new List<CCPM_Criteria__c>();
        List<CCPM_RuleAction__c> lstRuleAction = new List<CCPM_RuleAction__c>();
        
        CCPM_RERuleController.RERulePackage objRERulePackage = new CCPM_RERuleController.RERulePackage(objRule,lstcriteria,lstRuleAction);
        objRERulePackage.addCriteriaRow();
            objRERulePackage.addRuleActionRow();
    }
}