VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <fields>
        <fullName>CCPM_MessageStatus__c</fullName>
        <description>Refers to the status of the Message sent based on response code.</description>
        <inlineHelpText>Refers to the status of the Message sent based on response code.</inlineHelpText>
        <label>Message Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Resend Failed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_ScheduleDateTime__c</fullName>
        <description>Refers to the Date/Time the SMS is to be sent.</description>
        <inlineHelpText>Refers to the Date/Time the SMS is to be sent.</inlineHelpText>
        <label>Schedule Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_leadRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the associated lead.</description>
        <inlineHelpText>Refers to the associated lead.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>SMS Messages</relationshipLabel>
        <relationshipName>SMS_Message_Sent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_messageType__c</fullName>
        <description>Indicates the type of SMS being sent.</description>
        <inlineHelpText>Indicates the type of SMS being sent.</inlineHelpText>
        <label>Message Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_toPhoneNumber__c</fullName>
        <description>Refers to the number the SMS should be sent.</description>
        <inlineHelpText>Refers to the number the SMS should be sent.</inlineHelpText>
        <label>To Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_SMSSchedulesToBeRemoved__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>SMS Schedules To Be Removed</label>
    <nameField>
        <displayFormat>SMS2R-{00}</displayFormat>
        <label>SMS Schedules To Be Removed</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Schedules To Be Removed</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_RemoveSmsScheduleBatchHandler.cls
/**
*@name          RemoveSmsScheduleBatch
*@author        Sriraman Sridharan (Deloitte)
*@date          07/13/2017
@description    Handler class to remove the sms schedules
@testClass      
Modification    Log:
------------------------------------------------------------------------------------
Developer             				  Date                                Description
------------------------------------------------------------------------------------
Sriraman Sridharan(Deloitte)        07/14/2017                       Original Version
*/

public class CCPM_RemoveSmsScheduleBatchHandler {
    
    /**
*@author        Sriraman Sridharan (Deloitte)
*@description   This method removes the schedules
*@Params		List<CCPM_SMSSchedulesToBeRemoved__c>
*@return        Void(None)
*/ 
    
    Public static void CCPM_RemoveSmsScehdules(List<CCPM_SMSSchedulesToBeRemoved__c> lstSchedulesToBeRemoved){
        //Check if the parameter is not null and process it
        if(lstSchedulesToBeRemoved != null && lstSchedulesToBeRemoved.size()>0){
            
            //get the list of sms schedules to be removed
            List<CCPM_SMSMessage__c> lstSmsSchedulesToBeUpdated = getSMSScheduleList(lstSchedulesToBeRemoved);
            
            if(lstSmsSchedulesToBeUpdated != null && lstSmsSchedulesToBeUpdated.size()>0){
                for(CCPM_SMSMessage__c objSmsSchedule : lstSmsSchedulesToBeUpdated){
                    if(objSmsSchedule.CCPM_MessageStatus__c == CCPM_staticConstants.strMessageStatusQueued){
                        objSmsSchedule.CCPM_MessageStatus__c = CCPM_staticConstants.strMessageStatusRemoved;
                    }
                }
                //Update the sms message records
                try{
                    Update lstSmsSchedulesToBeUpdated;
                }
                catch(Exception e){
                    CCPM_LogMessageUtility.logMessage(e,'RemoveSmsScheduleBatchHandler','RemoveSmsScehdules','Exception thrown while updating list of sms message schedules',ccpm_staticConstants.boolSMSSent);
                }  
            }
            else{
                    CCPM_logMessageUtility.logMessage(CCPM_logMessageUtility.LOG_LogLevel.Debug, 'RemoveSmsScheduleBatchHandler','RemoveSmsScehdules', 'No Schedules To Remove' , ccpm_staticConstants.boolSMSSent);
            }
            //Update the status for custom object
            for(Integer i=0; i<lstSchedulesToBeRemoved.size();i++){
                if(lstSchedulesToBeRemoved[i].CCPM_Status__c == CCPM_staticConstants.StatusNew){
                    lstSchedulesToBeRemoved[i].CCPM_Status__c = CCPM_staticConstants.StatusCompleted;
                }
                else{
                    lstSchedulesToBeRemoved[i].CCPM_Status__c = CCPM_staticConstants.StatusRejected;
                }
            }
            try{
                Update lstSchedulesToBeRemoved;
            }
            catch(Exception e){
                CCPM_LogMessageUtility.logMessage(e,'RemoveSmsScheduleBatchHandler','RemoveSmsScehdules','Exception thrown while updating status for the list of records from the custom object',ccpm_staticConstants.boolSMSSent);
            }
        }
    }
    
    /**
*@author        Sriraman Sridharan (Deloitte)
*@description   This method removes the schedules
*@Params		List<CCPM_SMSSchedulesToBeRemoved__c>
*@return        Void(None)
*/ 
    
    Public static List<CCPM_SMSMessage__c> getSMSScheduleList(List<CCPM_SMSSchedulesToBeRemoved__c> lstSchedulesToBeRemoved){
        Set<String> setAccountuniqueId = new Set<String>();
        Set<String> setLeadId = new Set<String>();
        List<lead> lstLeadsForRemovingScedules = new List<lead>();
        List<CCPM_SMSMessage__c> lstSmsSchedulesToBeUpdated = new List<CCPM_SMSMessage__c>();
        //map<String,List<CCPM_SMSMessage__c>> mpAccAndSmsSchedules = new map<String,List<CCPM_SMSMessage__c>>();
        for(CCPM_SMSSchedulesToBeRemoved__c objSchedulesToRemove : lstSchedulesToBeRemoved){
            if(objSchedulesToRemove.CCPM_accountUniqueID__c != null){
                setAccountuniqueId.add(objSchedulesToRemove.CCPM_accountUniqueID__c);
            }
        }
        //system.debug('@@@setAccountuniqueId' + setAccountuniqueId);
        if(setAccountuniqueId.size()>0 && setAccountuniqueId!= null){
            try{
                lstLeadsForRemovingScedules = [Select id,Status,CCPM_mobileNumber__c,RecordTypeId,CCPM_accountUniqueID__c from lead where CCPM_accountUniqueID__c IN :setAccountuniqueId AND (Status =: CCPM_staticConstants.strLeadStatusNew OR Status =: CCPM_staticConstants.strLeadStatusEligible OR Status =: CCPM_staticConstants.strLeadStatusContacted)];
            	//system.debug('@@@lstLeadsForRemovingScedules' + lstLeadsForRemovingScedules);
                //CCPM_accountUniqueID__c IN :setAccountuniqueId AND 
            }        
            catch(Exception e)
            {
                //system.debug('@@@e'+ e);
                CCPM_LogMessageUtility.logMessage(e,'RemoveSmsScheduleBatchHandler','RemoveSmsScehdules','Exception thrown while querying for leads which belong to a set of accounts',ccpm_staticConstants.boolSMSSent);
            }
            if(lstLeadsForRemovingScedules!= null && lstLeadsForRemovingScedules.size()>0){
                for(lead objleadsForID : lstLeadsForRemovingScedules){
                    if(objleadsForID.id != null){
                        setLeadId.add(objleadsForID.id);
                    }
                }
                try{
                    if(setLeadId != null && !setLeadId.isEmpty()){
                        lstSmsSchedulesToBeUpdated = [Select Id,CCPM_toPhoneNumber__c,CCPM_ScheduleDateTime__c,CCPM_messageType__c,CCPM_MessageStatus__c from CCPM_SMSMessage__c where CCPM_leadRecord__c IN :setLeadId AND CCPM_MessageStatus__c =:CCPM_staticConstants.strMessageStatusQueued];
                        //system.debug('@@@lstSmsSchedulesToBeUpdated' + lstSmsSchedulesToBeUpdated);
                    }
                }        
                catch(Exception e)
                {
                    CCPM_LogMessageUtility.logMessage(e,'RemoveSmsScheduleBatchHandler','RemoveSmsScehdules','Exception thrown while querying for leads which belong to a set of accounts',ccpm_staticConstants.boolSMSSent);
                }   
            }  
        }
        return lstSmsSchedulesToBeUpdated;
    }
}