VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>CCPM Sales Rep,CCPM Retail Sales Rep,CCPM Retail Store Management,CCPM Retail District Management,CCPM Telesales Rep,CCPM Telesales Supervisor,CCPM Telesales Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Store Manager</fullName>
                </value>
                <value>
                    <fullName>Assistant Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSResponseReceivedDateTime__c</fullName>
        <description>Holds the date/time when SMS response was received</description>
        <label>SMS Response Received Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_leadOwner__c</fullName>
        <description>Formula to get full name of lead owner to display in list view. List view only shows owner alias or last name / first name but not the full name of the lead owner</description>
        <formula>TRIM(Owner:User.FirstName + &apos; &apos; + Owner:User.LastName)</formula>
        <label>Lead Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_leadSubStatus__c</fullName>
        <description>This field is used to store the Lead Sub Status</description>
        <inlineHelpText>Populated when the status is “Responded” or “Qualified”</inlineHelpText>
        <label>Lead Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>Action Required</fullName>
                </value>
                <value>
                    <fullName>In Discussion</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Needs Store Reassignment</fullName>
                </value>
                <value>
                    <fullName>Service Issue</fullName>
                </value>
                <value>
                    <fullName>Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart-Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart Opt Out</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_customHomePageController.cls
/**
*@name          CCPM_customHomePageController
*@author        Paras Shah (Deloitte)
*@date          03/30/2017
*@description   For Dispalying the "Qualified" Leads on the Home Page
*@testClass     CCPM_pullDetailsToDisplayOnChartControllerTest

Modification    Log:
------------------------------------------------------------------------------------
Developer                        Date                                Description
------------------------------------------------------------------------------------
Paras Shah(Deloitte)             03/30/2017                          Original Version
*/

public with Sharing class CCPM_customHomePageController {

        @AuraEnabled
        public static String  strProfileName{get;set;}
        @AuraEnabled
        public static String  strUserRoleName {get;set;}
        @AuraEnabled
        public static String  strUserStoreRoleName {get;set;}
        @AuraEnabled
        public static boolean boolStrProfileSystemAdministrator {get;set;}
        @AuraEnabled       
        public static boolean boolStrUserStoreRoleName {get;set;}
        @AuraEnabled
        public static boolean boolStrUserRoleName {get;set;}
        @AuraEnabled
        public static Id      idCurrentUser {get; set;}
    /**
    *@author        Paras Shah (Deloitte)
    *@description   This is a constructor method used to get the Role of the current user
    *@return        -
    */ 
    public CCPM_customHomePageController()  {
       
       
        Id idProfileOfCurrentUser        = UserInfo.getProfileId();
        List<Profile> lstProfileName     = [Select Name from Profile where Id = :idProfileOfCurrentUser limit 1];     
        
        if(lstProfileName.size() > 0) {
            strProfileName               = lstProfileName[0].Name;
            boolStrProfileSystemAdministrator = strProfileName.contains('System Administrator');
        }
        
        // Get User Role Name based on User Information
        idCurrentUser                 = UserInfo.getUserId();
        List<User> lstUserRoleName       = [Select UserRole.Name from User where Id = :idCurrentUser limit 1];   
        
        if (lstUserRoleName.size() > 0) {
            strUserRoleName              = lstUserRoleName[0].UserRole.Name;
            if (strUserRoleName != null) {
                boolStrUserRoleName      = strUserRoleName.contains('Manager');
            }
        }
        
        // Get User Store Role Name based on Store Employee record information
        List<CCPM_storeEmployee__c> lstUserStoreRoleName   = [Select CCPM_role__c from CCPM_storeEmployee__c where CCPM_employee__c = :idCurrentUser];
        if(lstUserStoreRoleName.size() > 0) {
            strUserStoreRoleName                               = lstUserStoreRoleName[0].CCPM_role__c;
            if (strUserStoreRoleName != null) {
                boolStrUserStoreRoleName                       = strUserStoreRoleName.contains('Manager');
            }
        }
        
    }    
    /**
    *@author        Paras Shah (Deloitte)
    *@description   This method is used to get the list of Qualified leads to display on the homepage
    *@return        List of leads
    */ 
    @AuraEnabled
    public static List<Lead> getLeadsThatResponded()  {
        
         transient List<Lead> lstLeadsThatResponded = new List<Lead>();
        
        //Check if the user is a System Administrator
        //If the user is a system administrator then show all the leads that responsded
        //Otherwise only display the leads that is owned by the logged in user
        
        if (strProfileName == CCPM_staticConstants.strSystemAdministrator) {
            
            // Query to pull the Qualified Leads that recently responded
            lstLeadsThatResponded = [SELECT id,Name, createdDate,CCPM_leadOwner__c,CCPM_SMSResponseReceivedDateTime__c,
                                    (SELECT Description,createdDate
                                       FROM Tasks 
                                      WHERE CCPM_communicationDirection__c = :CCPM_staticConstants.strTaskCommunicationDirection 
                                   ORDER BY createdDate DESC LIMIT 1)  
                                       FROM Lead    
                                      WHERE Status                         = :CCPM_staticConstants.strLeadStatusResponded 
                                        AND CCPM_leadSubStatus__c          = :CCPM_staticConstants.strLeadSubStatusActionRequired
                                   ORDER BY CCPM_SMSResponseReceivedDateTime__c        DESC LIMIT 900];
        } else {
            
            // Query to pull the Qualified Leads that recently responded
            lstLeadsThatResponded = [SELECT id,Name, createdDate,CCPM_leadOwner__c,CCPM_SMSResponseReceivedDateTime__c,
                                    (SELECT Description,createdDate
                                       FROM Tasks 
                                      WHERE CCPM_communicationDirection__c = :CCPM_staticConstants.strTaskCommunicationDirection 
                                   ORDER BY createdDate DESC LIMIT 1)
                                       FROM Lead
                                      WHERE Status                         = :CCPM_staticConstants.strLeadStatusResponded 
                                        AND CCPM_leadSubStatus__c          = :CCPM_staticConstants.strLeadSubStatusActionRequired
                                   ORDER BY CCPM_SMSResponseReceivedDateTime__c        DESC LIMIT 900];
        }
        
        return lstLeadsThatResponded;
    }
}