VZDEV/src/objects/CCPM_OrganizationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CCPM_DisableTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization Setting</label>
</CustomObject>

VZDEV/src/objects/CCPM_segmentation__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field will capture which Territories’ Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Segmentations</relationshipLabel>
        <relationshipName>CCPM_segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_districts1__c</fullName>
        <inlineHelpText>This field will capture which District’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Districts 1</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK01</fullName>
                </value>
                <value>
                    <fullName>CAR01-Coastal Carolinas</fullName>
                </value>
                <value>
                    <fullName>CAR02-Eastern NC</fullName>
                </value>
                <value>
                    <fullName>CAR03-NC Triad</fullName>
                </value>
                <value>
                    <fullName>CAR04-SC Central</fullName>
                </value>
                <value>
                    <fullName>CAR05-SCSE Coast</fullName>
                </value>
                <value>
                    <fullName>CAR06-Triangle North</fullName>
                </value>
                <value>
                    <fullName>CAR07-Triangle South</fullName>
                </value>
                <value>
                    <fullName>CC01</fullName>
                </value>
                <value>
                    <fullName>CC02</fullName>
                </value>
                <value>
                    <fullName>CC03</fullName>
                </value>
                <value>
                    <fullName>CC04</fullName>
                </value>
                <value>
                    <fullName>CC05</fullName>
                </value>
                <value>
                    <fullName>CC06</fullName>
                </value>
                <value>
                    <fullName>CP01</fullName>
                </value>
                <value>
                    <fullName>CP02</fullName>
                </value>
                <value>
                    <fullName>CP03</fullName>
                </value>
                <value>
                    <fullName>CP04</fullName>
                </value>
                <value>
                    <fullName>CP05</fullName>
                </value>
                <value>
                    <fullName>CP06</fullName>
                </value>
                <value>
                    <fullName>CP07</fullName>
                </value>
                <value>
                    <fullName>DS01-Las Vegas West</fullName>
                </value>
                <value>
                    <fullName>DS02-Phoenix North</fullName>
                </value>
                <value>
                    <fullName>DS03-Phoenix West</fullName>
                </value>
                <value>
                    <fullName>DS04-Scottsdale</fullName>
                </value>
                <value>
                    <fullName>DS05-Phoenix East</fullName>
                </value>
                <value>
                    <fullName>DS06-Phoenix South</fullName>
                </value>
                <value>
                    <fullName>DS07-Tucson West</fullName>
                </value>
                <value>
                    <fullName>DS08-Tucson East</fullName>
                </value>
                <value>
                    <fullName>DS09-Albuquerque</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_districts2__c</fullName>
        <inlineHelpText>This field will capture which District’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Districts 2</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GLW04-Far West Chicago</fullName>
                </value>
                <value>
                    <fullName>GLW05-South Chicago-NW IN</fullName>
                </value>
                <value>
                    <fullName>GLW06-Peoria-Davenport</fullName>
                </value>
                <value>
                    <fullName>GLW07-SW Chicago</fullName>
                </value>
                <value>
                    <fullName>GLW08-W MI-Grand Rapids</fullName>
                </value>
                <value>
                    <fullName>GLW09-NE Indiana</fullName>
                </value>
                <value>
                    <fullName>HI01</fullName>
                </value>
                <value>
                    <fullName>HI02</fullName>
                </value>
                <value>
                    <fullName>HQ-Telesales</fullName>
                </value>
                <value>
                    <fullName>KM01-Southern IL</fullName>
                </value>
                <value>
                    <fullName>KM02-St Louis</fullName>
                </value>
                <value>
                    <fullName>KM03-Southern MO</fullName>
                </value>
                <value>
                    <fullName>KM04-KC East</fullName>
                </value>
                <value>
                    <fullName>KM05-KC West</fullName>
                </value>
                <value>
                    <fullName>KM06-Central KS</fullName>
                </value>
                <value>
                    <fullName>LA01</fullName>
                </value>
                <value>
                    <fullName>LA02</fullName>
                </value>
                <value>
                    <fullName>LA03</fullName>
                </value>
                <value>
                    <fullName>LA04</fullName>
                </value>
                <value>
                    <fullName>LA05</fullName>
                </value>
                <value>
                    <fullName>LA06</fullName>
                </value>
                <value>
                    <fullName>LA07</fullName>
                </value>
                <value>
                    <fullName>LA08</fullName>
                </value>
                <value>
                    <fullName>MS01</fullName>
                </value>
                <value>
                    <fullName>MS02</fullName>
                </value>
                <value>
                    <fullName>MS03</fullName>
                </value>
                <value>
                    <fullName>MS04</fullName>
                </value>
                <value>
                    <fullName>MS05</fullName>
                </value>
                <value>
                    <fullName>MS06</fullName>
                </value>
                <value>
                    <fullName>MT01-Northern CO-WY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_districts3__c</fullName>
        <inlineHelpText>This field will capture which District’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Districts 3</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SN02</fullName>
                </value>
                <value>
                    <fullName>SN03</fullName>
                </value>
                <value>
                    <fullName>SN04</fullName>
                </value>
                <value>
                    <fullName>SN05</fullName>
                </value>
                <value>
                    <fullName>SN06</fullName>
                </value>
                <value>
                    <fullName>ST01-San Antonio</fullName>
                </value>
                <value>
                    <fullName>ST02-RGV</fullName>
                </value>
                <value>
                    <fullName>ST03-Houston Southwest</fullName>
                </value>
                <value>
                    <fullName>ST04-Houston West</fullName>
                </value>
                <value>
                    <fullName>ST05-Houston North</fullName>
                </value>
                <value>
                    <fullName>ST06-Houston East</fullName>
                </value>
                <value>
                    <fullName>ST07-Houston Southeast</fullName>
                </value>
                <value>
                    <fullName>ST08-Houston Central</fullName>
                </value>
                <value>
                    <fullName>TA01-East Texas</fullName>
                </value>
                <value>
                    <fullName>TA02-South Oklahoma</fullName>
                </value>
                <value>
                    <fullName>TA03-North Oklahoma</fullName>
                </value>
                <value>
                    <fullName>TA04-West Arkansas</fullName>
                </value>
                <value>
                    <fullName>TA05-East Arkansas</fullName>
                </value>
                <value>
                    <fullName>TA06-South Arkansas</fullName>
                </value>
                <value>
                    <fullName>TCW01-Charlotte North</fullName>
                </value>
                <value>
                    <fullName>TCW02-Charlotte South</fullName>
                </value>
                <value>
                    <fullName>TCW03-Nashville</fullName>
                </value>
                <value>
                    <fullName>TCW04-Chattanooga</fullName>
                </value>
                <value>
                    <fullName>TCW05-Knoxville</fullName>
                </value>
                <value>
                    <fullName>TCW06-Tri-Cities</fullName>
                </value>
                <value>
                    <fullName>TCW07-Upstate SC</fullName>
                </value>
                <value>
                    <fullName>TCW08-Western NC</fullName>
                </value>
                <value>
                    <fullName>UP01</fullName>
                </value>
                <value>
                    <fullName>UP02</fullName>
                </value>
                <value>
                    <fullName>UP03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_markets__c</fullName>
        <inlineHelpText>This field will capture which Market’s Sales Rep will have this Event type available to them</inlineHelpText>
        <label>Markets</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>HQ-Telesales</fullName>
                </value>
                <value>
                    <fullName>North Central</fullName>
                </value>
                <value>
                    <fullName>North East</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>South East</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Segmentation</label>
    <nameField>
        <displayFormat>SEG-{000000}</displayFormat>
        <label>Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_segmentationTriggerHandler.cls
/**
*@name          CCPM_segmentationTriggerHandler 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          04/14/2018
*@description   This is a handler for CCPM_segmentation trigger. 
*@Class         CCPM_segmentationTriggerHandler
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    04/14/2018   Initial Implementation.
*/
public with sharing class CCPM_segmentationTriggerHandler implements CCPM_ITriggerHandler{
    
    // Allows unit tests (or other code) to disable this trigger for the transaction
    public static Boolean boolTriggerDisabled = false;
    
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  Checks to see if the trigger has been disabled either by custom setting or by running code
	@param        N/A
	@return       Boolean
	*/ 
    public Boolean IsDisabled()
    {
        CCPM_OrganizationSetting__c settings = CCPM_OrganizationSetting__c.getInstance(UserInfo.getUserId());
	    if(settings != null && settings.CCPM_DisableTrigger__c == true){
	        return true;
	    }
        else
            return boolTriggerDisabled;
    }
    
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the before insert trigger context
	@param        List<SObject>
	@return       void
	*/     
    public void BeforeInsert(List<SObject> lstNewItems) {
    	/**************Method Declarations Start*/
    	List<CCPM_segmentation__c> lstNew = (List<CCPM_segmentation__c>) lstNewItems;
    	Map<String, Campaign> mapCampaign = new Map<String, Campaign>();
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	for(CCPM_segmentation__c objSeg : lstNew){
    		if(objSeg.CCPM_campaign__c !=  null && objSeg.CCPM_isActive__c){
    			mapCampaign.put(objSeg.CCPM_campaign__c, new Campaign());
    		}
    	}
    	/**************First loop End*/
    	
    	mapCampaign = new Map<String, Campaign>([Select id, Name, (Select Id, CCPM_districts1__c, CCPM_districts2__c, CCPM_districts3__c, CCPM_markets__c, CCPM_territories__c From CCPM_segmentations__r Where CCPM_isActive__c = true) From Campaign Where Id IN: mapCampaign.keyset()]);
    	
    	/**************Second Loop Start*/
    	for(CCPM_segmentation__c objSeg : lstNew){
    		
    		Set<String> setDistricts = new Set<String>();
			if(String.isNotBlank(objSeg.CCPM_districts1__c)){
				setDistricts.addAll(CCPM_utility.getSetFromString(objSeg.CCPM_districts1__c , ';'));
			}
			if(String.isNotBlank(objSeg.CCPM_districts2__c)){
				setDistricts.addAll(CCPM_utility.getSetFromString(objSeg.CCPM_districts2__c , ';'));
			}
			if(String.isNotBlank(objSeg.CCPM_districts3__c)){
				setDistricts.addAll(CCPM_utility.getSetFromString(objSeg.CCPM_districts3__c , ';'));
			}
    		
    		if(objSeg.CCPM_campaign__c !=  null && objSeg.CCPM_isActive__c){
    			Campaign objCampaign = mapCampaign.get(objSeg.CCPM_campaign__c);
    			if(CCPM_Collection.isNotNullEmpty(objCampaign.CCPM_segmentations__r)){
    				for(CCPM_segmentation__c objSegCampaign : objCampaign.CCPM_segmentations__r){
	    				Set<String> setSegCampaignDistricts = new Set<String>();
	    				if(String.isNotBlank(objSegCampaign.CCPM_districts1__c)){
	    					setSegCampaignDistricts.addAll(CCPM_utility.getSetFromString(objSegCampaign.CCPM_districts1__c , ';'));
	    				}
	    				if(String.isNotBlank(objSegCampaign.CCPM_districts2__c)){
	    					setSegCampaignDistricts.addAll(CCPM_utility.getSetFromString(objSegCampaign.CCPM_districts2__c , ';'));
	    				}
	    				if(String.isNotBlank(objSegCampaign.CCPM_districts3__c)){
	    					setSegCampaignDistricts.addAll(CCPM_utility.getSetFromString(objSegCampaign.CCPM_districts3__c , ';'));
	    				}
	    				List<String> lstOverlappingDisct = new List<String>();
	    				for(String strDisct : setDistricts){
	    					if(setSegCampaignDistricts.contains(strDisct)){
	    						lstOverlappingDisct.add(strDisct);
	    					}
	    				}
	    				if(CCPM_Collection.isNotNullEmpty(lstOverlappingDisct)){
	    					objSeg.addError('Overlapping Disctricts found for <u><i>'+ objCampaign.Name +'</i></u> : '+String.join(lstOverlappingDisct, ','), false);
	    				}
    				}
    			}
    		}
    	}
    	/**************Second loop End*/
    }
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the before update trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void BeforeUpdate(Map<Id, SObject> mapNewItems, Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_segmentation__c> mapNew = (Map<id, CCPM_segmentation__c>)mapNewItems;
    	Map<id, CCPM_segmentation__c> mapOld = (Map<id, CCPM_segmentation__c>)mapOldItems;
    	Map<String, Campaign> mapCampaign = new Map<String, Campaign>();
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	for(CCPM_segmentation__c objSeg : mapNew.values()){
    		if(objSeg.CCPM_campaign__c !=  null && objSeg.CCPM_isActive__c){
    			mapCampaign.put(objSeg.CCPM_campaign__c, new Campaign());
    		}
    	}
    	/**************First loop End*/
    	
    	mapCampaign = new Map<String, Campaign>([Select id, Name, (Select Id, CCPM_districts1__c, CCPM_districts2__c, CCPM_districts3__c, CCPM_markets__c, CCPM_territories__c From CCPM_segmentations__r Where CCPM_isActive__c = true) From Campaign Where Id IN: mapCampaign.keyset()]);
    	
    	/**************Second Loop Start*/
    	for(CCPM_segmentation__c objSeg : mapNew.values()){
    		
    		Set<String> setDistricts = new Set<String>();
			if(String.isNotBlank(objSeg.CCPM_districts1__c)){
				setDistricts.addAll(CCPM_utility.getSetFromString(objSeg.CCPM_districts1__c , ';'));
			}
			if(String.isNotBlank(objSeg.CCPM_districts2__c)){
				setDistricts.addAll(CCPM_utility.getSetFromString(objSeg.CCPM_districts2__c , ';'));
			}
			if(String.isNotBlank(objSeg.CCPM_districts3__c)){
				setDistricts.addAll(CCPM_utility.getSetFromString(objSeg.CCPM_districts3__c , ';'));
			}
    		
    		if(objSeg.CCPM_campaign__c !=  null && objSeg.CCPM_isActive__c){
    			Campaign objCampaign = mapCampaign.get(objSeg.CCPM_campaign__c);
    			if(CCPM_Collection.isNotNullEmpty(objCampaign.CCPM_segmentations__r)){
    				for(CCPM_segmentation__c objSegCampaign : objCampaign.CCPM_segmentations__r){
	    				Set<String> setSegCampaignDistricts = new Set<String>();
	    				if(String.isNotBlank(objSegCampaign.CCPM_districts1__c)){
	    					setSegCampaignDistricts.addAll(CCPM_utility.getSetFromString(objSegCampaign.CCPM_districts1__c , ';'));
	    				}
	    				if(String.isNotBlank(objSegCampaign.CCPM_districts2__c)){
	    					setSegCampaignDistricts.addAll(CCPM_utility.getSetFromString(objSegCampaign.CCPM_districts2__c , ';'));
	    				}
	    				if(String.isNotBlank(objSegCampaign.CCPM_districts3__c)){
	    					setSegCampaignDistricts.addAll(CCPM_utility.getSetFromString(objSegCampaign.CCPM_districts3__c , ';'));
	    				}
	    				List<String> lstOverlappingDisct = new List<String>();
	    				for(String strDisct : setDistricts){
	    					if(setSegCampaignDistricts.contains(strDisct)){
	    						lstOverlappingDisct.add(strDisct);
	    					}
	    				}
	    				if(CCPM_Collection.isNotNullEmpty(lstOverlappingDisct)){
	    					objSeg.addError('Overlapping Disctricts found for <u><i>'+ objCampaign.Name +'</i></u> : '+String.join(lstOverlappingDisct, ','), false);
	    				}
    				}
    			}
    		}
    	}
    	/**************Second loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the before delete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void BeforeDelete(Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_segmentation__c> mapOld = (Map<id, CCPM_segmentation__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after insert trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterInsert(Map<Id, SObject> mapNewItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_segmentation__c> mapNew = (Map<id, CCPM_segmentation__c>)mapNewItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after update trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterUpdate(Map<Id, SObject> mapNewItems, Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_segmentation__c> mapNew = (Map<id, CCPM_segmentation__c>)mapNewItems;
    	Map<id, CCPM_segmentation__c> mapOld = (Map<id, CCPM_segmentation__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the after delete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterDelete(Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	
    	Map<id, CCPM_segmentation__c> mapOld = (Map<id, CCPM_segmentation__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
 	/**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  is called in the After undelete trigger context
	@param        List<SObject>
	@return       void
	*/ 
    public void AfterUndelete(Map<Id, SObject> mapOldItems){
    	/**************Method Declarations Start*/
    	Map<id, CCPM_segmentation__c> mapOld = (Map<id, CCPM_segmentation__c>)mapOldItems;
    	/**************Method Declarations end*/
    	
    	/**************Methods calling functionalities in other classes start. */
    	
    	/**************Methods calling functionalities in other classes end.*/
    	
    	/**************First Loop Start*/
    	
    	/**************First loop End*/
    }
    
}