VZDEV/src/objects/CCPM_Store__c.object
<CustomObject>
    <description>Object to hold details of store (Store ID, Phone, Long Code, Address)</description>
    <fields>
        <fullName>CCPM_source__c</fullName>
        <description>This field contains source of store which markets store belongs  i.e Retail or Telesales</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_Store__c</fullName>
        <label>Store</label>
        <referenceTo>CCPM_Store__c</referenceTo>
        <relationshipLabel>Store Employees</relationshipLabel>
        <relationshipName>Store_Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCPM_employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>CCPM Sales Rep,CCPM Retail Sales Rep,CCPM Retail Store Management,CCPM Retail District Management,CCPM Telesales Rep,CCPM Telesales Supervisor,CCPM Telesales Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Store_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_storeSource__c</fullName>
        <formula>CCPM_Store__r.CCPM_source__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_uniqueStoreEmployeeID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Unique Store Employee ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSFollowUpDate__c</fullName>
        <inlineHelpText>The date &amp; time for the SMS to be scheduled to be sent</inlineHelpText>
        <label>SMS Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_confirmEmail__c</fullName>
        <description>Confirm Email address specified by the customer when creating the cart</description>
        <label>Confirm Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_confirmMTN__c</fullName>
        <description>Confirm Mobile number which has been used to create the cart</description>
        <label>Confirm MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_createdChannel__c</fullName>
        <description>The field shows the created channel on the prospect</description>
        <inlineHelpText>This represents the initial channel of the lead or prospect upon creation</inlineHelpText>
        <label>Created Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_createdDate__c</fullName>
        <label>Cart Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <description>Email address specified by the customer when creating the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Email of the lead / prospect. Required to save a Prospect if the MTN is unavailable.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_eventType__c</fullName>
        <inlineHelpText>The Conversation Topic that requires an SMS follow up to be sent.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samsung GS9 BOGO</fullName>
                </value>
                <value>
                    <fullName>TMP OE - Q2 2018</fullName>
                </value>
                <value>
                    <fullName>Add a Line</fullName>
                </value>
                <value>
                    <fullName>Confirming with Family First</fullName>
                </value>
                <value>
                    <fullName>Connected Device</fullName>
                </value>
                <value>
                    <fullName>Contract Terminating Soon</fullName>
                </value>
                <value>
                    <fullName>Feature Add</fullName>
                </value>
                <value>
                    <fullName>Gift for Upcoming Occasion</fullName>
                </value>
                <value>
                    <fullName>iPhone X</fullName>
                </value>
                <value>
                    <fullName>iPhone X send message</fullName>
                </value>
                <value>
                    <fullName>New Service</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>Special Event</fullName>
                </value>
                <value>
                    <fullName>Tablets</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_taskTriggerHandlerHelperTest.cls
/**
*@name          CCPM_taskTriggerHandlerHelperTest 
*@author        Aneesha Ragireddy(Deloitte)
*@date          11/21/2017
@description    Test class for 
@testClass      CCPM_taskTriggerHandlerHelper 
Modification    Log:
------------------------------------------------------------------------------------
Developer                               Date                        Description
------------------------------------------------------------------------------------
Aneesha Ragireddy(Deloitte)             11/21/2017                 Original Version
*/
@isTest
public class CCPM_taskTriggerHandlerHelperTest {
    @isTest
    Public static void updateLeadReminderTest(){
      
        
         test.startTest();
          //Group objTeleSales= [Select id from Group where DeveloperName =: Label.CCPM_telesalesUsersGroupName];
          //List<CCPM_storeEmployee__c> lststrEmp = [Select id from CCPM_storeEmployee__c Where CCPM_storeSource__c =: Label.CCPM_telesalesChannelName];
      Profile p = [SELECT Id,Name FROM Profile WHERE Name='CCPM Sales Rep' Limit 1]; 
      User u = new User(Alias = 'tstusr1', Email='standardtestuser1412@testorgUAT.com',
                   EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',firstname='a', 
                   LocaleSidKey='en_US', ProfileId = p.Id, IsActive = True,
                   TimeZoneSidKey='America/Los_Angeles', UserName= 'makeUnique'+'stest@testorg.com',mobilephone='3214249106');             
      insert u;
        system.debug('User ID is*****'+u.id);
        List<CCPM_store__c> lstStore = CCPM_testDataFactory.createStore(1);
        CCPM_store__c objStore = lstStore[0];
        // test.stopTest();
        //test.startTest();
        objStore.CCPM_source__c = 'Telesales';
        update objStore;
        objStore = [Select id, CCPM_source__c From CCPM_store__c Where id = :objStore.id];
        System.debug('******objStore**********'+objStore);
        CCPM_storeEmployee__c objStoreEmp = new CCPM_storeEmployee__c();
        //gm.GroupId = objTeleSales.id;
         system.debug('*******u.id*********'+u.id);
        objStoreEmp.CCPM_employee__c = u.id;
        
        objStoreEmp.CCPM_uniqueStoreEmployeeID__c = '1234';
        objStoreEmp.CCPM_Store__c = objStore.id;
        insert objStoreEmp;
        system.debug('*******objStoreEmp.CCPM_employee__c*********'+objStoreEmp.CCPM_employee__c);
        system.debug('*****Store Source of employee*****'+objStoreEmp.CCPM_storeSource__c);
        system.debug('*****objStoreEmp******'+objStoreEmp);
        //lststrEmp.add(sm);
        //List<GroupMember> AllMembers = [select id, GroupId, UserOrGroupId from GroupMember where UserOrGroupId=:userID];
        //system.debug('*****AllMembers******'+AllMembers);
        //test.stopTest();
        //system.debug('******objTeleSales********'+objTeleSales);
           Lead objCart=new Lead();
            CCPM_testDataFactory.createCustomSetting();
        
        objCart.LastName='testsample';
        objCart.FirstName='Inactive test';
        objCart.Status='New';
        objCart.Company = '1'; 
        objCart.CCPM_eventType__c = 'Reminder';
        objcart.CCPM_SMSFollowUpDate__c = system.now().addHours(5);
        objCart.CCPM_mobileNumber__c = '3213187287';
        objCart.CCPM_email__c ='test@gmail.com';
        objCart.CCPM_confirmEmail__c='test@gmail.com';
        datetime date1=Datetime.now();
        objCart.CCPM_createdDate__c=date1.addHours(-5);
        objCart.CCPM_SMSLegalOptIn__c =true;
        objCart.CCPM_confirmMTN__c= '3213187287';
        objCart.CCPM_LeadType__c = 'Prospect SFDC Manual';
        insert objCart;
        
        ccpm_utility.isCurrentUserTelesalesUser();
        /*objCart = [Select id, CCPM_createdChannel__c FROM Lead where id =: objCart.id];
            System.debug('******objCart******'+objCart);
        Task objTask = [select id,WhoId,Status from task where WhoId=:objCart.id];
        objTask.Status = 'Completed';
        update objTask;
        delete objTask;
        undelete objTask;
       objTask.Status = 'Cancelled';
         update objTask;*/
        Task objTask =new task();
        objTask.WhoId=objCart.id;
        objTask.Status='Completed';
        insert objTask;
        delete objTask;
        undelete objTask;
       objTask.Status = 'Cancelled';
         update objTask;
   
    }

}