VZDEV/src/objects/CCPM_globalSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Settings for verizon lead &amp; prospect management</description>
    <fields>
        <fullName>CCPM_daysOfLeadExpiry__c</fullName>
        <description>Number of days after which Leads need to be expired</description>
        <label>Days of Lead Expiry</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_followUpSMSInterval__c</fullName>
        <inlineHelpText>Interval in minutes from date/time lead is created to send the follow-up SMS</inlineHelpText>
        <label>Follow Up SMS Interval (In Min)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_initialSMSInterval__c</fullName>
        <inlineHelpText>Interval in minutes to send the initial sms from date/time lead (cart) was created in salesforce</inlineHelpText>
        <label>Initial SMS Interval (In Min)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

VZDEV/src/classes/CCPM_expireInActiveLeadsJobTest.cls
/**
*@name          CCPM_expireInActiveLeadsJobTest
*@author        Paras Shah (Deloitte)
*@date          05/25/2017
@description    This is a test class for CCPM_expireInActiveLeadsJob


@testClass:     CCPM_expireInActiveLeadsJobTest
Modification    Log:
------------------------------------------------------------------------------------
Developer               Date                                Description
------------------------------------------------------------------------------------
Paras Shah(Deloitte)    05/25/2017                          Original Version
*/

@istest(SeeAllData=False)
public class CCPM_expireInActiveLeadsJobTest {    
    
    public static list<string> lstAccountUniqueID=new list<string>();
    
    /**
*@author        Paras Shah (Deloitte)
*@description   This method is targeted to test the CCPM_SMSInteractionHistoryController class
*@param :       None
*/
    @istest(SeeAllData=False) public static void testLeadCreation()
    {   
        test.startTest();
        
        insert new CCPM_globalSetting__c(CCPM_daysOfLeadExpiry__c = -2,CCPM_initialSMSInterval__c ='10', CCPM_followUpSMSInterval__c='10'); 
        
        CCPM_expireInActiveLeadsJob expireLeads = new CCPM_expireInActiveLeadsJob();
        String schedule = '0 0 * * * ?';
        system.schedule('Lead Expiration', schedule, expireLeads);

        test.stopTest();
    }        
  }