VZDEV/src/objects/CCPM_SMSMessage__c.object
<CustomObject>
    <description>An custom SMS message to store the details of sms messages sent</description>
    <fields>
        <fullName>CCPM_LiveTextNumber__c</fullName>
        <description>Stores the Live Text Number Used.</description>
        <inlineHelpText>Stores the Live Text Number Used.</inlineHelpText>
        <label>Live Text Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_MessageStatus__c</fullName>
        <description>Refers to the status of the Message sent based on response code.</description>
        <inlineHelpText>Refers to the status of the Message sent based on response code.</inlineHelpText>
        <label>Message Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Resend Failed</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_SMSFailCounter__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <description>Counter that holds the number of times the SMS failed to be sent.</description>
        <label>SMS Fail Counter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_ScheduleDateTime__c</fullName>
        <description>Refers to the Date/Time the SMS is to be sent.</description>
        <inlineHelpText>Refers to the Date/Time the SMS is to be sent.</inlineHelpText>
        <label>Schedule Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_formattedtoPhone__c</fullName>
        <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( CCPM_toPhoneNumber__c, &quot;(&quot;, &quot;&quot;), &quot;)&quot;, &quot;&quot;), &quot; &quot;, &quot;&quot;), &quot;-&quot;, &quot;&quot;)</formula>
        <label>Formatted To Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_leadRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the associated lead.</description>
        <inlineHelpText>Refers to the associated lead.</inlineHelpText>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>SMS Messages</relationshipLabel>
        <relationshipName>SMS_Message_Sent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_messageType__c</fullName>
        <description>Indicates the type of SMS being sent.</description>
        <inlineHelpText>Indicates the type of SMS being sent.</inlineHelpText>
        <label>Message Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_message__c</fullName>
        <description>Message body to be sent.</description>
        <inlineHelpText>Message body to be sent.</inlineHelpText>
        <label>Message</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_responseCode__c</fullName>
        <description>Response codes recorded for each API call made</description>
        <label>Response Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_responseMessage__c</fullName>
        <description>Captures the Response Message for the Heywire API callout made.</description>
        <inlineHelpText>Captures the Response Message for the Heywire API callout made.</inlineHelpText>
        <label>Response Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_toPhoneNumber__c</fullName>
        <description>Refers to the number the SMS should be sent.</description>
        <inlineHelpText>Refers to the number the SMS should be sent.</inlineHelpText>
        <label>To Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>SMS Message</label>
    <nameField>
        <displayFormat>SMS-{000000000}</displayFormat>
        <label>SMS Message #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_isFollowUpSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if follow up SMS was sent</description>
        <inlineHelpText>Has a follow up SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Follow-Up SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isInitialSMSSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</description>
        <inlineHelpText>Has an initial SMS been sent to encourage the individual to visit a Verizon store?</inlineHelpText>
        <label>Initial SMS Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_isProspectSMSsent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate whethet Prospect 1st SMS was sent.</description>
        <inlineHelpText>Has an Event SMS been sent based off the Event based SMS and event date selected?</inlineHelpText>
        <label>Event SMS sent?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_sendSMSBatch.cls
/**
*@name          CCPM_sendSMSBatch
*@author        Brigadesh Chandrasekar (Deloitte)
*@date          05/07/2017
@description    Batch class to send SMS messages to customers & prospects by reading messages from “CCPM_SMSMessage"
@testClass      
Modification    Log:
------------------------------------------------------------------------------------
Developer             				  Date                                Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)      05/07/2017                          Original Version
Sudhakara Reddy Nallamilli(Deloitte)  09/26/2017                      DISTSCE-1589- Added SMS MessageTypes for SMS Batch Jobs
*/

global class CCPM_sendSMSBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable{
   
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   This Constructor builds up the query for SMS Messages Information based on conditions specified.
*@return        Void(None)
*/ 
    global Database.QueryLocator start(Database.BatchableContext BC){
    	string strQuery;
        string Queued = CCPM_staticConstants.strMessageStatusQueued;
        string Error = CCPM_staticConstants.strMessageStatusError;
        // Capturing the SMS Message Types from the custom settings specific to this batch job
        set<string> setSMSMessageTypes = new set<string>();
    	string strInitialSMSTypes = Label.CCPM_initialMessageTypes;
        if(strInitialSMSTypes != null && !string.isBlank(strInitialSMSTypes))
        {
          setSMSMessageTypes = new set<String>(strInitialSMSTypes.Split(CCPM_staticConstants.strColon));
        } 
        //Capturing the current System Time
        datetime datTCurrentTime     = Datetime.now();
        SYSTem.debug('Datetime Now-> '+Datetime.now());
        System.debug('System Now-> ' + System.now());
        system.debug('setSMSMessageTypes: '+ setSMSMessageTypes);
        //Getting the Date/Time formatted.
        String strCurrentTime        = datTCurrentTime.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        System.debug('# Current time of the system recorded -> '+strCurrentTime);
        // Building up the Query string for Execute method
        strQuery='select id,name,CCPM_LiveTextNumber__c,CCPM_formattedtoPhone__c,CCPM_messageType__c,CCPM_leadRecord__c,CCPM_leadRecord__r.CCPM_isInitialSMSSent__c,CCPM_leadRecord__r.CCPM_isFollowUpSMSSent__c,CCPM_leadRecord__r.CCPM_isProspectSMSsent__c,CCPM_message__c,CCPM_MessageStatus__c,CCPM_responseCode__c,CCPM_responseMessage__c,CCPM_ScheduleDateTime__c,CCPM_SMSFailCounter__c,CCPM_toPhoneNumber__c from CCPM_SMSMessage__c where (CCPM_MessageStatus__c=:'+CCPM_staticConstants.strMessageStatusQueued+' or CCPM_MessageStatus__c=:'+CCPM_staticConstants.strMessageStatusError+') and CCPM_ScheduleDateTime__c<'+strCurrentTime+' and CCPM_leadRecord__c != '+'null '+ ' and CCPM_messageType__c in :setSMSMessageTypes  order by CCPM_ScheduleDateTime__c limit '+CCPM_staticConstants.strBatchLimit;			
        system.debug('Query->'+strQuery);
        //Returning the records obtained by querying
        return Database.getQueryLocator(strQuery);
        
    }
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   Execute method in batchable context to make a callout to the handler
*@return        Void(None)
*/    
    global void execute(Database.BatchableContext BC, List<CCPM_SMSMessage__c> scope) {
        system.debug('# List of SMS Message Sent Records obtained from query in batchable context -> '+scope);
        CCPM_SMSMessageBatchHandler.sendSMSViaHeyWire(Scope);
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
    /**
*@author        Brigadesh Chandrasekar (Deloitte)
*@description   This method schedules the Batch class for every 5 min(Need to confirm)
*@return        Void(None)
*/     
    global void execute(SchedulableContext sc)
    {
        CCPM_sendSMSBatch CCPM_sendSMSBatch =new CCPM_sendSMSBatch();
        database.executebatch(CCPM_sendSMSBatch,integer.valueof(CCPM_staticConstants.strBatchChunk));
        //Scheduling the batch class
        
    }
    
}