VZDEV/src/objects/CCPM_storeEmployee__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if employee is active for that store</description>
        <label>Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_IsUpdateFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsUpdateFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_PreviousRole__c</fullName>
        <label>PreviousRole</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Store Manager</fullName>
                </value>
                <value>
                    <fullName>Assistant Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_previousactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Containing active flags for previous isactive value of store employee</description>
        <label>PreviousIsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Store Manager</fullName>
                </value>
                <value>
                    <fullName>Assistant Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_storeSource__c</fullName>
        <formula>CCPM_Store__r.CCPM_source__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Source</label>
        <type>Text</type>
    </fields>
    <label>Store Employee</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Store employee #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_strEmpTriggerHandlerHelper.cls
/**
*@name          CCPM_strEmpTriggerHandlerHelper 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          11/08/2017
*@description   This is a helper for CCPM_storeEmployeeTriggerHandler
*@Class         CCPM_strEmpTriggerHandlerHelper
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    11/08/2017   Initial Implementation.
*/
public with sharing class CCPM_strEmpTriggerHandlerHelper 
{
    
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  flags the record if the Rep Role is changed
	@param        CCPM_storeEmployee__c, CCPM_storeEmployee__c
	@return       void
	*/
    public static void flagRecForBatchProcess(CCPM_storeEmployee__c objNew, CCPM_storeEmployee__c ObjOld){
        system.debug('the new role is'+Objnew.CCPM_storeSource__c);
        system.debug('the soure is'+objOld.CCPM_storeSource__c);
    	if((objNew.CCPM_role__c != ObjOld.CCPM_role__c  && Objnew.CCPM_storeSource__c!=Label.CCPM_telesalesChannelName) || (objNew.CCPM_IsActive__c != ObjOld.CCPM_IsActive__c)) 
         {
    				objNew.CCPM_previousRole__c =  ObjOld.CCPM_role__c;
    				objNew.CCPM_previousactive__c =  ObjOld.CCPM_IsActive__c;
    				objNew.CCPM_IsUpdateFlag__c = true;
    	}    	
    }
}