VZDEV/src/objects/CCPM_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Record</label>
        <referenceTo>CCPM_RERecord__c</referenceTo>
        <relationshipLabel>Criterias</relationshipLabel>
        <relationshipName>CCPM_RECriterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_fieldName__c</fullName>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_fieldType__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Double</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CCPM_fieldType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equals</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Not Equal To</fullName>
                </value>
                <value>
                    <fullName>Contains</fullName>
                </value>
                <value>
                    <fullName>Does Not Contain</fullName>
                </value>
                <value>
                    <fullName>Starts With</fullName>
                </value>
                <value>
                    <fullName>Ends With</fullName>
                </value>
                <value>
                    <fullName>Greater Than</fullName>
                </value>
                <value>
                    <fullName>Greater Or Equal</fullName>
                </value>
                <value>
                    <fullName>Less Than</fullName>
                </value>
                <value>
                    <fullName>Less Or Equal</fullName>
                </value>
                <value>
                    <fullName>Is Null</fullName>
                </value>
                <value>
                    <fullName>Is Not Null</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_valueDate__c</fullName>
        <label>Value Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_valueDouble__c</fullName>
        <label>Value Double</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_valueText__c</fullName>
        <label>Value Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RE Criteria</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Criteria Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_RERecord__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_primaryObject__c</fullName>
        <label>Primary Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RE Record</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_RERecordController.cls
/**
*@name          CCPM_RERecordController 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          01/25/2018
*@description   This is a controller or class
*@Class         CCPM_RERecordController
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    01/25/2018   Initial Implementation.
*/
public with sharing class CCPM_RERecordController  {
    
    public RERecordPackage recordPackage{get;set;}
    public Map<String, Schema.sObjectField> mapTargetFields = new Map<String, Schema.sObjectField>();
    public Integer intCRowNum{get;set;}
    public boolean boolCloneRecord {get;set;}
    public String strRecordID{get;set;}
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  Constructor
	@param        N/A
	@return       N/A
	*/ 
    public CCPM_RERecordController(){
    	strRecordID = '';
        boolCloneRecord = false;
        try{
            recordPackage = new RERecordPackage();
            strRecordID =ApexPages.CurrentPage().getparameters().get('recordid'); 
            if(ApexPages.CurrentPage().getparameters().get('clone') == '1'){boolCloneRecord = true;}
            CCPM_RERecord__c objRecord = new CCPM_RERecord__c();
            if(strRecordID != ''){
                objRecord = [Select id, Name, CCPM_primaryObject__c, CCPM_active__c, CreatedDate,
                        CreatedById, CreatedBy.Name, LastModifiedBy.Name, LastModifiedDate, LastModifiedById,
                        (Select Id,CCPM_fieldName__c,CCPM_operator__c,CCPM_valueText__c,CCPM_active__c,CCPM_fieldType__c,
                        CCPM_valueDouble__c,CCPM_valueDate__c From CCPM_RECriterias__r)
                        From CCPM_RERecord__c WHERE id =:strRecordID];
                recordPackage = new RERecordPackage(objRecord, objRecord.CCPM_RECriterias__r);
            }
            else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Invalid RecordID. <br/>');
            	ApexPages.addMessage(myMsg);
            }
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Invalid RecordID. <br/>'+e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public PageReference save(){
        List<sObject> lstObjToInsert = new List<sobject>();
        List<sObject> lstObjToUpdate = new List<sobject>();
        if(boolCloneRecord){
            RERecordPackage clonerulePackage = recordPackage;
            clonerulePackage.objRecord.id = null;
            for(CCPM_Criteria__c objCri: clonerulePackage.mapCriteria.values()){
                objCri.id=null;
            }
            recordPackage = clonerulePackage;
        }
        try{
            upsert recordPackage.objRecord; 
            if(recordPackage.mapCriteria.size() > 0){
                for(CCPM_Criteria__c objCri : recordPackage.mapCriteria.values()){
                    if(objCri.CCPM_valueText__c != null && objCri.CCPM_valueText__c.contains('<Today>')){
                        objCri.CCPM_valueDate__c = null;
                    }
                    if(objCri.Id == null){ 
                        objCri.CCPM_Record__c = recordPackage.objRecord.id;
                        lstObjToInsert.add(objCri);
                    }
                    else{lstObjToUpdate.add(objCri);}
                }   
            }
            if(lstObjToInsert.size() > 0){ insert lstObjToInsert;}
            if(lstObjToUpdate.size() > 0){ update lstObjToUpdate;}
            PageReference viewPage = new PageReference('/apex/CCPM_RERecordViewPage?recordid='+recordPackage.objRecord.id);
            viewPage.setRedirect(true);
            return viewPage;
        }
        catch(Exception e){
            String error = 'ERROR in saving. \n';
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,error+e.getMessage());
            ApexPages.addMessage(myMsg);
            return null;
        }
    }
    
    public List<SelectOption> getFieldTypes(){
        List<SelectOption> fieldTypeList= new List<SelectOption>();
        if(String.isNotBlank(recordPackage.objRecord.CCPM_primaryObject__c)){
        	mapTargetFields = Schema.getGlobalDescribe().get(recordPackage.objRecord.CCPM_primaryObject__c).getDescribe().fields.getMap();
	        for(String key : mapTargetFields.KeySet()){
	            fieldTypeList.add(new SelectOption(mapTargetFields.get(key)+'', mapTargetFields.get(key).getDescribe().getLabel()+''));
	        }
	        fieldTypeList.sort();
        }
        return fieldTypeList;
    }
    
    public void setFieldType(){
        try{
            Schema.DisplayType ftype = mapTargetFields.get(recordPackage.mapCriteria.get(intCRowNum).CCPM_fieldName__c).getDescribe().getType();
            System.debug('**********ftype *************** '+ftype);
            if(ftype ==  Schema.DisplayType.DATE || ftype ==  Schema.DisplayType.DATETIME){
                recordPackage.mapCriteria.get(intCRowNum).CCPM_fieldType__c = 'Date';
            }
            else if(ftype ==  Schema.DisplayType.INTEGER || ftype ==  Schema.DisplayType.DOUBLE || ftype ==  Schema.DisplayType.PERCENT || ftype ==  Schema.DisplayType.CURRENCY){
                recordPackage.mapCriteria.get(intCRowNum).CCPM_fieldType__c = 'Double';
            }
            else if(ftype ==  Schema.DisplayType.BOOLEAN){
                recordPackage.mapCriteria.get(intCRowNum).CCPM_fieldType__c = 'Boolean';
            }
            else {
                recordPackage.mapCriteria.get(intCRowNum).CCPM_fieldType__c = 'Text';
            }
            System.debug('*****************recordPackage.mapCriteria.get(intCRowNum)************'+recordPackage.mapCriteria.get(intCRowNum));
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot Delete Row. Error: '+e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public void removeCriteriaRow(){
        CCPM_Criteria__c objCriToRemove = null;
        try{
            if(recordPackage.mapCriteria.get(intCRowNum).id != null){
                objCriToRemove = recordPackage.mapCriteria.get(intCRowNum);
                delete objCriToRemove;
            }
            recordPackage.mapCriteria.remove(intCRowNum);
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot Delete Row. Error: '+e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public PageReference edit(){
        PageReference viewPage = new PageReference('/apex/CCPM_RERecordEditPage?recordid='+recordPackage.objRecord.id);
        viewPage.setRedirect(true);
        return viewPage;
    }
    
    public PageReference cloneRecordPackage(){
        PageReference viewPage = new PageReference('/apex/CCPM_RERecordEditPage?recordid='+recordPackage.objRecord.id+'&clone=1');
        viewPage.setRedirect(true);
        return viewPage;
    }
    
    
    
    /**
	*@name          RERecordPackage 
	*@author        Bharath Ammanamanchi (Deloitte)
	*@date          01/10/2018
	*@description   This is a wrapper class
	*@testClass     
	Modification    Log:
	------------------------------------------------------------------------------------
	Developer                          Date         Description
	------------------------------------------------------------------------------------
	Bharath Ammanamanchi (Deloitte)    01/10/2018   Initial Implementation.
	*/
    public class RERecordPackage{
        public CCPM_RERecord__c objRecord{get; set;}
        public Map<Integer, CCPM_Criteria__c> mapCriteria{get;set;}
        Integer intCRowNum = 0;
        
        public RERecordPackage(CCPM_RERecord__c objRecord, List<CCPM_Criteria__c> lstcriteria){
            
            this.objRecord = objRecord;
            mapCriteria = new Map<Integer, CCPM_Criteria__c>();
            for(CCPM_Criteria__c objC : lstcriteria){
                mapCriteria.put(intCRowNum, objC);
                intCRowNum++;
            }
        }
        
        public RERecordPackage(){
            
            objRecord= new CCPM_RERecord__c(CCPM_active__c=true);
            mapCriteria = new Map<Integer, CCPM_Criteria__c>();
        }
        
        public void addCriteriaRow(){
            mapCriteria.put(intCRowNum, new CCPM_Criteria__c(CCPM_fieldName__c='Id',CCPM_active__c=true,CCPM_fieldType__c='Text', CCPM_operator__c='Equals'));
            intCRowNum++;
        }
    }
}