VZDEV/src/objects/CCPM_globalSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Settings for verizon lead &amp; prospect management</description>
    <fields>
        <fullName>CCPM_cartClosedStatus__c</fullName>
        <description>Contains all the closed status of the Carts</description>
        <label>Cart Closed Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_leadOpenStatus__c</fullName>
        <description>Lead Open Statuses</description>
        <inlineHelpText>Lead Open Statuses</inlineHelpText>
        <label>Lead Open Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Global Setting</label>
</CustomObject>

VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_leadSubStatus__c</fullName>
        <description>This field is used to store the Lead Sub Status</description>
        <inlineHelpText>Populated when the status is “Responded” or “Qualified”</inlineHelpText>
        <label>Lead Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>Action Required</fullName>
                </value>
                <value>
                    <fullName>In Discussion</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Needs Store Reassignment</fullName>
                </value>
                <value>
                    <fullName>Service Issue</fullName>
                </value>
                <value>
                    <fullName>Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart-Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart Opt Out</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_clickToCallControllerTest.cls
@isTest
public class CCPM_clickToCallControllerTest {

    public static list<lead> lstLead;
    public static list<user> lstUser;
    public static String strLeadProspectRT = 
        Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.CCPM_LeadProspectRecordType).getRecordTypeId();
    
    static{
        lstUser = CCPM_testDataUtil.createTestUsers('System Administrator', 1);
        lstUser[0].mobilePhone = '0323298238';
        insert lstUser;
        lstLead = CCPM_testDataUtil.createLead(1,strLeadProspectRT,false,'Prospect Abandoned Cart Digital');
        insert lstLead;
        lstLead[0].status = 'Qualified';
        lstLead[0].CCPM_leadSubStatus__c = 'In Discussion';
        update lstLead[0];
        
    }
    
    static testMethod void testGetResponse() {
        
        system.runAs(lstUser[0]){
            
            insert new CCPM_globalSetting__c(CCPM_cartClosedStatus__c = 'Expired:Converted:Dismissed',CCPM_leadOpenStatus__c = 'New:Eligible:Contacted:Responded:Qualified');

            test.startTest();
            CCPM_globalSetting__c objCustSettings = CCPM_globalSetting__c.getOrgDefaults();
            Test.setMock(WebServiceMock.class, new CCPM_clickToCallMock());
            ccpm_clicktoCallController.respWrapper retWrapper = CCPM_clicktoCallController.getResponse(lstLead[0].id,false);
            system.debug('re-- '+retwrapper);
            Test.stopTest();
        }
    }
}