VZDEV/src/objects/CCPM_Action__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_endDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_startDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>RE Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_fieldName__c</fullName>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_fieldType__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Double</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CCPM_fieldType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equals</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Not Equal To</fullName>
                </value>
                <value>
                    <fullName>Contains</fullName>
                </value>
                <value>
                    <fullName>Does Not Contain</fullName>
                </value>
                <value>
                    <fullName>Starts With</fullName>
                </value>
                <value>
                    <fullName>Ends With</fullName>
                </value>
                <value>
                    <fullName>Greater Than</fullName>
                </value>
                <value>
                    <fullName>Greater Or Equal</fullName>
                </value>
                <value>
                    <fullName>Less Than</fullName>
                </value>
                <value>
                    <fullName>Less Or Equal</fullName>
                </value>
                <value>
                    <fullName>Is Null</fullName>
                </value>
                <value>
                    <fullName>Is Not Null</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule</label>
        <referenceTo>CCPM_Rule__c</referenceTo>
        <relationshipLabel>Criterias</relationshipLabel>
        <relationshipName>CCPM_Criterias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_valueDate__c</fullName>
        <label>Value Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_valueDouble__c</fullName>
        <label>Value Double</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCPM_valueText__c</fullName>
        <label>Value Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RE Criteria</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Criteria Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_Rule__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CCPM_endDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_existingRecord__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Existing Record</label>
        <referenceTo>CCPM_RERecord__c</referenceTo>
        <relationshipLabel>RE Rules (Existing Record)</relationshipLabel>
        <relationshipName>CCPM_exitingRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_newRecord__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>New Record</label>
        <referenceTo>CCPM_RERecord__c</referenceTo>
        <relationshipLabel>RE Rules (New Record)</relationshipLabel>
        <relationshipName>CCPM_newRecord</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CCPM_primaryObject__c</fullName>
        <label>Primary Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_startDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CCPM_winningRecord__c</fullName>
        <label>Winning Record</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Record</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Existing Record</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RE Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VZDEV/src/objects/CCPM_RuleAction__c.object
<CustomObject>
    <fields>
        <fullName>CCPM_action__c</fullName>
        <label>Action</label>
        <referenceTo>CCPM_Action__c</referenceTo>
        <relationshipLabel>RE Rule Actions</relationshipLabel>
        <relationshipName>CCPM_RERuleActions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CCPM_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_rule__c</fullName>
        <label>Rule</label>
        <referenceTo>CCPM_Rule__c</referenceTo>
        <relationshipLabel>RE Rule Actions</relationshipLabel>
        <relationshipName>CCPM_RERuleActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RE Rule Action</label>
    <nameField>
        <displayFormat>RA{00000}</displayFormat>
        <label>Rule Action Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_RERuleController.cls
/**
*@name          CCPM_RERuleController 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          01/10/2018
*@description   This is a controller for CCPM_RERuleviewPage
*@testClass     CCPM_RERuleController
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    01/10/2018   Initial Implementation.
*/
public with sharing class CCPM_RERuleController  {
    
    public RERulePackage rulePackage{get;set;}
    public Map<String, Schema.sObjectField> mapTargetFields = new Map<String, Schema.sObjectField>();
    public Integer intCRowNum{get;set;}
    public Integer intRARowNum{get;set;}
    public boolean boolCloneRecord {get;set;}
    public String strRuleRecordType {get;set;}
    
    /**
	@author       Bharath Ammanamanchi (Deloitte)
	@description  Constructor
	@param        N/A
	@return       N/A
	*/ 
    public CCPM_RERuleController(){
    	String strRuleID = '';
        boolCloneRecord = false;
        strRuleRecordType = '';
        try{
            rulePackage = new RERulePackage();
            strRuleID =ApexPages.CurrentPage().getparameters().get('ruleid'); 
            if(ApexPages.CurrentPage().getparameters().get('clone') == '1'){boolCloneRecord = true;}
            CCPM_Rule__c objrule = new CCPM_Rule__c();
            if(strRuleID != ''){
                objrule = [Select id, Name, CCPM_primaryObject__c, CCPM_startDate__c, CCPM_endDate__c, CCPM_active__c, CreatedDate, RecordType.Name, 
                        CreatedById, CreatedBy.Name, LastModifiedBy.Name, LastModifiedDate, LastModifiedById, CCPM_description__c,
                        CCPM_existingRecord__c,CCPM_newRecord__c, CCPM_winningRecord__c, 
                        (Select Id,CCPM_fieldName__c,CCPM_operator__c,CCPM_valueText__c,CCPM_active__c,CCPM_fieldType__c,CCPM_valueDouble__c,CCPM_valueDate__c From CCPM_Criterias__r),
                        (Select Id,CCPM_action__c,CCPM_active__c,CCPM_Action__r.Name From CCPM_RERuleActions__r) 
                        From CCPM_Rule__c WHERE id =:strRuleID];
                rulePackage = new RERulePackage(objrule, objrule.CCPM_Criterias__r, objrule.CCPM_RERuleActions__r);
                strRuleRecordType = objrule.RecordType.Name;
            }
            else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Invalid RuleID. <br/>');
            	ApexPages.addMessage(myMsg);
            }
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Invalid RuleID. <br/>'+e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public PageReference save(){
        List<sObject> lstObjToInsert = new List<sobject>();
        List<sObject> lstObjToUpdate = new List<sobject>();
        if(boolCloneRecord){
            RERulePackage clonerulePackage = rulePackage;
            clonerulePackage.objrule.id = null;
            for(CCPM_Criteria__c objCri: clonerulePackage.mapCriteria.values()){
                objCri.id=null;
            }
            for(CCPM_RuleAction__c objRA: clonerulePackage.mapRuleAction.values()){
                objRA.id=null;
            }
            rulePackage = clonerulePackage;
        }
        try{
            upsert rulePackage.objrule; 
            if(rulePackage.mapCriteria.size() > 0){
                for(CCPM_Criteria__c objCri : rulePackage.mapCriteria.values()){
                    if(objCri.CCPM_valueText__c != null && objCri.CCPM_valueText__c.contains('<Today>')){
                        objCri.CCPM_valueDate__c = null;
                    }
                    if(objCri.Id == null){ 
                        objCri.CCPM_rule__c = rulePackage.objrule.id;
                        lstObjToInsert.add(objCri);
                    }
                    else{lstObjToUpdate.add(objCri);}
                }   
            }
            if(rulePackage.mapRuleAction.size() > 0){
                for(CCPM_RuleAction__c objRA : rulePackage.mapRuleAction.values()){
                    if(objRA.Id == null){ 
                        objRA.CCPM_rule__c = rulePackage.objrule.id;
                        lstObjToInsert.add(objRA);
                    }
                    else{lstObjToUpdate.add(objRA);}
                }
            }
            if(lstObjToInsert.size() > 0){ insert lstObjToInsert;}
            if(lstObjToUpdate.size() > 0){ update lstObjToUpdate;}
            PageReference viewPage = new PageReference('/apex/CCPM_RERuleViewPage?ruleid='+rulePackage.objrule.id);
            viewPage.setRedirect(true);
            return viewPage;
        }
        catch(Exception e){
            String error = 'ERROR in saving. \n';
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,error+e.getMessage());
            ApexPages.addMessage(myMsg);
            return null;
        }
    }
    
    public List<SelectOption> getFieldTypes(){
        List<SelectOption> fieldTypeList= new List<SelectOption>();
        if(String.isNotBlank(rulePackage.objrule.CCPM_primaryObject__c)){
        	mapTargetFields = Schema.getGlobalDescribe().get(rulePackage.objrule.CCPM_primaryObject__c).getDescribe().fields.getMap();
	        for(String key : mapTargetFields.KeySet()){
	            fieldTypeList.add(new SelectOption(mapTargetFields.get(key)+'', mapTargetFields.get(key).getDescribe().getLabel()+''));
	        }
	        fieldTypeList.sort();
        }
        return fieldTypeList;
    }
    
    public void setFieldType(){
        try{
            Schema.DisplayType ftype = mapTargetFields.get(rulePackage.mapCriteria.get(intCRowNum).CCPM_fieldName__c).getDescribe().getType();
            System.debug('**********ftype *************** '+ftype);
            if(ftype ==  Schema.DisplayType.DATE || ftype ==  Schema.DisplayType.DATETIME){
                rulePackage.mapCriteria.get(intCRowNum).CCPM_fieldType__c = 'Date';
            }
            else if(ftype ==  Schema.DisplayType.INTEGER || ftype ==  Schema.DisplayType.DOUBLE || ftype ==  Schema.DisplayType.PERCENT || ftype ==  Schema.DisplayType.CURRENCY){
                rulePackage.mapCriteria.get(intCRowNum).CCPM_fieldType__c = 'Double';
            }
            else if(ftype ==  Schema.DisplayType.BOOLEAN){
                rulePackage.mapCriteria.get(intCRowNum).CCPM_fieldType__c = 'Boolean';
            }
            else {
                rulePackage.mapCriteria.get(intCRowNum).CCPM_fieldType__c = 'Text';
            }
            System.debug('*****************rulePackage.mapCriteria.get(intCRowNum)************'+rulePackage.mapCriteria.get(intCRowNum));
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot Delete Row. Error: '+e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public void removeCriteriaRow(){
        CCPM_Criteria__c objCriToRemove = null;
        try{
            if(rulePackage.mapCriteria.get(intCRowNum).id != null){
                objCriToRemove = rulePackage.mapCriteria.get(intCRowNum);
                delete objCriToRemove;
            }
            rulePackage.mapCriteria.remove(intCRowNum);
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot Delete Row. Error: '+e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public void removeRuleActionRow(){
        CCPM_RuleAction__c objRAToRemove = null;
        try{
            if(rulePackage.mapRuleAction.get(intRARowNum).id != null){
                objRAToRemove = rulePackage.mapRuleAction.get(intRARowNum);
                delete objRAToRemove;
            }
            rulePackage.mapRuleAction.remove(intRARowNum);
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot Delete Row. Error: '+e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public PageReference edit(){
        PageReference viewPage = new PageReference('/apex/CCPM_RERuleEditPage?ruleid='+rulePackage.objrule.id);
        viewPage.setRedirect(true);
        return viewPage;
    }
    
    public PageReference cloneRulePackage(){
        PageReference viewPage = new PageReference('/apex/CCPM_RERuleEditPage?ruleid='+rulePackage.objrule.id+'&clone=1');
        viewPage.setRedirect(true);
        return viewPage;
    }
    
    
    
    /**
	*@name          RERulePackage 
	*@author        Bharath Ammanamanchi (Deloitte)
	*@date          01/10/2018
	*@description   This is a wrapper class
	*@testClass     
	Modification    Log:
	------------------------------------------------------------------------------------
	Developer                          Date         Description
	------------------------------------------------------------------------------------
	Bharath Ammanamanchi (Deloitte)    01/10/2018   Initial Implementation.
	*/
    public class RERulePackage{
        public CCPM_Rule__c objRule{get; set;}
        public Map<Integer, CCPM_Criteria__c> mapCriteria{get;set;}
        public Map<Integer, CCPM_RuleAction__c> mapRuleAction{get;set;} 
        Integer intCRowNum = 0;
        Integer intRARowNum = 0;
        
        public RERulePackage(CCPM_Rule__c objRule, List<CCPM_Criteria__c> lstcriteria, List<CCPM_RuleAction__c> lstRuleAction){
            
            this.objRule = objRule;
            mapCriteria = new Map<Integer, CCPM_Criteria__c>();
            for(CCPM_Criteria__c objC : lstcriteria){
                mapCriteria.put(intCRowNum, objC);
                intCRowNum++;
            }
            
            mapRuleAction = new Map<Integer, CCPM_RuleAction__c>();
            for(CCPM_RuleAction__c objRA : lstRuleAction){
                mapRuleAction.put(intRARowNum, objRA);
                intRARowNum++;
            }
            
        }
        
        public RERulePackage(){
            
            objRule= new CCPM_Rule__c(CCPM_active__c=true);
            mapCriteria = new Map<Integer, CCPM_Criteria__c>();
            mapRuleAction = new Map<Integer, CCPM_RuleAction__c>();
            
        }
        
        public void addCriteriaRow(){
            mapCriteria.put(intCRowNum, new CCPM_Criteria__c(CCPM_fieldName__c='Id',CCPM_active__c=true,CCPM_fieldType__c='Text', CCPM_operator__c='Equals'));
            intCRowNum++;
        }
        
        public void addRuleActionRow(){
            mapRuleAction.put(intRARowNum, new CCPM_RuleAction__c(CCPM_active__c=true));
            intRARowNum++;
        }
    }
}