VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSFollowUpDate__c</fullName>
        <inlineHelpText>The date &amp; time for the SMS to be scheduled to be sent</inlineHelpText>
        <label>SMS Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_confirmEmail__c</fullName>
        <description>Confirm Email address specified by the customer when creating the cart</description>
        <label>Confirm Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_confirmMTN__c</fullName>
        <description>Confirm Mobile number which has been used to create the cart</description>
        <label>Confirm MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_createdDate__c</fullName>
        <label>Cart Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <description>Email address specified by the customer when creating the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Email of the lead / prospect. Required to save a Prospect if the MTN is unavailable.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_eventType__c</fullName>
        <inlineHelpText>The Conversation Topic that requires an SMS follow up to be sent.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samsung GS9 BOGO</fullName>
                </value>
                <value>
                    <fullName>TMP OE - Q2 2018</fullName>
                </value>
                <value>
                    <fullName>Add a Line</fullName>
                </value>
                <value>
                    <fullName>Confirming with Family First</fullName>
                </value>
                <value>
                    <fullName>Connected Device</fullName>
                </value>
                <value>
                    <fullName>Contract Terminating Soon</fullName>
                </value>
                <value>
                    <fullName>Feature Add</fullName>
                </value>
                <value>
                    <fullName>Gift for Upcoming Occasion</fullName>
                </value>
                <value>
                    <fullName>iPhone X</fullName>
                </value>
                <value>
                    <fullName>iPhone X send message</fullName>
                </value>
                <value>
                    <fullName>New Service</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>Special Event</fullName>
                </value>
                <value>
                    <fullName>Tablets</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_ProspectManualLeadUpdateBatchTest.cls
@isTest
public class CCPM_ProspectManualLeadUpdateBatchTest 
{
    @isTest
    public static void LeadTest()
    {
      CCPM_testdataFactory.createCustomSetting();
       
        Lead objCart=new Lead();
        objCart.LastName='testsample';
        objCart.FirstName='Inactive test';
        objCart.Status='New';
        objCart.Company = '1';  
        objcart.CCPM_accountUniqueID__c='23467';
        // objCart.CCPM_eventType__c = 'SMB';
        objcart.CCPM_SMSFollowUpDate__c = system.now().addHours(5);
        objCart.CCPM_mobileNumber__c = '3213187287';
        objCart.CCPM_email__c ='test@gmail.com';
        objCart.CCPM_confirmEmail__c='test@gmail.com';
        datetime date1=Datetime.now();
        objCart.CCPM_createdDate__c=date1.addHours(-5);
        objCart.CCPM_SMSLegalOptIn__c =true;
        objCart.CCPM_confirmMTN__c= '3213187287';
        objCart.CCPM_LeadType__c = 'Prospect SFDC Manual';
        insert objCart;
        CCPM_ProspectManualLeadUpdateBatch objbatch = new CCPM_ProspectManualLeadUpdateBatch();
            Database.executeBatch(objbatch);    
 // Creating the object for the scheduler class and invoking the execution
       String StrCRONEXP = ccpm_staticConstants.StrCRONEXP;
    CCPM_ProspectManualLeadUpdateBatchJob objSch = new CCPM_ProspectManualLeadUpdateBatchJob(); 
        system.schedule('CCPM_ProspectManualLeadUpdateBatchTest- 10 Mins', StrCRONEXP, objSch); 
    }

}