VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSFollowUpDate__c</fullName>
        <inlineHelpText>The date &amp; time for the SMS to be scheduled to be sent</inlineHelpText>
        <label>SMS Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_SMSLegalOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_accountUniqueID__c</fullName>
        <description>Unique identifier of customer generated in staging(Oracle) based on account number. This unique identifier will always be same based on account number so that we can use this key for upsert logic</description>
        <externalId>true</externalId>
        <label>Account Unique ID</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCPM_confirmEmail__c</fullName>
        <description>Confirm Email address specified by the customer when creating the cart</description>
        <label>Confirm Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_confirmMTN__c</fullName>
        <description>Confirm Mobile number which has been used to create the cart</description>
        <label>Confirm MTN</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CCPM_createdDate__c</fullName>
        <label>Cart Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_email__c</fullName>
        <description>Email address specified by the customer when creating the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Email of the lead / prospect. Required to save a Prospect if the MTN is unavailable.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CCPM_eventType__c</fullName>
        <inlineHelpText>The Conversation Topic that requires an SMS follow up to be sent.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Samsung GS9 BOGO</fullName>
                </value>
                <value>
                    <fullName>TMP OE - Q2 2018</fullName>
                </value>
                <value>
                    <fullName>Add a Line</fullName>
                </value>
                <value>
                    <fullName>Confirming with Family First</fullName>
                </value>
                <value>
                    <fullName>Connected Device</fullName>
                </value>
                <value>
                    <fullName>Contract Terminating Soon</fullName>
                </value>
                <value>
                    <fullName>Feature Add</fullName>
                </value>
                <value>
                    <fullName>Gift for Upcoming Occasion</fullName>
                </value>
                <value>
                    <fullName>iPhone X</fullName>
                </value>
                <value>
                    <fullName>iPhone X send message</fullName>
                </value>
                <value>
                    <fullName>New Service</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>SMB</fullName>
                </value>
                <value>
                    <fullName>Special Event</fullName>
                </value>
                <value>
                    <fullName>Tablets</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_leadType__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Campaign</fullName>
                </value>
                <value>
                    <fullName>Customer SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Quotes</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales POS Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Prospect Telesales SFDC Manual</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Retail</fullName>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart Digital</fullName>
                </value>
                <value>
                    <fullName>Customer Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Customer Abandoned Visit</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Prospect Abandoned Cart</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_CollectionTest.cls
/**
*@name          CCPM_CollectionTest 
*@author        Manjunath Keshava (Deloitte)
*@date          06/13/2017
@description    This is the Unit Test Class for the CCPM_Collection Class  
@testClass      
Modification    Log:
------------------------------------------------------------------------------------
Developer                       Date                                Description
------------------------------------------------------------------------------------
Manjunath Keshava (Deloitte)    10/25/2017                          Original Version
Paras Shah (Deloitte)           11/28/2017                          Additional Test case scenario
*/
@isTest
public class CCPM_CollectionTest 
{
    @isTest
    public static void isNotNullEmptyTest()
    {
        CCPM_testdataFactory.createCustomSetting();
        Lead objCart=new Lead();
        objCart.LastName='testsample';
        objCart.FirstName='Inactive test';
        objCart.Status='New';
        objCart.Company = '1';  
        objcart.CCPM_accountUniqueID__c='23467';
        //objCart.CCPM_eventType__c = 'SMB';
        objcart.CCPM_SMSFollowUpDate__c = system.now().addHours(5);
        objCart.CCPM_mobileNumber__c = '3213187287';
        objCart.CCPM_email__c ='test@gmail.com';
        objCart.CCPM_confirmEmail__c='test@gmail.com';
        datetime date1=Datetime.now();
        objCart.CCPM_createdDate__c=date1.addHours(-5);
        objCart.CCPM_SMSLegalOptIn__c =true;
        objCart.CCPM_confirmMTN__c= '3213187287';
        objCart.CCPM_LeadType__c = 'Customer Abandoned Cart Digital';
        
        
        insert objCart;
        
        map<id,lead> maplead= new map<id,lead>();
        Boolean isNotNullEmplty = CCPM_collection.isNotNullEmpty(maplead);
        System.assertEquals(false, isNotNullEmplty);
        
        map<String,lead> mapleadStr= new map<String,lead>();
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(mapleadStr);
        System.assertEquals(false, isNotNullEmplty);
        
        maplead.put(objcart.id, objCart);
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(maplead);
        System.assertEquals(true, isNotNullEmplty);
        list<string> lststr= new  list<string>();
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(lststr);
        System.assertEquals(false, isNotNullEmplty);
        
        lststr.add('Test');
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(lststr);
        System.assertEquals(true, isNotNullEmplty);
        
        Set<sObject> setSObj = new Set<sObject>();
        
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(setSObj);
        System.assertEquals(false, isNotNullEmplty);
        setSObj.add(objCart);
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(setSObj);
        System.assertEquals(true, isNotNullEmplty);
         CCPM_collection.populateSetFromString('strCustom,Label', ',');
                Set<string> setString = new Set<string>();
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(setString);
                        System.assertEquals(false, isNotNullEmplty);
                    setString.add('Test');
                isNotNullEmplty = CCPM_collection.isNotNullEmpty(setString);
                System.assertEquals(true, isNotNullEmplty);
        list<sObject> lstSObj = new list<sObject>();
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(lstSObj);
        System.assertEquals(false, isNotNullEmplty);
        lstSObj.add(objCart);
        isNotNullEmplty = CCPM_collection.isNotNullEmpty(lstSObj);
        System.assertEquals(true, isNotNullEmplty);
        
        //Updates by Paras Shah
        
        setString.add('TestString1');
        setString.add('TestString2');  
        
        Map<String, Set<String>> mapStringSetString = new Map<String, Set<String>>();
        mapStringSetString.put('mapKeyOne',setString);
        Boolean boolTestMapWithStringSetString = CCPM_collection.isNotNullEmpty(mapStringSetString);
        
        Map<String, List<sObject>> mapStringSObject = new Map<String, List<sObject>>();
        mapStringSObject.put('mapKeyOne',lstSObj);
        Boolean boolTestMapWithStringSObject = CCPM_collection.isNotNullEmpty(mapStringSObject);
        
        Map<String, Boolean> mapStringBoolean = new Map<String, Boolean>();
        mapStringBoolean.put('mapKeyOne',true);
        Boolean boolTestMapStringBoolean = CCPM_collection.isNotNullEmpty(mapStringBoolean);
        
        Map<String, String> mapStringString = new Map<String, String>();
        mapStringString.put('mapKeyOne','StringOne');
        Boolean boolTestMapStringString = CCPM_collection.isNotNullEmpty(mapStringString);
    }
    

}