VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_cartUniqueID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique Identified to create/update carts(leads). The format will be &apos;A:&apos;+Account Number&apos; +&apos;-M:&apos; + Mobile Number + &apos;-S:&apos; + Lead Status. This field will be used to upset leads in Salesforce for carts (leads) for existing customers.</description>
        <externalId>true</externalId>
        <label>Cart Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CCPM_mobileNumber__c</fullName>
        <description>Mobile number which has been used to create the cart</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Mobile number of the lead / prospect</inlineHelpText>
        <label>MTN</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_ProspectManualLeadUpdateBatch.cls
/**
@author        Manjunath Keshava (Deloitte)
@description	Update the Cart unique ID for Prospects and Manual Leads
@param         None
@return          
*/ 
global with sharing class CCPM_ProspectManualLeadUpdateBatch implements Database.Batchable<sObject>,Database.Stateful  
{
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        // Set of Strings for the lead open status
        set<string> setOpenLeadStatus = CCPM_staticConstants.setOpenLeadStatus;
        string strProspectRecordType =Schema.SObjectType.Lead.getRecordTypeInfosByName().get(label.CCPM_LeadProspectRecordType).getRecordTypeId();
        //string strLeadRecordType=Schema.SObjectType.Lead.getRecordTypeInfosByName().get(label.CCPM_LeadCustomerAbandonedCartRecordTypeID).getRecordTypeId();
        String strquery = label.CCPM_PropsectNullCartUniqueIdQuery;
        return Database.getQueryLocator(strquery);
    }
    
    global void execute(Database.BatchableContext BC, List<Lead> scope ) 
    {
            list<lead> lstUpdatedLead = new list<lead>();
        for(Lead objLead:scope)
        {
            string strTimeStamp = string.valueOf(system.now());
            string strMtn= objlead.CCPM_mobileNumber__c;
            string strcartUniqueID= strTimeStamp + strMtn;
            objlead.CCPM_cartUniqueID__c=CCPM_EncryptKey.CCPM_EncryptKey(strcartUniqueID);
            lstUpdatedLead.add(objLead);
        }
        if(lstUpdatedLead!=null && lstUpdatedLead.isEmpty()==false)
        {
            //used to run the batch for all the records except the failed records
            Database.SaveResult[] updateLeadData = Database.update(lstUpdatedLead, false);  
            for (Database.SaveResult objresult : updateLeadData) {
                if (!objresult.isSuccess())
                {
                    for (Database.Error objerror : objresult.getErrors())
                    {
                        System.debug('Error: '+ objerror.getStatusCode() + ' ' + objerror.getMessage());
                    }
                }
            }
            
            
        }
    }
    
    
    global void finish(Database.BatchableContext BC)
    {
        
    }
    
    
}