VZDEV/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CCPM_SMSResponseReceivedDateTime__c</fullName>
        <description>Holds the date/time when SMS response was received</description>
        <label>SMS Response Received Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CCPM_firstPredefinedSMSFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Predefined SMS Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CCPM_leadSubStatus__c</fullName>
        <description>This field is used to store the Lead Sub Status</description>
        <inlineHelpText>Populated when the status is “Responded” or “Qualified”</inlineHelpText>
        <label>Lead Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opted Out</fullName>
                </value>
                <value>
                    <fullName>Action Required</fullName>
                </value>
                <value>
                    <fullName>In Discussion</fullName>
                </value>
                <value>
                    <fullName>Appointment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Needs Store Reassignment</fullName>
                </value>
                <value>
                    <fullName>Service Issue</fullName>
                </value>
                <value>
                    <fullName>Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart-Disinterested</fullName>
                </value>
                <value>
                    <fullName>Cart Opt Out</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

VZDEV/src/classes/CCPM_LeadsAwaitingResponseApexTest.cls
/**
*@name          CCPM_LeadsAwaitingResponseApexTest
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          12/15/2017
*@description   Test Class
Modification    Log:
------------------------------------------------------------------------------------
Developer                                     Date               Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)             12/15/2017         Original Version       
*/
@isTest
public class CCPM_LeadsAwaitingResponseApexTest {
    @isTest
    public static void loadComponentWithRecordsTest(){
        test.startTest();
        CCPM_testDataFactory.createCustomSetting();
        List<Lead> lstLead = new List<Lead>();
        lstLead = CCPM_testDataFactory.createmyActiveLeadsTest(5, 'Confirming with Family First', 'Prospect SFDC Manual');
        insert lstLead;
        lstLead[0].status='Responded';
        lstLead[0].CCPM_Leadsubstatus__c='Action Required';
        lstLead[0].CCPM_SMSResponseReceivedDateTime__c=System.now().addHours(-7);
        update lstLead[0];
        System.assert(CCPM_LeadsAwaitingResponseApexController.loadComponentWithRecords(null,null,null,'0')!=null);
        lstLead[0].CCPM_firstPredefinedSMSFlag__c=true;
        update lstLead;
        System.assert(CCPM_LeadsAwaitingResponseApexController.loadComponentWithRecords(null,null,null,'0')!=null);
        lstLead[0].RecordTypeId=Schema.SObjectType.Lead.getRecordTypeInfosByName().get(Label.CCPM_leadCustomerCartRT).getRecordTypeId();
        lstLead[0].CCPM_firstPredefinedSMSFlag__c=false;
        update lstLead[0];
        System.assert(CCPM_LeadsAwaitingResponseApexController.loadComponentWithRecords(null,null,null,'0')!=null);
        test.stopTest();
    }
    
}